### ISSUE TITLE
Research multi-label

### ISSUE THREAD

**Issue by rafsun42** [apache/age#1004]

**Comment by WendelLana** [comment]
We can continue to use a separate table for each label, where the table name corresponds to the label name and each table has its own ID, however, these tables will only contain the vertex/edge IDs.
Then utilize only the global vertex table (graph_name._ag_label_vertex) and global edge table (graph_name._ag_label_edge) to store the information of each vertex/edge (its properties and so on). 

At last, we should create two junction tables: one for vertices and one for edges. These junction tables will include the vertex/edge ID and its corresponding label ID, ordered by the vertex/edge ID. For instance, the junction table for vertices would resemble the following:

vertex_id    |    label_id
6842625    |    1
6842625    |    4
6842626    |    1
6842626    |    2

**Comment by rafsun42** [comment]
# Benchmark test of multi-label (as an array of label ids)

## Structure of vertex table

```sql
CREATE TABLE intarray_test.vertex_default
(
    id bigint,
    label_ids int4[] NOT NULL
    -- property column not included
);
```

## Populating the table

* Number of vertices (rows) inserted is: 10,000,000 (ten million).

* Number of labels each vertex have is: between 1 to 4.

* Label IDs range from 1 to 9.

* Sample of table content:

```
(pg-13.9) agedev=*# SELECT * FROM intarray_test.vertex_default LIMIT 10;
   id    | label_ids 
---------+-----------
 9891835 | {8,3}
 9891836 | {1,3,6}
 9891837 | {2}
 9891838 | {6,4,1,5}
 9891839 | {9,5,4,1}
 9891840 | {9,4,5}
 9891841 | {4,8}
 9891842 | {9,8,4}
 9891843 | {1,4}
 9891844 | {5,7,4,1}
(10 rows)
```

## Queries that are tested

1. `MATCH (:1)`,
Consider 1 as both label ID and label name.

2. `MATCH (:1|2)`.
Matches 1 or 2. Similar to union.

3. `MATCH(:1:2)`.
Matches 1 and 2. Similar to intersection.

4. Matches exactly 1 and 2. Similar to equality.

```sql
EXPLAIN (ANALYZE, VERBOSE, BUFFERS) SELECT *
FROM intarray_test.vertex_default WHERE '{1}'::int4[] <@ label_ids;

EXPLAIN (ANALYZE, VERBOSE, BUFFERS) SELECT *
FROM intarray_test.vertex_default WHERE '{1}'::int4[] <@ label_ids OR '{2}'::int4[] <@ label_ids ;

EXPLAIN (ANALYZE, VERBOSE, BUFFERS) SELECT *
FROM intarray_test.vertex_default WHERE '{1,2}'::int4[] <@ label_ids;

EXPLAIN (ANALYZE, VERBOSE, BUFFERS) SELECT *
FROM intarray_test.vertex_default WHERE '{1,2}'::int4[] <@ label_ids AND label_ids <@ '{1,2}'::int4[];
```

## Use of index and cluster

### Index

A table `vertex_indexed` is created. `Gist` index is added on `label_ids`.

### Cluster

A table `vertex_clustered` is created. `Gist` index is also added on `label_ids`.

Additionally, the content of the table is clustered (ordering of physical table) by label ids:

* Smaller length of array label_ids goes first.

* For similar length of array label_ids, order by the content of the array in descending order.

For example, physical order of label_id column would look like this in the clustered table:
```
{1}
{1}
{2}
{2}
{3}
{1,2}
{1,2}
{1,2}
{1,3}
{1,3}
{2,4}
{3,8}
{1,2,8}
{1,4,5}
{4,5,6}
...
```

## Benchmark result

The above queries are run on the 3 tables.

Note: the `intarray` module needs to be installed to run the queries.

Execution time retrieved from the EXPLAIN ANALYZE command is provided below:

|   | vertex_default  | vertex_indexed  | vertex_clustered  |
|---|---|---|---|
|  Query 1 | 11198.419 ms  | 8218.173 ms  | 4909.334 ms  |
|  Query 2 |  18695.878 ms | 15470.613 ms (seq scan) | 9666.337 ms  |
|  Query 3 | 11850.516 ms  | 7518.450 ms  | 1760.783 ms  |
|  Query 4 |  5664.825 ms (para seq scan) |  9095.456 ms |  1746.895 ms |


## Conclusion

Clustered table with Gist index performs better other two tables.

Caveat is clustering process takes time. But, it is useful for analytical databases where data is read-only. So, the table needs to be clustered only once. On the other hand, transactional databases, where CREATE and SET are frequent, re-clustering after every insert is not a usable solution.

**Comment by Zainab-Saad** [comment]
> On the other hand, transactional databases, where CREATE and SET are frequent, re-clustering after every insert is not a usable solution.

Would it be practically feasible if rather than re-clustering after every table insertion/updation, re-clustering is done only before the first MATCH after the clustered was disordered (will have to look for a way to find whether the table needs re-clustering or not). 
That would not make updation/insertion too time taking and we would still be benefitting from clustering for MATCH.

**Comment by rafsun42** [comment]
@Zainab-Saad Wouldn't that make first MATCH query slower than querying without clustering at all?

**Comment by WendelLana** [comment]
### Multi-label queries supported in openCypher specification and Neo4j
**Create a node with multiple labels**
Query 1
```
CREATE (n:Actor:Director)
```
Query 2 - using SET
```
CREATE (n)
SET n:Actor:Director
```
**Find all nodes which are defined with both labels of `Actor` and `Director`**
Query 1 - filtering using WHERE
```
MATCH (n) 
WHERE n:Actor AND n:Director 
RETURN n;
```
Query 2 - filtering in the MATCH
```
MATCH (n:Actor:Director)
RETURN n;
```
Query 3 - using label expression
```
MATCH (n:Actor&Director)
RETURN n;
```
Query 4
```
MATCH (n:Actor), (n:Director)
RETURN n;
```
**Find all nodes which have either label of `Actor` or `Director`**
Query 1 - using `labels()` function
```
MATCH (n)
WHERE labels(n) IN [['Actor'],['Director'], ['Actor', 'Director']]
RETURN n
```
Query 2 - using WHERE
```
MATCH (n)
WHERE n:Actor OR n:Director
RETURN n
```
Query 3 - using UNION
```
MATCH (n:Actor)
RETURN n 

UNION

MATCH (n:Director) 
RETURN n
```
Query 4 - using COLLECT
```
OPTIONAL MATCH (n1:Actor)
WITH COLLECT(distinct n1) AS c1

OPTIONAL MATCH (n2:Director) 
WITH COLLECT(distinct n2) + c1 AS c2

UNWIND c2 AS nodes
RETURN nodes
```
Query 5 - using label expression
```
MATCH (n:Actor|Director)
RETURN n
```
**Remove labels `Actor` and `Director`**
```
MATCH (n)
REMOVE n:Actor:Director
```

**Comment by rafsun42** [comment]
@Zainab-Saad Could you also give us a sample query on how would you create the declarative partition?

**Comment by Zainab-Saad** [comment]
Create edge table as a RANGE partitioned table using for instance start label id 
```
CREATE TABLE graph_name._ag_label_egde (
 id int64,
 start_id int64,
 end_id int64,
 properties agtype,
 start_label_id int32,
 end_label_id int32,
 label_id int32
) PARTITION BY RANGE (start_label_id)
```
Then the partitions (as more labels are added) can be created as
```
CREATE TABLE _ag_label_edge_1 PARTITION OF graph_name._ag_label_edge
    FOR VALUES FROM (1) TO (5);
CREATE TABLE _ag_label_edge_2 PARTITION OF graph_name._ag_label_edge
    FOR VALUES FROM (5) TO (10);
```
[reference](https://www.postgresql.org/docs/current/ddl-partitioning.html)

**Comment by rafsun42** [comment]
@WendelLana About usage of multiple label, could you specify if a query is supported in only openCypher, only neo4j, or both?

**Comment by WendelLana** [comment]
@rafsun42 Based on the queries that I provided, openCypher supports all of them except for the label expression using `&`.  Both Neo4j and openCypher don't allow multiple labels in edges, but we can use them in MATCH clauses and expressions, for example:
```
MATCH ()-[:ACTED_IN|:DIRECTED]->(:Movie)
```
So, openCypher supports label expressions using the PIPES symbol, denoted as `|`. However, Neo4j supports label expression with an extended set of logical operators and also relationship type expressions. Some examples:

**Nested expression**
Find all nodes that either have both labels `A` and `B`, or have label `C`
```
MATCH (n:(A&B)|C)-[]->(m)
```
**NOT expression**
Find all nodes that do not contain the `A` label
```
MATCH (n:!A)
```
**Wildcard expression**
Find all the nodes that contain at least one label
```
MATCH (n:%)
```

**References**:
[Cypher Query Language Reference](https://github.com/opencypher/openCypher/blob/master/docs/openCypher9.pdf) 
[Neo4j Label Expressions](https://neo4j.com/docs/cypher-manual/current/syntax/expressions/#label-expressions)
[Neo4j Relationship Type Expressions](https://neo4j.com/docs/cypher-manual/current/syntax/expressions/#relationship-type-expressions)

**Comment by rafsun42** [comment]
@WendelLana It would be helpful if you mark each queries (i.e. Neo4j Only, OpenCypher Only, Both) in your first comment on this topic.

**Comment by Zainab-Saad** [comment]
As Wendel said, Neo4j supports logical operators (`|, &, !, %`) in addition to `colon (:)` operator (which is equivalent to `AND`). But colon and label expressions can not be mixed in the same clause.  For example: 
`MATCH (n: A|B:C) RETURN n`
```
Neo.ClientError.Statement.SyntaxError
Mixing label expression symbols ('|', '&', '!', and '%') with colon (':') is not allowed. Please only use one set of symbols. This expression could be expressed as :A|(B&C). (line 1, column 13 (offset: 12))
"MATCH (n: A|B:C) RETURN n"
             ^
```
Another example of erroneous query is:
`MATCH (n: A:B), (m: (A&B)|C) RETURN n, m`
```
Neo.ClientError.Statement.SyntaxError
Mixing label expression symbols ('|', '&', '!', and '%') with colon (':') is not allowed. Please only use one set of symbols. This expression could be expressed as :A&B. (line 1, column 12 (offset: 11))
"MATCH (n: A:B), (m: (A&B)|C) RETURN n, m"
```
But using these different syntaxes in seperate queries is allowed
`MATCH (n: A:B:C) MATCH (m: (A&B)|C) RETURN n, m`
[Restrictions on label expression syntax](https://neo4j.com/docs/cypher-manual/current/syntax/expressions/#syntax-restrictions-label)

**Comment by WendelLana** [comment]
## Benchmarking of label IDs in an array with identical data
In this benchmarking, I conducted tests on three tables, each containing identical data, with the only difference being the data type, changed from `int4` (integer) to `int4[]` (integer array).
### Setup
**Creation of tables**
```sql
CREATE TABLE labels_test1.ag_label_vertex
(
   id bigint NOT NULL,
   label_id INT4,
   PRIMARY KEY (id)
);

CREATE TABLE labels_test1.ag_label_vertex_array
(
   id bigint NOT NULL,
   label_id INT4[],
   PRIMARY KEY (id)
);
```
**Populating the tables**
- The label_id array only contains 1 integer.
- Created 1000000 (one million) vertices (rows) for each table, same data in both tables.
- Label IDs range from 1 to 10.

**Table 1 sample - ag_label_vertex**
```
SELECT * FROM labels_test1.ag_label_vertex LIMIT 10;
 id | label_id
----+----------
  1 |        9
  2 |        5
  3 |       10
  4 |        2
  5 |        4
  6 |        5
  7 |        3
  8 |        4
  9 |        4
 10 |        5
(10 rows)
```
**Table 2 sample - ag_label_vertex_array**
```
SELECT * FROM labels_test1.ag_label_vertex_array LIMIT 10;
 id | label_id
----+----------
  1 | {9}
  2 | {5}
  3 | {10}
  4 | {2}
  5 | {4}
  6 | {5}
  7 | {3}
  8 | {4}
  9 | {4}
 10 | {5}
(10 rows)
```
### Queries that are tested
**Query 1 - MATCH (:1)**
```sql
EXPLAIN (ANALYZE, VERBOSE, BUFFERS)
SELECT * FROM labels_test1.ag_label_vertex
    WHERE label_id = 1;

EXPLAIN (ANALYZE, VERBOSE, BUFFERS)
SELECT * FROM labels_test1.ag_label_vertex_array
    WHERE '{1}'::int4[] <@ label_id;
```
**Query 2 - MATCH (:1|2)**
```sql
EXPLAIN (ANALYZE, VERBOSE, BUFFERS)
SELECT * FROM labels_test1.ag_label_vertex
    WHERE label_id = 1 OR label_id = 2;

EXPLAIN (ANALYZE, VERBOSE, BUFFERS)
SELECT * FROM labels_test1.ag_label_vertex_array
    WHERE '{1}'::int4[] <@ label_id OR '{2}'::int4[] <@ label_id;
```
### Indices
I've created a table to test the queries with GIN index.
```sql
CREATE INDEX idx_label_array ON labels_test1.ag_label_vertex_array_gin USING gin(label_id);
```
### Performance tests 
Execution time of each query for the table ag_label_vertex (Integer Column) and ag_label_vertex_array (Array Column), also a test with GIN index.
| | Integer Column | Array Column | Array with Index |
|---|---|---|---|
| Query 1 |  180.381 ms | 305.785 ms | 245.435 ms |
| Query 2 |  189.958 ms | 312.840 ms | 230.046 ms |

**Comment by rafsun42** [comment]
@WendelLana Thanks!

**Comment by WendelLana** [comment]
## Benchmarking of label IDs in an array with multi-labels
In this benchmarking, I conducted tests to assess the performance of a vertex table with an integer column representing a single label for vertices, comparing it against a vertex table with an integer array representing the multi-label feature. Additionally, I utilized an index for the integer array to enhance performance.
### Setup
**Creation of tables**
```sql
CREATE TABLE labels_test.ag_label_vertex
(
   id bigint NOT NULL,
   label_id INT4,
   PRIMARY KEY (id)
);

CREATE TABLE labels_test.ag_label_vertex_array
(
   id bigint NOT NULL,
   label_ids INT4[],
   PRIMARY KEY (id)
);
```
**Populating the tables**
- Created 1000000 (one million) vertices (rows) for each table.
- The label_id array can contain 0 to 5 label IDs.
- Label IDs range from 1 to 10.

**Table 1 sample - ag_label_vertex**
```
SELECT * FROM labels_test.ag_label_vertex LIMIT 10;
 id | label_id
----+----------
  1 |       10
  2 |        1
  3 |       10
  4 |        2
  5 |        1
  6 |       10
  7 |        3
  8 |        4
  9 |        2
 10 |        5
(10 rows)
```
**Table 2 sample - ag_label_vertex_array**
```
SELECT * FROM labels_test.ag_label_vertex_array LIMIT 10;
 id |  label_ids
----+--------------
  1 | {2,9,4,10,2}
  2 | {2,3}
  3 | {9,4,7}
  4 | {2,10,5}
  5 | {8,10,6}
  6 | {6}
  7 | {9}
  8 | {1,7}
  9 | {}
 10 | {}
(10 rows)
```
### Queries that are tested
**Query 1 - MATCH (:1)**
```sql
EXPLAIN (ANALYZE, VERBOSE, BUFFERS)
SELECT * FROM labels_test.ag_label_vertex
    WHERE label_id = 1;

EXPLAIN (ANALYZE, VERBOSE, BUFFERS)
SELECT * FROM labels_test.ag_label_vertex_array
    WHERE '{1}'::int4[] <@ label_ids;
```
**Query 2 - MATCH (:1|2)**
```sql
EXPLAIN (ANALYZE, VERBOSE, BUFFERS)
SELECT * FROM labels_test.ag_label_vertex
    WHERE label_id = 1 OR label_id = 2;

EXPLAIN (ANALYZE, VERBOSE, BUFFERS)
SELECT * FROM labels_test.ag_label_vertex_array
    WHERE '{1}'::int4[] <@ label_ids OR '{2}'::int4[] <@ label_ids;
```
**Query 3 - MATCH (:!1)**
```sql
EXPLAIN (ANALYZE, VERBOSE, BUFFERS)
SELECT * FROM labels_test.ag_label_vertex
    WHERE label_id != 1;

EXPLAIN (ANALYZE, VERBOSE, BUFFERS)
SELECT * FROM labels_test.ag_label_vertex_array
    WHERE NOT '{1}'::int4[] <@ label_ids;
```
`From here on, there will only be queries for the multi-label array table.`
**Query 4 - MATCH (:1:2)**
```sql
EXPLAIN (ANALYZE, VERBOSE, BUFFERS)
SELECT * FROM labels_test.ag_label_vertex_array
    WHERE '{1,2}'::int4[] <@ label_ids;
```
**Query 5 - MATCH (:1&2)**
```sql
EXPLAIN (ANALYZE, VERBOSE, BUFFERS)
SELECT * FROM labels_test.ag_label_vertex_array
    WHERE label_ids = '{1,2}'::int4[];
```
### Indices
I've created a table to test the queries with GIN index.
```sql
CREATE INDEX idx_label_array ON labels_test.ag_label_vertex_array_gin USING gin(label_ids);
```
### Performance tests 
Execution time of each query for the table ag_label_vertex (Integer Column) and ag_label_vertex_array (Array Column), also a test with GIN index. The first table shows the best and worst execution times obtained from executing the queries, while the second table displays the average execution time for each query.

<table>
    <thead>
        <tr>
            <th></th>
            <th>Integer Column</th>
            <th>Array Column</th>
            <th>Array with Index</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td rowspan=2>Query 1</td>
            <td> 85.516 ms </td>
            <td> 207.132 ms </td>
            <td> 61.038 ms </td>
        </tr>
        <tr>
            <td> 235.642 ms </td>
            <td> 385.092 ms </td>
            <td> 211.111 ms </td>
        </tr>
        <tr>
        <td rowspan=2>Query 2</td>
            <td> 95.306 ms </td>
            <td> 299.130 ms </td>
            <td> 97.431 ms </td>
        </tr>
        <tr>
            <td> 216.760 ms </td>
            <td> 417.860 ms </td>
            <td> 270.313 ms </td>
        </tr>
        <tr>
        <td rowspan=2>Query 3</td>
            <td> 247.242 ms </td>
            <td> 246.839 ms </td>
            <td> 247.569 ms </td>
        </tr>
        <tr>
            <td> 280.002 ms </td>
            <td> 369.022 ms </td>
            <td> 407.235 ms </td>
        </tr>
        <tr>
        <td rowspan=2>Query 4</td>
            <td> ------------- </td>
            <td> 119.549 ms </td>
            <td> 40.732 ms </td>
        </tr>
        <tr>
            <td> ------------- </td>
            <td> 277.031 ms </td>
            <td> 225.804 ms </td>
        </tr>
        <tr>
        <td rowspan=2>Query 5</td>
            <td> ------------- </td>
            <td> 84.104 ms </td>
            <td> 43.549 ms </td>
        </tr>
        <tr>
            <td> ------------- </td>
            <td> 312.020 ms </td>
            <td> 255.996 ms </td>
        </tr>
    </tbody>
</table>

**Average Execution Time**

| | Integer Column | Array Column | Array with Index |
|---|---|---|---|
| Query 1 | 150.1548 ms | 247.0602 ms | 94.0968 ms |
| Query 2 | 123.0912 ms | 324.2656 ms | 134.56 ms |
| Query 3 | 256.2982 ms | 273.6316 ms | 292.5652 ms |
| Query 4 |  ------------- | 157.3674 ms | 79.4852 ms |
| Query 5 |  ------------- | 135.9024 ms | 90.8026 ms |

**Comment by CapnSpek** [comment]
Same results as Wendel.

**My setup**
`test_array` having `vertex_id` and `labels_id` array.
`test_int` having `vertex_id` and `label_id` int type.

The 2 tables were populated by generating an sql file through a C program and running the sql file.

[Here](https://pastebin.com/9fUWSejP) is the code for both programs.


**Tests**

1. Listing vertices by a single label_id
2. Listing vertices by using OR on multiple label ids.
3. Listing vertices by using NOT label_id.


Average vertices by a single label_id result:

One label query execution time - 82.2 ms
`OR` label query execution time - 103.8 ms
`NOT` label query execution time - 123.8 ms

Average vertices by multiple label_ids result:

One label query execution time - 186.19
`OR` label query execution time - 254.25 ms
`NOT` label query execution time - 200.78 ms

It appears we are looking at a 2x+ increase of execution time unless we can optimize it further.
