### ISSUE TITLE
Study the make_directed_edge_join_conditions function

### ISSUE THREAD

**Issue by rafsun42** [apache/age#1007]
Find the function `make_directed_edge_join_conditions` in `cypher_clause.c` file. 

Notice the last two IF-block.
```c
...
    if (prev_node_filter != NULL && !IS_DEFAULT_LABEL_VERTEX(prev_node_filter))
    {
        ...
    }

    if (next_node_filter != NULL && !IS_DEFAULT_LABEL_VERTEX(next_node_filter))
    {
        ...
    }
...
```

Research the following question:
1. What cypher queries will enter the last two IF-block?
2. Are there any regression tests exist that test such queries? If not, write your own.

**Comment by amakodikara** [comment]
Hi @eyab , 
Kindly look into this matter. Thank you!

**Comment by Zainab-Saad** [comment]
I have debugged this function with the regression tests for MATCH clause, and found that the following regression test enters second IF conditional:
```
SELECT * FROM cypher('cypher_match', $$
        MATCH (u:duplicate)-[]-(:other_v)
        RETURN DISTINCT u
$$) AS (i agtype);
```

But one thing I have noticed is that there are many tests possible [here](https://github.com/apache/age/blob/master/regress/sql/cypher_match.sql) where the code flow could enter either first or second or both IF condtionals but such tests do not exist already. If such tests need to be added, I can go ahead and add those regression tests.

**Comment by rafsun42** [comment]
@Zainab-Saad 

Good job. It would be great if you could add tests for cases that enter first, second and both blocks.

**Comment by Zainab-Saad** [comment]
Sure, I will do that
