### ISSUE TITLE
Restore ag_catalog schema - empty table

### ISSUE THREAD

**Issue by patrond** [apache/age#1032]
Hello,
I'm trying to restore a database with the apache age extension installed. When I restore the ag_catalog schema it contains the ag_graph and ag_label tables but they are empty. What is the correct procedure for restoring a database of this type? 
Thank you

**Comment by Munmud** [comment]
ag_label tables should not be empty.

'When you create a graph using the command as follow
```sql
SELECT create_graph('graph_name') ;
```
The default behaviour is that it creats a graph where default vertex is `_ag_label_vertex`and default edge is `_ag_label_edge`
You can check them by the command 
```sql
SELECT table_catalog, table_schema, table_name, table_type 
FROM information_schema.tables
WHERE table_schema = 'graph_name' 
ORDER BY table_name ASC;
```

You can check the label by following commad
```sql
select * from ag_catalog.ag_label;
```

Can you please share more details from where your are trying to restore database ?

**Comment by patrond** [comment]
I have a working source database with a graph:
`SELECT table_catalog, table_schema, table_name, table_type 
FROM information_schema.tables
WHERE table_schema = 'iam' 
ORDER BY table_name ASC;
--33 rows`

the second query:
`select * from ag_catalog.ag_label;
--33 rows`

I need to dump the whole database and create a second one from this dump.
I use the command:
`pg_dump -Fc -Upostgres <dbname> -f /<path>/<dump_filename>`

and:
`pg_restore -Upostgres -C -dpostgres /<path>/<dump_filename>`

I run the queries again, in the new (destination) database:
`SELECT table_catalog, table_schema, table_name, table_type 
FROM information_schema.tables
WHERE table_schema = 'iam' 
ORDER BY table_name ASC;
--33 rows`

and the second one:
the second query:
`select * from ag_catalog.ag_label;
--0 rows`

tables in the ag_catalog schema are empty.
thanks

**Comment by titoausten** [comment]
Before **restoring** the database, I think you should create a destination database using `createdb` and provide the path when restoring like so:
```
pg_restore -U postgres -d <destination_dbname> /<path>/<dump_filename>

```

You can check the contents of the dump file if accurate as this might be an issue using `pg_restore -l /<path>/<dump_filename>`.

**Comment by patrond** [comment]
I also tried with an already existing database. The problem persists.
I noticed that if I run a pg_dump in plain text, in the file produced I don't find the lines for creating and populating ag_graph and ag_label tables. Any suggestions?

`pg_dump -Fp -Upostgres <dbname> -f <file_path>`

**Comment by titoausten** [comment]
Is AGE installed in the destination database prior to dumping and restoring?

**Comment by M4rcxs** [comment]
it depends of the way you have dumped the file out. You can run `pg_restore` as well.

`pg_restore -U username -d dbname -1 filename.dump`

check the docs : [pg_restore docs](https://www.postgresql.org/docs/current/app-pgrestore.html)

**Comment by humzakt** [comment]
Hi @patrond,

There are a couple of steps you can follow when restoring a database with Apache AGE installed, specifically for the `ag_catalog` schema.

- Backup your Database:
Use the pg_dump command to backup your PostgreSQL database, this will also include AGE specific catalog data.
```
pg_dump -U [username] -d [database_name] > [backup_file.sql]
```
- Restore your Database:
Once you have your backup file, you can restore it using psql.
```
psql -U [username] -d [database_name] < [backup_file.sql]
```
Please ensure that the database [database_name] you are restoring to, has AGE extension installed. If it's not, install AGE before you restore.

**Comment by patrond** [comment]
I updated and recompiled the extension and now it works.
thanks
