### ISSUE TITLE
container must be an array or object

### ISSUE THREAD

**Issue by MuhammadTahaNaveed** [apache/age#1043]
**Describe the bug**
Errors out saying container must be an array or object.

**How are you accessing AGE (Command line, driver, etc.)?**
- terminal

**What data setup do we need to do?**
```pgsql
SELECT * FROM cypher('hello',
    $$CREATE (n)-[:KNOWS {n:'hello'}]->({n:'hello'})
$$) as (a agtype);
```

**What is the command that caused the error?**
```pgsql
SELECT * FROM cypher('hello',
    $$MATCH (x)<-[y *]-(),({n:y[0].n}) RETURN x
$$) as (a agtype);
```
```
ERROR:  container must be an array or object
```

**Expected behavior**
expected vertex x to be returned
```
{"id": 281474976710658, "label": "", "properties": {"n": "hello"}}::vertex
```

**Environment (please complete the following information):**
- latest (PG13 master)

**Additional Context**
This works

```
SELECT * FROM cypher('hello',$$
    MATCH (x)<-[y *]-()
    MATCH ({n:y[0].n})
    RETURN x
$$) as (a agtype);
                                     a                                      
----------------------------------------------------------------------------
 {"id": 281474976710658, "label": "", "properties": {"n": "hello"}}::vertex
(1 row)
```

**Comment by jrgemignani** [comment]
@MuhammadTahaNaveed Looks like I overlooked binary arrays and objects. I will look into this.

**Comment by jrgemignani** [comment]
@MuhammadTahaNaveed I have fixed it and verified the results with Neo4j. Working on the PR now.

**Comment by MuhammadTahaNaveed** [comment]
> @MuhammadTahaNaveed Looks like I overlooked binary arrays and objects. I will look into this.
> 
> Correction: It is because the VLE passes a special vpc container (vpc = VLE Path Container) around for its results. In this case, the container is getting passed instead of the actualized contents of that container. I will see about putting the decode into agtype_access_operator. However, this may not be the appropriate place for it.

@jrgemignani I think the reason you mentioned may also be valid for #1044.

**Comment by jrgemignani** [comment]
See PR #1046
