### ISSUE TITLE
Array functions not recognizing VPC

### ISSUE THREAD

**Issue by MuhammadTahaNaveed** [apache/age#1044]
**Describe the bug**
I encountered an error when trying to get size of vle edge array in where clause which should have executed without error.

**How are you accessing AGE (Command line, driver, etc.)?**
- terminal

**What data setup do we need to do?**
```pgsql
SELECT * FROM cypher('graph',$$
    CREATE (n)-[:KNOWS {n:'hello'}]->({n:'hello'})
$$) as (a agtype);
```

**What is the command that caused the error?**
```pgsql
SELECT * FROM cypher('graph', $$
    MATCH (m)-[v *]->(b) 
    WHERE size(v) >1
    RETURN b
$$) AS (a agtype);
```
```
ERROR:  size() unsupported argument
```

**Expected behavior**
Should have returned
```
 {"id": 281474976710658, "label": "", "properties": {"n": "hello"}}::vertex
```

**Environment (please complete the following information):**
- latest (PG13 master)

**Additional context**
same error exists in all array functions i.e. they dont recognize VPC.

**Comment by titoausten** [comment]
The condition beside the `WHERE` clause is `> 1`, this will return an error as the **size** is not greater than 1.
