### ISSUE TITLE
Built-In support for undirected graphs

### ISSUE THREAD

**Issue by Allison-E** [apache/age#1069]
**Is your feature request related to a problem? Please describe.**

Undirected graphs are not built into AGE. In Neo4j, you could create a new undirected graph using:
```sql
CREATE (x)-[:Is_friends_with]-(y)
```
Trying that in AGE throws an error.

```sql
ERROR:  only directed relationships are allowed in CREATE
```
To get around this, I have to manually create two opposite-directed edges.
```sql
CREATE (x)-[:Is_friends_with]->(y)-[:Is_friends_with]->x
```

**Describe the solution you'd like**
It'll be convenient to be able to create an undirected graph using the cypher query `CREATE (x)-[Is_friends_with]-(y)`, which will also be represented using a single line without arrowheads in AGE Viewer.

**Describe alternatives you've considered**
NIL

**Additional context**
Manually creating an undirected graph using directed edges currently looks like this in AGE Viewer.
![Current undirected graph in AGE](https://github.com/apache/age/assets/39530416/8001a289-144c-4b96-9c6b-003b62d9e38e)

**Comment by solomspd** [comment]
I'm uncertain about the underlying architecture of AGE but I expect that considering how heavily inspired AGE is by cypher and neo4j, then undirected edges go against its philosophy. [Here](https://graphaware.com/blog/neo4j/neo4j-bidirectional-relationships.html) is this great blog on how undirected edges can be thought of in Cypher. For semantically symmetric relationships, you typically would just pick an arbitrary direction for the relationship and query it without direction.

**Comment by Allison-E** [comment]
Thanks for your response @solomspd. I understand it now.

**Comment by M4rcxs** [comment]
I think it's not possible in the current version of AGE, but probably in the future it can be implemented (or not).

**Comment by titoausten** [comment]
AGE supports Neo4j's Cypher and follows most if not all of its standards. Hence, relationships must have a "Direction" in AGE.
