### ISSUE TITLE
Contributing to the documentation of age

### ISSUE THREAD

**Issue by TalhaMunir-JD** [apache/age#1070]
Hii!! I have been reading the documentation of age [here](https://age.apache.org/age-manual/master/intro/overview.html) and wanted to know how can we contribute to the documentation part of age. 

Anything would mean a lot. 
Thank you!!

**Comment by RahimullahShaheen** [comment]
There is [age-website](https://github.com/apache/age-website) repository in which there is a file by the name of docs. If you want to make any contribution to the documentation, create a pull request of the repository.

**Comment by M4rcxs** [comment]
You can just go to the [Docs](https://github.com/apache/age-website) of AGE. Create a **fork** of this repository and modify/create the part that you want to, so after it you just need to open a PR!

**Comment by Nimra-1234** [comment]
Yes, you can contribute to the Documentation by creating Pull Request to its official repo. 
That is [https://github.com/apache/age-website](Age_Site_Repo).

The simplest way of doing this is:

1. Create a fork of this repo.
2.  Go to the Docs folder and add your changes
3. Then, do PR.
