### ISSUE TITLE
[Label Redesign] Update get_label_name

### ISSUE THREAD

**Issue by rafsun42** [apache/age#1093]

**Comment by panosfol** [comment]
Assign me please

**Comment by rafsun42** [comment]
@panosfol If you think junction table is done, you may start working on this on a different branch.

**Comment by panosfol** [comment]
@rafsun42 On it!

**Comment by CapnSpek** [comment]
`get_label_name` has been updated to accept 3 parameters instead of 2 (graph name, element id, element label id) after the edge object has been updated to contain `start label id` and `end label id`.

This change is implement in https://github.com/rafsun42/age/pull/29 PR 29.
