### ISSUE TITLE
Python Driver : Antlr4ResultHandler Initialization Optimization

### ISSUE THREAD

**Issue by Munmud** [apache/age#1106]
**Issue Summary:**
Currently, in our python driver codebase, the `Antlr4ResultHandler` is being initialized afresh for every query made. This leads to unnecessary overhead as the handler's initialization process is repeated needlessly. To improve the overall performance and reduce execution time, we should explore the possibility of initializing the `Antlr4ResultHandler` only once and then reusing it for subsequent queries.

**Issue Details:**
The `Antlr4ResultHandler` plays a crucial role in processing and handling query results using the ANTLR (ANother Tool for Language Recognition) library. However, the current implementation initializes a new handler instance each time a query is executed. This approach proves to be suboptimal, especially in scenarios where multiple queries are processed in succession or in a short timeframe.

**Expected Behavior:**
The ideal behavior we aim to achieve is to initialize the Antlr4ResultHandler only once during the application's lifecycle or upon the first query execution. Subsequently, we can reuse this pre-initialized handler for all subsequent queries, avoiding redundant instantiation.

**Potential Benefits**
- `Reduced Overhead`: Avoiding repeated initialization of the handler will significantly reduce overhead and improve the efficiency of query processing.
- `Improved Performance`: Reusing the pre-initialized handler will result in faster response times for subsequent queries, providing a smoother user experience.
- `Resource Efficiency`: Conserving resources by reusing the handler will lead to better resource utilization and overall system stability.
- `Code Readability and Maintainability`: Implementing a shared, initialized handler will result in cleaner and more maintainable code, as it reduces redundant code blocks and promotes modularization.

**Comment by Munmud** [comment]
Please assign me to the task

**Comment by M4rcxs** [comment]
the singleton pattern sounds a good way to solve this. 

```c
resultHandler = None
```
