### ISSUE TITLE
List functions In AGE

### ISSUE THREAD

**Issue by M4rcxs** [apache/age#1109]
**Is your feature request related to a problem? Please describe.**
Could be good add more list functions in AGE?

**Describe the solution you'd like**
there are a lot of functions in AGE that doesn't support list as a entry function like toUpper(), toLower() and others. 
**Describe alternatives you've considered**
does have a good way to handle with this without create a new entire function to handle with lists?
**Additional context**
none.

**Comment by cmucheru** [comment]
Have you considered using a library for lists to enable working with _toUpper()_  and _toLower()_ functions? @M4rcxs

**Comment by danielwambo** [comment]
That is already in place.
`SELECT toLower('WORD');`
and
`SELECT toUpper('word');`

> Have you considered using a library for lists to enable working with _toUpper()_ and _toLower()_ functions? @M4rcxs

**Comment by jrgemignani** [comment]
@M4rcxs Do you mean as a parameter of type list?

For example:

```
lst = ['this', 'that', 1, 2, {name: "Jim"}] 

toUpper(lst) or toLower(lst)
```

If so, it doesn't really make sense to.
