### ISSUE TITLE
Proposal: Create a Comprehensive Developer's Manual

### ISSUE THREAD

**Issue by markgomer** [apache/age#1120]
**Is your feature request related to a problem? Please describe.**

The onboarding process for new contributors to the Apache AGE project is challenging due to a lack of comprehensive documentation about the codebase, standards, and procedures. This makes it difficult for new developers to understand how they can best contribute to the project. Furthermore, the absence of a standard guide may lead to inconsistencies in code and practices across the project.

**Describe the solution you'd like**

I propose that we create a comprehensive Developer's Manual for the Apache AGE project. This document should provide:

1. An overview of the project structure and codebase to help newcomers understand the system quickly.
2. Our coding and documentation standards, best practices, and conventions to ensure consistency across the project.
3. Step-by-step procedures for common tasks like submitting pull requests, reporting bugs, or proposing new features.
4. Information about the project's vision, goals, and roadmap to ensure that all contributors are aligned in their efforts.

**Describe alternatives you've considered**

An alternative solution could be creating separate documents for each of the points mentioned above. However, having all the information in one comprehensive Developer's Manual would provide a central source of truth and would be more efficient for both new and existing contributors.

**Additional context**

Creating a comprehensive Developer's Manual would not only ease the onboarding process for new contributors but also enhance collaboration among team members. It would provide a shared understanding of the project and its goals, making the development process smoother and more efficient. As the project grows, this manual will be an invaluable resource to ensure consistency and quality in our collaborative efforts.

**Comment by carlasanches** [comment]
I support this proposal and would like to contribute if it becomes a project. Another suggestion I've seen in other open-source projects is to create a "good first issue" category. This helps new contributors find issues easier to contribute to when first introduced to the project and still add value.

**Comment by titoausten** [comment]
This will help alot.
Unfortunately, I made some PRs that wasn't considered because of lack of such info. If there are clear details about contribution, It's going to be a great foundation for new contributors.

**Comment by M4rcxs** [comment]
It would be really helpful if this proposal goes ahead! If there are other interns to guide the newest ones, using techniques like pair programming and explaining how to contribute, that would also be good!

**Comment by MatheusFarias03** [comment]
I think that, for now, we can add to the documentation some of the functions that are missing. But it would really help to have a developer's manual. For that, we might need to do some reverse engineering, it would probably be best if someone with more knowledge on AGE could guide us through on which files to look for and in which it would be best to do that, so we can see how exactly things work.
