### ISSUE TITLE
Connecting age with spark or hadoop

### ISSUE THREAD

**Issue by talhahahae** [apache/age#1122]
I was studying the documentation of Apache Spark and I was trying to figure out if there was any way I could connect Age to Spark. But I couldn't find any information on that. Is it possible to connect spark to age?
Any article or piece of information would be very beneficial.

Thank you in advance!!

**Comment by Amr-Shams** [comment]
I believe there is a project working on this they are using Kafka. but so far, no direct connection.

**Comment by titoausten** [comment]
There is no way to connect them at the moment. However, if you really are interested in working with both of them at the moment, saving and exporting data in either CSV or JSON would be a way to indirectly work with them (this depends on the data you're working with).

**Comment by pawankukreja01** [comment]
It is not possible so far to connect Apache AGE with Apache Spark or Hadoop, but you can use PostgreSQL JDBC drivers to integrate with Hadoop. 
You can further Read this [documentation](https://www.integrate.io/blog/integrating-relational-databases-with-apache-hadoop/) for better understanding.
