### ISSUE TITLE
AGE&OrioleDB-Project Planning and Requirements Gathering

### ISSUE THREAD

**Issue by eyab** [apache/age#1126]

**Comment by farooquememon385** [comment]
OrioleDB is a new storage engine for PostgreSQL, bringing a modern approach to database capacity, capabilities and performance to the world's most-loved database platform.

OrioleDB consists of an extension, building on the innovative table access method framework and other standard Postgres extension interfaces. By extending and enhancing the current table access methods.

Apache AGE is also a Graph extension to PostgreSQL.

By combining both these extensions we can achieve graph database functionality while avoiding legacy CPU bottlenecks on modern servers.

**Comment by namsi-lia** [comment]
Integration of a plug-gable storage engine such as Oriole Db to Apache AGE will be beneficial in that 
1.Oriole DB as our desired storage engine  will allow in-place update and enable the reuse of space to help control database bloat
2.Secondly Oriole as the desired storage engine will allow developers be able to choose storage methods that is optimized for specific needs .One can configure the storage engine for high transactional loads while  others for analytics workloads and still others for archiving
