### ISSUE TITLE
AGE&Citus Integrationn-Project Planning and Requirements Gathering

### ISSUE THREAD

**Issue by eyab** [apache/age#1127]

**Comment by farooquememon385** [comment]
Since,  Citus is an extension to PostgreSQL that is used for horizontal scaling of PostgreSQL across multiple nodes. we can use it with AGE to improve the performance and scalability of graph queries by parallelizing the execution across the cluster.

**Comment by M4rcxs** [comment]
### Citus
In relation to its operational efficiency, **Citus** distributes tables into shards across a network of PostgreSQL nodes. This means that data is broken down into smaller pieces and stored on numerous nodes, enabling tasks to be carried out concurrently. This approach optimally harnesses the processing power, memory, storage, and input/output capabilities of the CPU. 
### Additionally
The system's distributed query engine effectively directs transactions throughout the cluster, simultaneously distributing analytical queries and batch processes across all available cores. Additionally, you retain the ability to utilize the familiar PostgreSQL features and tools.

**Comment by MuhammadZeeshan03** [comment]
## Citus Architecture

Talking about its architecture, in a citus cluster all servers run PostgreSQL with the citus extension plus any number of other extension installed. Citus uses the PostgreSQL extension APIs to change the behaviour of database in two ways.

- It replicates database objects to all servers such as custom types and functions.
- It adds two new table types that can be used to take advatange of additional servers.

**Comment by farooquememon385** [comment]
AGE and citus both are extensions to PostgreSQL, we can try to use it by installing both extensions on Postgres cluster

**Comment by GPF199541** [comment]
How to choose a shard ID on citus is a problem
