### ISSUE TITLE
Function showing that it does not exist, but it does exist.

### ISSUE THREAD

**Issue by MatheusFarias03** [apache/age#1139]
Hi! I've just written a function for AGE, compiled and installed the extension, dropped it and created it again. But when I call the function, it says that it does not exist. Am I doing something wrong? What could be a solution for this?

I've declared it as the following in the `age--1.3.0.sql` file:
```sql
CREATE FUNCTION ag_catalog.age_adjacency_matrix(graph_name name)
RETURNS void
LANGUAGE c
STABLE
PARALLEL SAFE;
AS 'MODULE_PATHNAME';
```

and defined as the following in the `graph_commands.c` file:
```c
PG_FUNCTION_INFO_V1(age_adjacency_matrix);
/*
* Function for returning the graph's adjacency matrix. This adjacency matrix
* stores the number of edges between two nodes. The complexity to check if an
* edge exists within an adjacency matrix is O(1), while the space complexity
* is O(v^2) with v = number of vertices.
*/
Datum age_adjacency_matrix(PG_FUNCTION_ARGS)
{
        // Code goes here...
        PG_RETURN_VOID();
}
```

Example of query:
```sql
SELECT ag_catalog.age_adjacency_matrix();
ERROR:  function ag_catalog.age_adjacency_matrix() does not exist
LINE 1: SELECT ag_catalog.age_adjacency_matrix();
               ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.

```

**Comment by jrgemignani** [comment]
@MatheusFarias03 You didn't specify a parameter.

**Comment by MatheusFarias03** [comment]
And I was also running PG11 whilst modifying AGE for PG15... lol. But thanks for the response @jrgemignani. Btw, do you think a function that returns the graph's adjacency matrix to be a good idea?

**Comment by jrgemignani** [comment]
@MatheusFarias03 Honestly, I don't know. I only deal with the data while it is inside AGE. For the internal stuff that I have written (vle) I use hash maps for storage and retrieval. But, it could be useful for an external program.

**Comment by jrgemignani** [comment]
@MatheusFarias03 

> And I was also running PG11 whilst modifying AGE for PG15, saw that right now... lol.

It happens to the best of us.
