### ISSUE TITLE
AGE make segmentation fault for postgresql 15

### ISSUE THREAD

**Issue by I33Buckler** [apache/age#1170]
Have checked requirements for build of the AGE extension for postgresql 15. 
Unfortunately running make in the installation directory results in a segmentation fault during the build.

make: *** [/usr/lib/postgresql/15/lib/pgxs/src/makefiles/../../src/Makefile.global:1081: src/backend/age.bc] Segmentation fault

**Comment by titoausten** [comment]
Try the following process to solve this:

- Firstly, ensure you switch to the right branch for that version which should be `PG15`
- Secondly, add `PG_CONFIG` to the environment variables.
`export PG_CONFIG=/usr/local/pgsql-12/bin/pg_config`
- Finally, you can install.
`sudo make install`

**Comment by I33Buckler** [comment]
Thanks.
I am currently building off the master branch.
Will try the pg15 branch when I have the opportunity.

**Comment by I33Buckler** [comment]
pg_config is available at /usr/bin/pg_config. No problem resolving the path.
I downloaded the PG15 repository with the following 'git clone https://github.com/apache/age.git --branch PG15 --single-branch'
Unfortunately still get the segmentation fault when running make.

**Comment by jrgemignani** [comment]
It should not matter which branch you are building off of - the **master** branch is essentially a more current version of the **PG15** branch. Just make sure that your version of PostgreSQL matches the version of AGE. I build either the **master** or **PG15** against PostgreSQL 15.3

Also, a full listing of it being built would be useful. That one error by itself doesn't really say much.

Below is my build script, as an example.

```
#! /usr/bin/bash

pver=$1
port=$2
build="psql"-$pver-$port-$3

path="~jgemignani/POSTGRESQL/postgresql-$pver/$build/bin"

make PG_CONFIG=$path/pg_config clean
make PG_CONFIG=$path/pg_config
make PG_CONFIG=$path/pg_config install
make PG_CONFIG=$path/pg_config installcheck
```

**Comment by I33Buckler** [comment]
Further to the issue I cloned the main branch and executed the following in the cloned directory:
make clean
make 
make PG_CONFIG=/usr/bin/pg_config 1> ~/age_make.txt 2>> ~/age_make.txt
Attached is the resulting output.
[age_make.txt](https://github.com/apache/age/files/12427963/age_make.txt)

**Comment by jrgemignani** [comment]
@I33Buckler Thank you for the output file. Could you please tell us what OS, flavor and version, you are running this under? Additionally, what are the other options you have set up for gcc? I ask this because of the D_FORTIFY_SOURCE flag.

I was able to successfully build against 15.4 without issue,

**Comment by eyab** [comment]
@I33Buckler Could you please provide more detailed information as mentioned in our standards: https://age.apache.org/contribution/how

**Comment by jrgemignani** [comment]
@I33Buckler I would add that this `Segmentation fault` may be an issue with `clang ` and not necessarily AGE because `clang ` is what is crashing -

```
1073 COMPILE.c.bc = $(CLANG) -Wno-ignored-attributes $(BITCODE_CFLAGS) $(CPPFLAGS) -flto=thin -emit-llvm -c
1074 endif
1075
1076 ifndef COMPILE.cxx.bc
1077 COMPILE.cxx.bc = $(CLANG) -xc++ -Wno-ignored-attributes $(BITCODE_CXXFLAGS) $(CPPFLAGS) -flto=thin -emit-llvm -c
1078 endif
1079
1080 %.bc : %.c
1081         $(COMPILE.c.bc) -o $@ $<
```

```
/usr/bin/clang-14 -Wno-ignored-attributes -fno-strict-aliasing -fwrapv -Wno-unused-command-line-argument -Wno-compound-token-split-by-macro -O2  -I.//src/include -I.//src/include/parser -I. -I./ -I/usr/include/postgresql/15/server -I/usr/include/postgresql/internal  -Wdate-time -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -I/usr/include/libxml2  -flto=thin -emit-llvm -c -o src/backend/age.bc src/backend/age.c
make: *** [/usr/lib/postgresql/15/lib/pgxs/src/makefiles/../../src/Makefile.global:1081: src/backend/age.bc] Segmentation fault
```

**Comment by I33Buckler** [comment]
> @I33Buckler Could you please provide more detailed information as mentioned in our standards: https://age.apache.org/contribution/how

Thanks.
I am not a regular user of redit and discord. 
Rather old school :)
Could not find any information on the email addresses for subscription on the page.

**Comment by I33Buckler** [comment]
> @I33Buckler Thank you for the output file. Could you please tell us what OS, flavor and version, you are running this under? Additionally, what are the other options you have set up for gcc? I ask this because of the D_FORTIFY_SOURCE flag.
> 
> I was able to successfully build against 15.4 without issue,

I am using the following kernel on Debian 12.

Linux version 6.1.0-11-amd64 (debian-kernel@lists.debian.org) (gcc-12 (Debian 12.2.0-14) 12.2.0, GNU ld (GNU Binutils for Debian) 2.40) #1 SMP PREEMPT_DYNAMIC Debian 6.1.38-4 (2023-08-08)

In addition the default gcc that is included in the distro.
gcc -v reports the following

Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/12/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none:amdgcn-amdhsa
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Debian 12.2.0-14' --with-bugurl=file:///usr/share/doc/gcc-12/README.Bugs --enable-languages=c,ada,c++,go,d,fortran,objc,obj-c++,m2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-12 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --enable-libphobos-checking=release --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --enable-cet --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none=/build/gcc-12-bTRWOB/gcc-12-12.2.0/debian/tmp-nvptx/usr,amdgcn-amdhsa=/build/gcc-12-bTRWOB/gcc-12-12.2.0/debian/tmp-gcn/usr --enable-offload-defaulted --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 12.2.0 (Debian 12.2.0-14)

**Comment by I33Buckler** [comment]
Thank you for the responses.
It turns out that the problem was a result of a corrupted file in the system.
This was resolved by running debsums as follows.

apt-get install --reinstall $(dpkg -S $(debsums -c) | cut -d : -f 1 | sort -u)
