### ISSUE TITLE
Should toBoolean function convert integer to boolean?

### ISSUE THREAD

**Issue by WendelLana** [apache/age#1171]
### Description
In Neo4j the function `toBoolean()` converts a string, integer or boolean value to a boolean value. Given this, should we also incorporate the ability to convert integers to boolean within our own function?

If so, I'll take the initiative to develop this feature and also implement it into the `toBooleanList()` function.

### Example
Query
```
SELECT * FROM cypher('expr', $$
    RETURN toBoolean(1)
$$) AS (toBoolean agtype);
```
Result
```
 toboolean 
-----------
 true
```

**Comment by Nimra-1234** [comment]
The **toBoolean()** function in Neo4j already has the ability to convert integers to boolean values. For **non-zero** integer numbers, the function returns true, whereas for zero, it returns false. 
As you've demonstrated in the example, toBoolean() correctly returns true when you feed it the integer 1. Passing 0 would also produce a false result.

_Example:_
True is the result of toBoolean(1).
False is returned by toBoolean(0).

**Comment by jrgemignani** [comment]
@WendelLana If this is resolved, please close the issue :)
