### ISSUE TITLE
drop_graph('graph_name') fails to Delete Graph

### ISSUE THREAD

**Issue by markgomer** [apache/age#1178]
**Describe the bug**
`SELECT drop_graph('graph_name')` is not deleting recently created graph.

**How are you accessing AGE (Command line, driver, etc.)?**
- psql interface, command line.

**What is the necessary configuration info needed?**
- Fresh install of PostgreSQL 15 and Apache AGE master, on Debian stable-slim Docker image.

**What is the command that caused the error?**
```pgsql
psql (15.4)
Type "help" for help.

test=# CREATE EXTENSION age;
CREATE EXTENSION
test=# LOAD 'age';
SET search_path TO ag_catalog;
LOAD
SET
test=# SELECT * FROM ag_catalog.ag_graph;
 graphid | name | namespace 
---------+------+-----------
(0 rows)

```

```
test=# SELECT create_graph('agload');
NOTICE:  graph "agload" has been created
 create_graph 
--------------
 
(1 row)

test=# SELECT drop_graph('agload');
2023-08-23 10:33:23.574 -03 [28787] ERROR:  cannot drop schema agload because other objects depend on it
2023-08-23 10:33:23.574 -03 [28787] DETAIL:  table agload._ag_label_vertex depends on schema agload
        table agload._ag_label_edge depends on schema agload
2023-08-23 10:33:23.574 -03 [28787] HINT:  Use DROP ... CASCADE to drop the dependent objects too.
2023-08-23 10:33:23.574 -03 [28787] STATEMENT:  SELECT drop_graph('agload');
ERROR:  cannot drop schema agload because other objects depend on it
DETAIL:  table agload._ag_label_vertex depends on schema agload
table agload._ag_label_edge depends on schema agload
HINT:  Use DROP ... CASCADE to drop the dependent objects too.
test=# 
```

**Expected behavior**
After `SELECT drop_graph('graph_name');` the graph should be dropped along with all its vertexes and edges.

**Environment (please complete the following information):**
- AGE Version: 1.3.0

**Comment by markgomer** [comment]
I actually forgot one argument, so I should be calling `SELECT drop_graph('graph_name', true);`, which works.

So now I raise a question: in what cases would setting the `cascade` option to `false` would be useful? 

Calling the function with `false`, on any graph I tested, raised the same error. 

Should we change the function so it always considers the `cascade` argument as `true`?

**Comment by Amr-Shams** [comment]
When there are multiple graphs with foreign key relationships between them, deleting the "main" graph with the cascade option set to True could cause errors or data integrity issues in the dependent graphs.
but as you mentioned it would be better if we set it to "true" and pop up a message in case we found a relation or dependency

**Comment by Munmud** [comment]
cascade is A boolean that will will delete labels and data that depend on the graph. So, it is recommended to set the cascade option to true, otherwise everything in the graph must be manually dropped with SQL DDL commands.
See references [here](https://age.apache.org/age-manual/master/intro/graphs.html#drop-graph)
