### ISSUE TITLE
[Hybrid Query]Cannot use SQL function in Cypher query

### ISSUE THREAD

**Issue by cho2hhun** [apache/age#1234]
I've used Agens Graph and AGE many times, and I think there is a point that hope to revise like Agens Graph

In AGE, it cannot use **PostgreSQL function in Cypher query** but Agens Graph was possible to use PG function in Cypher clause

the example is like below

**[case 1. AGE ]**
```
select * from cypher ('car' $$
    match (a : vt_car) -[r : eg_eng_use2]->(b : vt_engine)
    return corr(r.fe, r.co2) as corr $$) as (corr numeric)
```
then error is occured like below

```
ERROR:  function ag_catalog.age_corr(agtype, agtype) does not exist
```

**[case 2. Agens Graph]**
```
match (a : vt_car) -[r : eg_eng_use2]->(b : vt_engine)
return corr(r.fe, r.co2) as corr
```
In the case of Agens Graph, It is possible to use PG function in Cypher clause

the thing that you need to notice is that ```corr()``` is a **PostgreSQL function**

I think the schema ```ag_catalog``` doesnt have **PG functions** but only have AGE's unique functions

So I Think it might as well to add PG function in ```ag_catalog``` So we can use PG functions in Cypher clause and It could be fluent **Hybrid Query**!!! cause many people dont know exactly about Cypher functions, It might be really good for user who is knowing for PG SQL 

**Environment (please complete the following information):**
- Version: 13

**Comment by jimenasansav** [comment]
Hi @cho2hhun! Thank you for pointing this issue out. Our team is already reproducing the issue and finding a solution.

**Comment by rafsun42** [comment]
@cho2hhun 

Have you tried using the full qualified name of the function and casting agtype to float8? 
```
select * from cypher ('car', $$
    match (a : vt_car) -[r : eg_eng_use2]->(b : vt_engine)
    return (pg_catalog.corr((r.fe)::pg_float8, (r.co2)::pg_float8)) as corr $$) as (corr agtype);

```

**Comment by rafsun42** [comment]
@cho2hhun Was it helpful?

**Comment by jrgemignani** [comment]
> the thing that you need to notice is that corr() is a PostgreSQL function

You can use PostgreSQL functions in cypher. However, you must fully qualify them, just like with user defined functions.

```
--
-- user defined function expressions - using pg functions for these tests
--
SELECT * from cypher('expr', $$
    RETURN pg_catalog.sqrt(25::pg_float8)
$$) as (result agtype);
 result
--------
 5.0
(1 row)
```

**Comment by jrgemignani** [comment]
Resolved and closed due to inactivity.

**Comment by cho2hhun** [comment]
@rafsun42 @jrgemignani Really apologize for late response and appreciate for solving problem

I completely understand that because both referred schema is different (ag_catalog & pg_catalog), it should clarify the schema that referred schema by PG to use PG functions

again really appreciate that.
