### ISSUE TITLE
Index is not used in the WHERE clause for IN operator

### ISSUE THREAD

**Issue by vladiksun** [apache/age#1235]
**Describe the bug**
Index is not used in the WHERE clause for IN operator.
Related to https://github.com/apache/age/issues/1000

**Additional context**
@rafsun42 proposed the possible solution in the thread https://github.com/apache/age/issues/1000#issuecomment-1710885960.
As agreed with @jrgemignani in https://github.com/apache/age/issues/1000#issuecomment-1723626748 this issue deserves a separate ticket.

**How are you accessing AGE (Command line, driver, etc.)?**
- JDBC

**What data setup do we need to do?**
```pgsql
LOAD 'age';
SET search_path = ag_catalog, "$user", public;

select ag_catalog.create_graph('test_graph');
select ag_catalog.create_vlabel('test_graph','profile');

-- works only for MATCH because GIN only makes sense for pattern matching what MATCH clause is
CREATE INDEX profile_gin_idx ON test_graph."profile" USING GIN (properties);

------ generate more data -------
DO
$do$
    BEGIN
        FOR i IN 1..10000 LOOP
            EXECUTE format('
                select * from ag_catalog.cypher(''test_graph'',
                $$
                    CREATE (any_vertex: profile { `id`: "%s", `pet`: "%s", `hidden`: %s })
                    RETURN any_vertex
                $$
            ) as (any_vertex ag_catalog.agtype)',
                   (SELECT uuid_in(md5(random()::text || now()::text)::cstring)),
                   (SELECT ('[0:2]={dog,cat,bird}'::text[])[floor(random()*3)]),
                   (SELECT ('[0:1]={true,false}'::text[])[floor(random()*2)])
                );
        END LOOP;
    END
$do$;

```
**What is the command that caused the error?**
```pgsql
select
    any_profile
from ag_catalog.cypher('test_graph',$$
    EXPLAIN ANALYZE
    MATCH (any_profile:`profile` { hidden: false })
    WHERE any_profile.pet IN ['dog', 'cat']
    RETURN any_profile
$$
) as (any_profile ag_catalog.agtype);
```

**Expected behavior**
Ability to create the index to use it with IN operator

**Environment (please complete the following information):**
- Version: 1.4.0

**Comment by jimenasansav** [comment]
Hi @vladiksun! Thank you for pointing out this issue. Our team is already reproducing this issue and working on a solution. In the meantime, please feel free to reach out if you have any questions or comments.

**Comment by jrgemignani** [comment]
@rafsun42

**Comment by jrgemignani** [comment]
@vladiksun When I run it against the current master I get the following -

```
                                                         QUERY PLAN
-----------------------------------------------------------------------------------------------------------------------------
 Bitmap Heap Scan on profile any_profile  (cost=20.08..52.32 rows=1 width=32) (actual time=1.832..26.179 rows=3311 loops=1)
   Recheck Cond: (properties @> '{"hidden": false}'::agtype)
   Filter: (agtype_access_operator(VARIADIC ARRAY[properties, '"pet"'::agtype]) = ANY ('{"\"dog\"","\"cat\""}'::agtype[]))
   Rows Removed by Filter: 1674
   Heap Blocks: exact=143
   ->  Bitmap Index Scan on profile_gin_idx  (cost=0.00..20.07 rows=10 width=0) (actual time=1.742..1.742 rows=4985 loops=1)
         Index Cond: (properties @> '{"hidden": false}'::agtype)
 Planning Time: 2.057 ms
 Execution Time: 26.598 ms
(9 rows)

psql-15.4-5432-pgsql=#
```

**Comment by vladiksun** [comment]
@jrgemignani the GIN index used in this plan only involves the MATCH section of the query. But WHERE section should use another index structure which we don't know beforehand. I believe @rafsun42 proposed a solution as I mentioned in the description.

**Comment by rafsun42** [comment]
@vladiksun 

@dehowef worked on a patch related to the solution I proposed. It was merged into the master. I suggest you try recompiling AGE from latest master.

Your query will produce a plan similar to @jrgemignani's above comment. For the WHERE clause, you may create an index like below:
```sql
CREATE INDEX pet_btree
ON test_graph.profile
USING btree (agtype_access_operator(VARIADIC ARRAY[properties, '"pet"'::agtype]));
```

**Comment by rafsun42** [comment]
@vladiksun 

Additionally, I would like to introduce a configration parameter I worked on. It may or may not be useful for you. It let you choose which operator to use for MATCH's property filter. If you set the parameter OFF,
```sql
SET age.enable_containment = OFF; -- default is ON
```
AGE will use `agtype_access_operator` instead of `@>` for MATCH's property filter.

It gives you the choice to use BTREE index over GIN index (for MATCH) which may be preferable sometimes.

```sql
SET age.enable_containment = off;

CREATE INDEX pet_btree
ON test_graph.profile
USING btree (agtype_access_operator(VARIADIC ARRAY[properties, '"pet"'::agtype]));

CREATE INDEX hidden_btree
ON test_graph.profile
USING btree (agtype_access_operator(VARIADIC ARRAY[properties, '"hidden"'::agtype]));

select                           
    any_profile
from ag_catalog.cypher('test_graph',$$
    EXPLAIN ANALYZE
    MATCH (any_profile:`profile` { hidden: false })
    WHERE any_profile.pet IN ['dog', 'cat']
    RETURN any_profile
$$
) as (any_profile ag_catalog.agtype);
```
```txt
                                                                                                            QUERY PLAN                                                                                                            
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 Bitmap Heap Scan on profile any_profile  (cost=14.23..18.26 rows=1 width=32) (actual time=7.281..21.149 rows=3325 loops=1)
   Recheck Cond: ((agtype_access_operator(VARIADIC ARRAY[properties, '"hidden"'::agtype]) = 'false'::agtype) AND (agtype_access_operator(VARIADIC ARRAY[properties, '"pet"'::agtype]) = ANY ('{"\"dog\"","\"cat\""}'::agtype[])))
   Heap Blocks: exact=143
   ->  BitmapAnd  (cost=14.23..14.23 rows=1 width=0) (actual time=7.124..7.126 rows=0 loops=1)
         ->  Bitmap Index Scan on hidden_btree  (cost=0.00..4.66 rows=50 width=0) (actual time=2.697..2.698 rows=4978 loops=1)
               Index Cond: (agtype_access_operator(VARIADIC ARRAY[properties, '"hidden"'::agtype]) = 'false'::agtype)
         ->  Bitmap Index Scan on pet_btree  (cost=0.00..9.32 rows=100 width=0) (actual time=4.403..4.403 rows=6615 loops=1)
               Index Cond: (agtype_access_operator(VARIADIC ARRAY[properties, '"pet"'::agtype]) = ANY ('{"\"dog\"","\"cat\""}'::agtype[]))
 Planning Time: 1.415 ms
 Execution Time: 21.735 ms
(10 rows)
```

**Comment by jrgemignani** [comment]
I do want to point out the following - 

Being able to create an index is no guarantee that PostgreSQL will actually use it. PostgreSQL makes decisions on whether to use an index or not. A good example is in the `BitmapAnd` above. Depending on how PostgreSQL weights it, it may not use the indexes within at all, or maybe just one.

I just don't want anyone assuming that the lack of an index being used means that it isn't working - as long as you are able to create that index.

Additionally, sometimes having multiple indexes can actually have worse performance than no index at all. Again, that `BitmapAnd` above is a good example. In tests from the original issue, GIN indexes actually performed worse than BTree indexes and the two combined performed worse than just running the query without, for large datasets.

**Comment by vladiksun** [comment]
@jrgemignani @rafsun42 @dehowef Thank you for looking into this.
We will try to check the btree index feature for IN operator as well as new option 
```
SET age.enable_containment = OFF; -- default is ON
```
Though I don't know if it makes sense to use btree indexes for MATCH instead of GIN indexes because MATCH can only work with object patterns (@> operator). I believe for that we should create several btree indexes for each field of an object. But in that case I don't know how the object pattern is treated under the hood.

@jrgemignani I agree that in some scenarios index traversal could be more expensive than full scan and we should always check the plan first.

**Comment by jrgemignani** [comment]
@vladiksun I do want to add that we are continuously adding to, and adjusting, these property operators.

**Comment by vladiksun** [comment]
@jrgemignani @rafsun42 @dehowef Thank you for implementing this feature.
It works.
We also checked the 
```sql
SET age.enable_containment = OFF; -- default is ON
```
Actually, this might be useful because with btree indexes the queries are  a bit faster in some scenarios.
