### ISSUE TITLE
[Query Plan]Is it possible to see the query plan for CYPHER?

### ISSUE THREAD

**Issue by cho2hhun** [apache/age#1239]
I hava a question that I want to see Query Plan for Cypher which runs in  AGE's Graph DB

But I think it is not possible see Query Plan for Cypher, only can see SQL Query Plan

In the case of Agens Graph, it was possible to query plan for Graph Query

Because of Comment processing of Cypher with Dollar-quotation(**$$** match~ return ~ **$$**), I think it is not read in PG enviroment, and cannot return Query plan for Cypher

If you folks know how to see the query plan for Cypher in AGE GDB, please let me share it!

It is important to save the cost for Query to see the Graph DB query Process

Thank you

**Comment by markgomer** [comment]
Hi @cho2hhun! 

You can put the command EXPLAIN with the cypher queries, but AGE still is PostgreSQL tables arranged as a graph, so it is essentially transforming the Cypher query into an SQL query that operates on PostgreSQL tables:

```cypher
test=# SELECT * FROM cypher('agload', 
        $$
                EXPLAIN MATCH (co:Country {name:"Albania"})-[e]-(ci:City)
                RETURN co, e, ci
        $$) 
        as (co agtype, e agtype, ci agtype);
                                                   QUERY PLAN                                                    
-----------------------------------------------------------------------------------------------------------------
 Nested Loop  (cost=0.00..118223792.34 rows=725 width=96)
   Join Filter: (((e.start_id = co.id) AND (e.end_id = ci.id)) OR ((e.end_id = co.id) AND (e.start_id = ci.id)))
   ->  Nested Loop  (cost=0.00..3656.49 rows=72485 width=614)
         ->  Seq Scan on "Country" co  (cost=0.00..3.79 rows=1 width=402)
               Filter: (properties @> agtype_build_map('name'::text, '"Albania"'::agtype))
         ->  Seq Scan on "City" ci  (cost=0.00..2927.85 rows=72485 width=212)
   ->  Materialize  (cost=0.00..1982.71 rows=72486 width=29)
         ->  Append  (cost=0.00..1620.28 rows=72486 width=29)
               ->  Seq Scan on _ag_label_edge e_1  (cost=0.00..0.00 rows=1 width=56)
               ->  Seq Scan on has_city e_2  (cost=0.00..1257.85 rows=72485 width=29)
(10 rows)
```

With EXPLAIN, you can still get insights into the query's cost and how you might optimize it, though.

To see how the Cypher is transformed into SQL, you might want to execute the query with a debugger, like GDB.

**Comment by cho2hhun** [comment]
Oh gosh, Thanks a lot. I missed it. indeed, I normaly use ```EXPLAIN``` clause in front of ```SELECT``` query...... but it was really really simple solution! appriciate it really

**Comment by jrgemignani** [comment]
@cho2hhun If this is resolved, please close it :)
