### ISSUE TITLE
AGE not getting installed on Postgresql v postgresql-11.18

### ISSUE THREAD

**Issue by KamleshKumar427** [apache/age#1247]
**Describe the bug**
AGE giving an error when installing on postgresql-11.18.

**How are you accessing AGE (Command line, driver, etc.)?**
I have PostgreSQL-11.18 installed on my system, and I am trying to install age on the top of it using command ```sudo make PG_CONFIG=/root/age_installation/pg/postgresql-11.18/bin/pg_config install``` but it return the following error:
 
![image](https://github.com/apache/age/assets/95052507/eac46e50-d29a-4e49-8730-db4cd0f63727)
**What data setup do we need to do?**
PostgreSQL-11.18

**What is the necessary configuration info needed?**
Postgresql v11.18 needed

**What is the command that caused the error?**
sudo make PG_CONFIG=/root/age_installation/pg/postgresql-11.18/bin/pg_config install

**Expected behavior**
It should install the AGE extension in Postgresql.

**Comment by Zainab-Saad** [comment]
AGE master branch is on PG-15 so you either need to change your postgres version from 11 to 15 or clone `PG11` branch rather than master if you specifically need to use AGE on PG-11.
Same goes for other versions of PG, there are specific branches for each version.

**Comment by KamleshKumar427** [comment]
PG v 15.2 also returns this error when the command: "make PG_CONFIG=/home/kamleshk/age_installation/p
ostgresql-15.2/bin/pg_config installcheck"

![image](https://github.com/apache/age/assets/95052507/d97ca748-841c-47ab-97ff-e5dc4ed44344)

**Comment by Allison-E** [comment]
Can you try running the same command without sudo? (That is, `make PG_CONFIG=/home/kanleshk/age_installation/postgresql-15.2/bin/pg_config installcheck`).

**Comment by markgomer** [comment]
@KamleshKumar427, from older to newer versions of AGE, I needed to do the command `make clean` before installing, did you try that?

**Comment by danielwambo** [comment]
You are getting the error because the packages shown there are not available for that release. Make sure to use same package version for postgres and Apache age. If it's 12,use 12 in both. 

1. Check your postgres version with the command below.
`pg_config --version`

2. After knowing the version e.g 12.Install  Apache age as below.
`git clone https://github.com/apache/age.git`

3. cd to the directory of age and checkout to the version similar to you postgres, e.g 12 as below.
`git checkout PG12`
4 Then do the install
`sudo make install`

**Comment by KamleshKumar427** [comment]
@Allison-E I have tried with sudo as well it doesn't work.
@markgomer I have tried using the clean command as well, but the error persists,
@danielwambo I will try the solution you have suggested.

**Comment by cmucheru** [comment]
@KamleshKumar427, it worked?

**Comment by KamleshKumar427** [comment]
@cmucheru Yes the solution suggested by dainelwambo worked!

**Comment by jrgemignani** [comment]
@KamleshKumar427 If this is resolved, please close the ticket :)

**Comment by cmucheru** [comment]
> @cmucheru Yes the solution suggested by dainelwambo worked!

Great, @KamleshKumar427  close this issue.

**Comment by danielwambo** [comment]
Great! @cmucheru
