### ISSUE TITLE
Confusing git tags with -rc suffix

### ISSUE THREAD

**Issue by jirutka** [apache/age#1255]
The latest release for PG15 is named [Release v1.4.0 for PG15](https://github.com/apache/age/releases/tag/PG15%2Fv1.4.0-rc0), but it’s created from the tag [PG15/v1.4.0-**rc0**](https://github.com/apache/age/releases/tag/PG15%2Fv1.4.0-rc0). So, is it an RC (Release Candidate) version or a final (stable) version?

**Comment by yadav9887** [comment]
Hi @jirutka 
Thank you very much for sharing this issue. Our team is already looking into it. In the meantime, please do not hesitate to reach out if you have any questions. @dehowef @eyab

**Comment by eyab** [comment]
@jirutka, It is a final (stable) version. The RC0 tag is stable, well-tested, and has gone through all necessary quality checks. Hope this helps!!

**Comment by jirutka** [comment]
So why is it called `-rc0`? What does it stands for if not Release candidate?

**Comment by dehowef** [comment]
@jirutka When we do our releases, our process is we tag it with a RC tag to demarcate that that branch is the one that is our release candidate. It does seem a little confusing now that you mention it. Moving forward maybe we'll change the process for doing so.
