### ISSUE TITLE
Unexpected termination on looping cypher query - could not find rte

### ISSUE THREAD

**Issue by I33Buckler** [apache/age#1260]
Have encountered an intriguing issue with loading a table with a large number of rows into Apache AGE. The process is looping through PL/pgSQL. 
The looping terminates with the following message.
```
SQL Error [42703]: ERROR: could   not find rte for a01a724103fbb3d059b8387bf043dbc8     Where: PL/pgSQL function analysis.create_trips(text,text,text,text,text,text,integer,text,integer)   line 5 at EXECUTE
```
The database version is PostgreSQL 15.4 (Debian 15.4-2.pgdg120+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit. 
The Apache AGE version is 1.4.0 for PG15 built from the repository.
The error results from the following process.
```sql
SELECT create_graph('transport_network');

CREATE OR REPLACE FUNCTION analysis.create_trips
(graph_name text,
service_key text,service_id text, trip_id text, trip_headsign text, route_id text, direction_id int, shape_id text, wheelchair_accessible int)
returns text
LANGUAGE plpgsql
VOLATILE
as $trips$
declare
nodename text := graph_name || '.' || 'trips';
BEGIN
execute
format ('select * from cypher(''%1$s'', $$match (v:routes {id: %6$s})
create(v)-[:USES]->
(t:trips
{service_key: %2$s, service_id: %3$s, id: %4$s, headsign: %5$s, route_id: %6$s, direction_id: %7$s, shape_id: %8$s,
wheelchair_accessible: %9$s})$$) as (t agtype);',
quote_ident(graph_name),
quote_ident(service_key),quote_ident(service_id),
quote_ident(trip_id),quote_ident(trip_headsign),
quote_ident(route_id),to_char(direction_id,'9'),quote_ident(shape_id),to_char(wheelchair_accessible,'9'));
return nodename;
END
$trips$
;

select create_vlabel('transport_network','trips');

do $$
declare temprow record;
graph_name text:='transport_network';
counter integer := 0 ;
begin
for temprow in select service_key, service_id, trip_id from allservices.trips
order by service_key,trip_id
loop
counter := counter+1; -- Prevent replication of row
perform
analysis.create_trips
(graph_name,
a.service_key, a.service_id,
a.trip_id, a.trip_headsign,
a.route_id, a.direction_id, a.shape_id,
a.wheelchair_accessible)
from
(select row_number() over (order by service_key,trip_id) as row_num,
service_key, service_id,
trip_id, trip_headsign,
route_id, direction_id, shape_id,
coalesce(wheelchair_accessible,0) as wheelchair_accessible from allservices.trips) a
where a.row_num=counter
;
end loop;
end; $$;
```
In this case the string after the rte in the error message refers to the service_key value in the table allservices.trips. 
The first instance of the record in this instance is.
|row_num|service_key                                           |service_id|trip_id|trip_headsign|route_id|direction_id|shape_id|wheelchair_accessible|
|---------:|:------------------------------------------|:----------|:-------|:--------------|:--------|------------:|:----------|-----------------------:|
|7741      |a01a724103fbb3d059b8387bf043dbc8|FR           |307      |Gunghalin Pl|X1         |0                |1002        |1                                | 

The attributes of the table being processed are:
* Total size with indexes: 60MB
* Number of rows 231,131

**Comment by I33Buckler** [comment]
Further investigation has determined that the process continues until row 123,486 of the 231,131 rows in the table. 
Would be interested to know what could be the cause of this hard limit on processing the table as there is no obvious reason for it.

**Comment by jrgemignani** [comment]
@I33Buckler Have you tried against the **master** branch which is also at PostgreSQL 15?

**Comment by I33Buckler** [comment]
> @I33Buckler Have you tried against the **master** branch which is also at PostgreSQL version 15?

Yes. 
I have version 1.4.0 installed from the master branch.
name|default_version|installed_version
---|---|---
age|1.4.0|1.4.0

**Comment by jrgemignani** [comment]
@I33Buckler Is it always failing on the same row? What happens if you remove that row?

**Comment by I33Buckler** [comment]
> @I33Buckler Is it always failing on the same row? What happens if you remove that row?

Fails in exactly the same row number regardless of content.

**Comment by jrgemignani** [comment]
@I33Buckler Is the rte not found always the same or different?

**Comment by I33Buckler** [comment]
> @I33Buckler Is the rte not found always the same or different?

The RTE value depends on the content of service_key in the effected row

**Comment by jrgemignani** [comment]
@I33Buckler If you are able to restart it, from where it left off, does it error at the same location? Or, the same distance from where it started?

**Comment by I33Buckler** [comment]
> @I33Buckler If you are able to restart it, from where it left off, does it error at the same location? Or, the same distance from where it started?

At the same location.

**Comment by jrgemignani** [comment]
@I33Buckler I think what I meant to say was, if it fails at `row_num` **7741** what happens if you have it run to **7740** and then start the next run from **7741** to **7741+7740** and increments of **7740** there afterwards?

**Comment by I33Buckler** [comment]
> @I33Buckler I think what I meant to say was, if it fails at `row_num` **7741** what happens if you have it run to **7740** and then start the next run from **7741** to **7741+7740** and increments of **7740** there afterwards?

Sorry for the confusion. 
The issue is actually at row 123486. The previous instance was identified as 7741 because I matched by service_key rather than row number so the processed table was not sorted to match 1:1 with the table **temprow**. 
After ensuring 1:1 row match between **temprow** and **allservices.trips** it was discovered that the actual row number effected was 123486. 
As noted at https://github.com/apache/age/issues/1260#issuecomment-1751540744 splitting the table up to row 123486 resulted in successful processing. It was when row 123487 was introduced into the AGE graph table that the error occured.

**Comment by jrgemignani** [comment]
@I33Buckler Btw, just for clarification, what do you mean by "splitting the table" or "splitting the process into separate tables"? The input table loading the same graph database?

**Comment by I33Buckler** [comment]
In the first instance of the I processed the table ALLSERVICES.TRIPS as a single table. This was where the error was experienced. 
First step was to identify where the error occured. Ensuring that the TEMPROW table and ALLSERVICES.TRIPS were matched 1:1 in the loop the row number 123487 was identified as the location. 
To examine this error I then separated ALLSERVICES.TRIPS into TRIPS1 and TRIPS2 where TRIPS1 contained rows 1 to 123486 from ALLSERVICES.TRIPS. 
I processed TRIPS1 in the loop which inserted into the graph table 'Transport Analysis'.Trips.
This process succeeded. 
I then applied the process to TRIPS2 with the result being immediate failure suggesting the graph table could not accept an additional row.

**Comment by jrgemignani** [comment]
@I33Buckler As part of debugging indexes, I've created graphs with over 1 million rows, in the same graph, with the same label, and containing properties. So, I don't think this is a limit based on the number of rows. Additionally, if it were, it would likely land on an obvious base 2 number.

We need to break this down by removing items that might be extraneous. What happens if you reduce by 1 the number of parameters, and thus the number of properties, to the create_trips function? Try removing each parameter, while keeping the rest, to see if a specific parameter may be an issue?

**Comment by I33Buckler** [comment]
> `pg_ctrl restart`

Thank you for the suggestion. 
Restarting the server did not solve the problem. 
However, it introduced an additional error in the process.
Running the following code block
```
do $$
declare temprow record;
		graph_name text:='transport_network';
		counter integer := 123486 ;
begin 
for temprow in select service_key, trip_id from trips2 order by service_key,trip_id
loop
counter := counter+1; -- Prevent replication of row
perform 
	public.create_trips	
	(graph_name,a.service_key, a.service_id,a.trip_id, a.trip_headsign,a.route_id, a.direction_id, a.shape_id,a.wheelchair_accessible) 
	from 
	(select * from trips2 where row_num=counter) a
;
end loop;
end; $$
```
Resulted in
```
ERROR: unhandled cypher(cstring) function call
  Detail: transport_network
  Where: SQL statement "select * from cypher('transport_network', $$match (v:routes {id: "X1"})
			create(v)-[:USES]->
			(t:trips 
			{service_key: a01a724103fbb3d059b8387bf043dbc8, service_id: "FR", id: "307", headsign: "Gungahlin Pl", route_id: "X1", direction_id:  0, shape_id: "1002", 
					wheelchair_accessible:  1})$$) as (t agtype);"
PL/pgSQL function create_trips(text,text,text,text,text,text,integer,text,integer) line 5 at EXECUTE
SQL statement "SELECT 
	public.create_trips	
	(graph_name,a.service_key, a.service_id,a.trip_id, a.trip_headsign,a.route_id, a.direction_id, a.shape_id,a.wheelchair_accessible) 
	from 
	(select * from trips2 where row_num=counter) a"
PL/pgSQL function inline_code_block line 9 at PERFORM
```
I ran the process again with the following result.
```
ERROR: could not find rte for a01a724103fbb3d059b8387bf043dbc8
  Where: PL/pgSQL function create_trips(text,text,text,text,text,text,integer,text,integer) line 5 at EXECUTE
SQL statement "SELECT 
	public.create_trips	
	(graph_name,a.service_key, a.service_id,a.trip_id, a.trip_headsign,a.route_id, a.direction_id, a.shape_id,a.wheelchair_accessible) 
	from 
	(select * from trips2 where row_num=counter) a"
PL/pgSQL function inline_code_block line 9 at PERFORM
```

**Comment by jrgemignani** [comment]
Hmmmm,... maybe there is an issue with stored procedures.

**Comment by jrgemignani** [comment]
@I33Buckler After the restart did you load the extension before running that query? As you stated rerunning it appeared to not generate that error again.

**Comment by jrgemignani** [comment]
@I33Buckler Also, did you try reducing the number of parameters, as mentioned above, to see if that has an impact? I'm trying to think of ways to condense this down to a smaller, repeatable issue.

**Comment by jrgemignani** [comment]
@I33Buckler I'm also thinking it might be best if we try to reproduce this locally. It will save a lot of back and forth. How can we create the dataset that you have?

**Comment by I33Buckler** [comment]
> @I33Buckler I'm also thinking it might be best if we try to reproduce this locally. It will save a lot of back and forth. How can we create the dataset that you have?
I can provide you with the tables and the query at a shared link.

**Comment by jrgemignani** [comment]
@I33Buckler The `pg_dump` requires the table definitions (creates) in order to load them. Did you miss adding some definition files by chance? 

Also, could you also give access to @rafsun42

**Comment by I33Buckler** [comment]
> @I33Buckler The `pg_dump` requires the table definitions (creates) in order to load them. Did you miss adding some definition files by chance? Or, I could be doing it incorrectly,...
> 
> Also, could you also give access to @rafsun42

Thanks. Had the wrong configuration.

**Comment by rafsun42** [comment]
It seems `quote_ident` is not working as expected for some `trips2.service_key`.
```
(pg-15.4) agedev=# SELECT quote_ident(service_key) FROM trips1 LIMIT 1;
            quote_ident             
------------------------------------
 "01a5f85d9dd4392c29c0cf9040cd324f"
(1 row)

(pg-15.4) agedev=# SELECT quote_ident(service_key) FROM trips2 LIMIT 1;
           quote_ident            
----------------------------------
 a01a724103fbb3d059b8387bf043dbc8
(1 row)

```
If `a01a724103fbb3d059b8387bf043dbc8` is not wrapped, cypher thinks it is a variable.

**Comment by jrgemignani** [comment]
@I33Buckler I think the data might have some bad characters in it.

**Comment by jrgemignani** [comment]
@I33Buckler Here's why -

```
/*
 * quote_identifier                     - Quote an identifier only if needed
 *
 * When quotes are needed, we palloc the required space; slightly
 * space-wasteful but well worth it for notational simplicity.
 */
const char *
quote_identifier(const char *ident)
{
        /*
         * Can avoid quoting if ident starts with a lowercase letter or underscore
         * and contains only lowercase letters, digits, and underscores, *and* is
         * not any SQL keyword.  Otherwise, supply quotes.
         */

```

**Comment by jrgemignani** [comment]
@I33Buckler There is a global variable that can change this behavior -

```
        if (quote_all_identifiers)
                safe = false;
```

```
/* Globals exported by this file */
int                     quote_all_identifiers = 0;
```

See the following for more information -

[https://www.postgresql.org/docs/current/runtime-config-compatible.html](https://www.postgresql.org/docs/current/runtime-config-compatible.html)

**Comment by jrgemignani** [comment]
@I33Buckler updated comments above.

**Comment by jrgemignani** [comment]
@I33Buckler There is a function `quote_literal` but that uses single quotes instead, not double.

**Comment by I33Buckler** [comment]
> @I33Buckler There is a function `quote_literal` but that uses single quotes instead, not double.

Thank you for the responses.
Was not immediately obvious from the error message. 
The service_key is a field that was created from an MD5 hash to create a reference for some attributes in the source data that were unexpectedly not unique.
The information provided is helpful.

**Comment by I33Buckler** [comment]
Have changed the quote_ident() function to format() to ensure the service_key value is quoted.
```
format('"%s"',service_key),
```
This now results in the operation terminating with the following message.
```
ERROR: syntax error at or near ","
  Where: PL/pgSQL function create_trips(text,text,text,text,text,text,integer,text,integer) line 5 at EXECUTE
SQL statement "SELECT 
	public.create_trips	
	(graph_name, a.service_key, a.service_id,a.trip_id, a.trip_headsign,a.route_id, a.direction_id, a.shape_id,a.wheelchair_accessible) 
	from 
	(select * from trips where row_num=counter) a"
PL/pgSQL function inline_code_block line 9 at PERFORM`
```

**Comment by I33Buckler** [comment]
Issue now resolved using format() to assign quotes 
A small issue of NULL in the field **trip_headsign** easily resolved.
Applied format as below
```
format('"%s"',service_key)
```

**Comment by jrgemignani** [comment]
@I33Buckler Error messages can be misleading at times. Although, in this particular case, I'm not sure if any specific error message would have been able to help. The lack of quotes on that parameter seemed to change the cypher command structure making it something that was technically legal but didn't make sense when executed.

We will keep it in mind, though, and try to see if there might be a way to better address these.
