### ISSUE TITLE
Support for Postgres14?

### ISSUE THREAD

**Issue by simonriggs** [apache/age#127]
The docs say "Apache AGE is currently being developed for the PostgreSQL 11 release and will support PostgreSQL 12 and 13 in 2021".

What versions are supported? Please update README to reflect status/progress. Thanks!

**Comment by jrgemignani** [comment]
We are still working on finishing up AGE for PG 11, at the moment.

Support for PG 12 and beyond likely won't start until 2022.

I will have someone follow up with an update to the documentation.

john

**Comment by blusewang** [comment]
Oh！at 2022, PG 15 will released! come on! AGE!

**Comment by emotionbug** [comment]
Maybe on PG15, will be support hook for parser. It will take time, but I think it will be possible to implement like AgensGraph.

https://www.postgresql.org/message-id/20210501072458.adqjoaqnmhg4l34l@nol

**Comment by JoshInnis** [comment]
We are currently working on AGE compatibility with Postgres 12. Postgres 13 and beyond is currently being researched. Please expect a slightly more accelerated status update for Postgres 12+ coming soon. For even more updates on the status of Postgres 12+ subscribe to the incubating-Apache AGE dev mailing list by sending an email to: dev-subscribe@age.apache.org. We have many issue to discuss regarding backwards compatibility coming soon.

**Comment by rtrad89** [comment]
Are there are ETA for PG 14 support please?

**Comment by blusewang** [comment]
> @rtrad89 PG14 is currently being worked on and is expected to be supported within a month. An experimental branch has been available to test for many months.

Come on! dude! You need support PG15 now! -_-!!!

**Comment by jrgemignani** [comment]
@blusewang I know everyone is anxious. PG14 is about week away, PG15, I believe, is a month away.
