### ISSUE TITLE
Unexpected error when matching nodes that are connected to nodes resulted from a previous MATCH clause

### ISSUE THREAD

**Issue by ns-hygao** [apache/age#1393]
**Describe the bug**
I simplified the Cypher query to do the following:
1. `MATCH` nodes with `Object` label
2. `MATCH` nodes that are connected with the nodes resulting from the previous query by any edge
3. `RETURN` the nodes

**How are you accessing AGE (Command line, driver, etc.)?**
- Command line inside `psql` client

**What data setup do we need to do?**
Minimal data setup:
postgresDB=# SELECT * FROM ag_catalog.create_graph('testgraph');
postgresDB=# SELECT * FROM cypher('testgraph', $$ CREATE (n1:Object)  RETURN n1$$)
postgresDB=# SELECT * FROM cypher('testgraph', $$ MATCH (n1:Object)
                    MATCH (n2:Object)
                    WHERE EXISTS((n1)-[]->(n2))
                    RETURN n2 $$)
AS (n2 agtype);
ERROR:  missing FROM-clause entry for table "n1"
LINE 1: SELECT * FROM cypher('testgraph', $$ MATCH (n1:Object)

**What is the necessary configuration info needed?**

**What is the command that caused the error?**
postgresDB=# SELECT * FROM cypher('testgraph', $$ MATCH (n1:Object)
                    MATCH (n2:Object)
                    WHERE EXISTS((n1)-[]->(n2))
                    RETURN n2 $$)
AS (n2 agtype);
ERROR:  missing FROM-clause entry for table "n1"
LINE 1: SELECT * FROM cypher('testgraph', $$ MATCH (n1:Object)

**Expected behavior**
The query should succeed and return 0 rows.

**Environment (please complete the following information):**
- Installed from docker image obtained from command command `docker pull apache/age`
- Run using docker command `docker run \
    --name myPostgresDb  \
    -p 5455:5432 \
    -e POSTGRES_USER=postgresUser \
    -e POSTGRES_PASSWORD=postgresPW \
    -e POSTGRES_DB=postgresDB \
    -d \
    apache/age`
- PostgreSQL version 15.4

**Additional context**

**Comment by jrgemignani** [comment]
@ns-hygao Thank you for pointing out this bug, we will address it. I will point out, though, this particular command is the same as the following, which does work -

```
psql-15.4-5432-pgsql=# SELECT * FROM cypher('testgraph', $$ MATCH (n1)-[]->(n2) RETURN n2 $$) AS (n2 agtype);
 n2
----
(0 rows)

psql-15.4-5432-pgsql=#
```

**Comment by ns-hygao** [comment]
> @ns-hygao Thank you for pointing out this bug, we will address it. I will point out, though, this particular command is the same as the following, which does work -
> 
> ```
> psql-15.4-5432-pgsql=# SELECT * FROM cypher('testgraph', $$ MATCH (n1)-[]->(n2) RETURN n2 $$) AS (n2 agtype);
>  n2
> ----
> (0 rows)
> 
> psql-15.4-5432-pgsql=#
> ```

Hi @jrgemignani , Thanks for the response. I realize the 2nd command is equivalent. The original command I tried to run is more complicated and cannot be expressed in one clause. What is reported here is the simplified version after removing all other conditions that do not cause the error.

**Comment by jrgemignani** [comment]
@ns-hygao Unfortunately, the other PR doesn't quite fix your issue. I am still working on resolving it.

**Comment by jrgemignani** [comment]
This issue should be fixed in PR #1426 which is now in review.

**Comment by rafsun42** [comment]
@ns-hygao Hi, could you let us know if the PR mentioned above solves the issue?

**Comment by ns-hygao** [comment]
Hi, the issue has been fixed. Closing out now.
