### ISSUE TITLE
Filter NOT EXISTS leads to an error if a relation label does not exists as database table

### ISSUE THREAD

**Issue by nupis-DanielS** [apache/age#1399]
**Describe the bug**
We run in an error if we query for a non existing relationship. If the filter contains the label of the relationship it will return "Variable `foo` does not exist". When the relationship label is not used everything works as expected. It looks like that the error occurs only when the database table for the label is not present..

**How are you accessing AGE (Command line, driver, etc.)?**
- JDBC
- pg (Node)

**What data setup do we need to do?**
```pgsql
/
```

**What is the necessary configuration info needed?**
- /

**What is the command that caused the error?**
```pgsql
SELECT * FROM cypher('property-graph', $$ 
  MATCH (foo)
  WHERE NOT exists((foo)-[:BAR]->())
  RETURN count(foo) > 0
$$) as (c agtype)
```
```
Variable `foo` does not exist
```

**Expected behavior**
false

**Environment (please complete the following information):**
- Version: 1.4.0
- PostgreSQL: 14.6 (Ubuntu 14.6-1.pgdg22.04+1)

**Additional context**
Without non existing relation label it works as expected (result -> false).

**Comment by jimenasansav** [comment]
Hi @nupis-DanielS! Thank you for letting us know about this issue. Our technical team is already going through it and will provide a solution soon. In the meantime, please feel free to reach out if you have any other questions.

**Comment by jrgemignani** [comment]
@nupis-DanielS I will look into this.

**Comment by jrgemignani** [comment]
@nupis-DanielS PR #1400 should resolve this once reviewed and merged.

**Comment by jrgemignani** [comment]
@nupis-DanielS The fix is now in the master branch. If you could verify that it satisfactorily resolves your issue and close it, that would be great.

**Comment by nupis-DanielS** [comment]
> @nupis-DanielS The fix is now in the master branch. If you could verify that it satisfactorily resolves your issue and close it, that would be great.

Hi @jrgemignani . We would love to test this but we use the "PG14" Branch. I think we will create a separate PG14 branch and cherry pick your commit. We close this issue if everything works as expected.

Thank you

**Comment by MuhammadTahaNaveed** [comment]
> Hi @jrgemignani . We would love to test this but we use the "PG14" Branch. I think we will create a separate PG14 branch and cherry pick your commit. We close this issue if everything works as expected.
> 
> Thank you

The fix is now on PG14 branch as well. It would be great if you could check it out.

**Comment by nupis-DanielS** [comment]
Hello again @jrgemignani. Your fix works. The query returns successful even if the relationship label does not exist in the database. Thank you
