### ISSUE TITLE
Update to Apache AGE's directory on PGXN

### ISSUE THREAD

**Issue by Allison-E** [apache/age#1411]
AGE on PostgreSQL Extension Network (PGXN) is outdated. The last release on the website is 1.1.0, and the description (including the README) is stale. Do you think this can be updated?

Link to Apache AGE's directory on PGXN: [https://pgxn.org/dist/apacheage/](https://pgxn.org/dist/apacheage/)

**Comment by jrgemignani** [comment]
@eyab Would this be something you could look into?

**Comment by MuhammadTahaNaveed** [comment]
@Allison-E @jrgemignani PR #1711 should resolve this issue once merged.
