### ISSUE TITLE
AGE Cypher query matching variable length edges with [*] returns zero rows

### ISSUE THREAD

**Issue by ajit-satav** [apache/age#1413]
While executing variable length query I am getting zero results

SELECT *
FROM cypher('demo', $$
    MATCH (a:Employee{name:'xxxx'})-[*]-(b)
    RETURN a
$$) as (a agtype);
But if I do execute below query without variable length edges (*) it works and returns results

SELECT *
FROM cypher('demo', $$
    MATCH (a:Employee{name:'xxxx'})-[]-(b)
    RETURN a
$$) as (a agtype);

Any suggestions why query with * is returning zero results?

**Comment by jimenasansav** [comment]
Hi @ajit-satav! Thank you very much for your question. Our team will look through it and provide an answer soon.

**Comment by rafsun42** [comment]
@ajit-satav 

Both with and without `*` produced same result on the latest master.
```
(pg-15.4) agedev=# SELECT *
FROM cypher('demo', $$
MATCH (a:Employee{name:'xxxx'})-[]-(b)
RETURN a
$$) as (a agtype);
                                           a                                           
---------------------------------------------------------------------------------------
 {"id": 1125899906842625, "label": "Employee", "properties": {"name": "xxxx"}}::vertex
(1 row)
```
```
(pg-15.4) agedev=# SELECT *
FROM cypher('demo', $$
MATCH (a:Employee{name:'xxxx'})-[*]-(b)
RETURN a
$$) as (a agtype);
                                           a                                           
---------------------------------------------------------------------------------------
 {"id": 1125899906842625, "label": "Employee", "properties": {"name": "xxxx"}}::vertex
(1 row)
```

I created the entities using-
```sql
SELECT * FROM cypher ('demo', $$ CREATE (a:Employee{name:'xxxx'})-[:rel]->(b) $$) as (a agtype);
```

**Comment by ajit-satav** [comment]
it is working for me as well with limited number of vertices and edges. Issue appears when I loaded around 500k vertices and 900k edges

**Comment by rafsun42** [comment]
@ajit-satav Is it possible to share your dataset?

**Comment by jrgemignani** [comment]
@ajit-satav Can you provide an output showing the two queries where one works and the other doesn't? Like what @rafsun42 showed above. Use the <> code option so that we can see that output here.

**Comment by jrgemignani** [comment]
@ajit-satav Also, please explain what you mean by "start breaking". Do you mean taking a long time? When you query for variable length edges with just `[*]`, that means all lengths. When you use directionless edges `-[*]-` that means both directions. On a large graph, using both can be intensive depending on how connected the graph is.

Additionally, what version of AGE are you using?

**Comment by ajit-satav** [comment]
1. AGE Version - 1.4.0

2. Start breaking means it gives me zero results
    e..g
    
    ```
      SELECT * from 
       cypher('demo', $$
	      MATCH (c1:components{name:'XXXX'})-[]-(c2:versions)
	      return c2.name
      $$) as (v agtype);
    ```  
      Results - No of c2.name returned - 2 
    
    ```
      SELECT * from 
       cypher('demo', $$
	      MATCH (c1:components{name:'XXXX'})-[*]-(c2:versions)
	      return c2.name
      $$) as (v agtype);
    ```  
    Results - No of c2.name returned - 0

**Comment by jrgemignani** [comment]
@ajit-satav Could you please include the results of the queries along with the queries? In particular, the full output of c1, c2, and the edge. Say, these queries instead -

```
SELECT * from 
   cypher('demo', $$
      MATCH (c1:components{name:'XXXX'})-[e]-(c2:versions)
      return c1,c2,e
  $$) as (c1 agtype, c2 agtype, e agtype);

SELECT * from 
   cypher('demo', $$
      MATCH (c1:components{name:'XXXX'})-[e*]-(c2:versions)
      return c1,c2,e
  $$) as (c1 agtype, c2 agtype, e agtype);
```

Just looking at the queries, and not the results (blank or otherwise), doesn't really give us much to go on.

**Comment by jrgemignani** [comment]
@ajit-satav Is this still a problem or is the issue resolved?
