### ISSUE TITLE
JDBC Driver error during compile time

### ISSUE THREAD

**Issue by amthiagomont** [apache/age#1440]
**Describe the bug**

I have a small issue to decribe. This error occurs in  jdbc driver.
When I try to compile I occurs this error message: 
```
$ ./gradlew assemble 
Erro: Não foi possível localizar nem carregar a classe principal org.gradle.wrapper.GradleWrapperMain
Causada por: java.lang.ClassNotFoundException: org.gradle.wrapper.GradleWrapperMain
```
This error is  happening because the file gradle-wrapper.jar dont exists in directory. I verify that in the file  .gitignore there is a configuration to exclude this file.
When I drop gradlew and grandlew.bat and create a new wrapper with the same gradle version  and it works!
How about remove  entry for .gitignore file and put gradle-wrapper.jar in the repository? Or at least exclude gradle wrapper binary to force run gradle wrapper again? 
I hope this issue can help others developpers. 
Thanks for this driver and  I hope that this issue can be resolved as soon as possible.

**How are you accessing AGE (Command line, driver, etc.)?**
- JDBC

**What data setup do we need to do?**
None

**What is the necessary configuration info needed?**
- Only try to compile java driver

**What is the command that caused the error?**
```
$ ./gradlew assemble 
```
```
Erro: Não foi possível localizar nem carregar a classe principal org.gradle.wrapper.GradleWrapperMain
Causada por: java.lang.ClassNotFoundException: org.gradle.wrapper.GradleWrapperMain
```

**Expected behavior**
Succesfull compile

**Environment (please complete the following information):**
- Version: Latest

**Additional context**
When I drop gradlew and grandlew.bat and create a new wrapper with the same gradle version  and it works!
How about remove  entry for .gitignore file and put gradle-wrapper.jar in the repository? Or at least exclude gradle wrapper binary to force run gradle wrapper again?

**Comment by amthiagomont** [comment]
Waiting for a feedback

**Comment by jrgemignani** [comment]
@amthiagomont Could you provide the command you used to build the file?

**Comment by amthiagomont** [comment]
I just cloned the repository and ran the command `$ ./gradlew assemble `, as i described when i open the issue.

**Comment by jrgemignani** [comment]
@amthiagomont Thank you. I was able to reproduce it. However, I'm not exactly sure what you mean by -

> Additional context
When I drop gradlew and grandlew.bat and create a new wrapper with the same gradle version and it works!
