### ISSUE TITLE
Cypher query to exlude subpaths (or return only full paths)

### ISSUE THREAD

**Issue by FrancescoSillani** [apache/age#1464]
Hello all,

I have the following (simplified) scenario:

A -> [R] -> B
B -> [R] -> C

where A, B, C are vertex of my graph, and R is a relation. 

With the following query:

MATCH p = (t1)-[R*]->(t2)

the following paths are returned:

A -> B, 
B->C, 
A -> B -> C

Is it possible to build a query that returns only the following path: A -> B -> C?

I was thinking about 

- adding a WHERE clause similar to "WHERE not t2 -> [R] -> ()" 
- adding a MATCH similar to "MATCH NOT (p1 =  (t2)-[R]->())"

but I'm not able to obtain a valid query... 

Could you please me give any advice?

Thanx a lot in advance

**Comment by rafsun42** [comment]
@FrancescoSillani 

Given you scenario, does this path `A -> B -> C` exists?

**Comment by rafsun42** [comment]
@FrancescoSillani 

Assuming, your scenario is- `A -> [R] -> B -> [R] -> C`, please refer to the documentation on [variable length edges](https://age.apache.org/age-manual/master/clauses/match.html#variable-length-edges). You can MATCH paths with exactly 2 edges using `(t1)-[:R*2]->(t2)`.
