### ISSUE TITLE
How to specify property types when loading vertices from files with "load_labels_from_file“ 

### ISSUE THREAD

**Issue by jhan129** [apache/age#1502]
hi, i wonder if there is any way I can specify property types when loading vertices from CSV? it seems all the properties will be loaded as String, though some of them are numeric values in my csv. 

Thanks!

**Comment by rafsun42** [comment]
The requested behavior is added to the latest master branch by in PR #1519.

**Comment by jrgemignani** [comment]
@jhan129 If this resolves your question satisfactorily, please consider closing this ticket :)

**Comment by jhan129** [comment]
@rafsun42 @jrgemignani Thanks for the update!
