### ISSUE TITLE
No update path to 1.5.0

### ISSUE THREAD

**Issue by guruguruguru** [apache/age#1508]
Hi,

I have installed AGE 1.5.0 but the sql files for updating are missing. Is there no update path planned or was this just missed in the release?

`asmaage=# alter extension age update;
ERROR:  extension "age" has no update path from version "1.4.0" to version "1.5.0"
`

Thanks,
Dennis

**Comment by jrgemignani** [comment]
@guruguruguru Without knowing the specific PostgreSQL version of Apache AGE you are using, I can't give you a specific answer. However, per the latest RELEASE notes, which generally applies to all but PostgreSQL 16 -

```
Apache AGE 1.5.0 - Release Notes

NOTE: Due to the complexity and the amount of additions, there are no
      upgrade scripts to this release.

```

We may try to provide these at a later date, but for this specific release it is a difficult process.

**Comment by guruguruguru** [comment]
Hi @jrgemignani ,

thanks for the reply. My fault for not checking the release notes :-(
So I am running/testing AGE in most PG Versions and wanted to upgrade my PG12 / AGE 1.4.0 Databases to PG16 / AGE 1.5.0.

Is there any way to do so right now?

**Comment by jrgemignani** [comment]
@guruguruguru Not a problem, it happens. 

There is no way, **currently**, to upgrade from one version of AGE in say, PostgreSQL version 12 to the same version of AGE in PostgreSQL version 16. Meaning that upgrading across PostgreSQL versions is not an option **currently**. This is something we plan to look into when we have the time and resources. However, at this moment, it isn't available.

As for upgrading AGE within a PostgreSQL version, we try to make it possible. However, sometimes changes are made such that you just can't. As AGE 1.5.0 for PG 16 is brand new, unfortunately, you have to start from scratch. Sorry about that.

**Comment by guruguruguru** [comment]
@jrgemignani thank you very much! I will close this Issue.
