### ISSUE TITLE
MERGE using array not working in some cases

### ISSUE THREAD

**Issue by mingfang** [apache/age#1630]
```cypher
WITH ['jon', 'snow'] AS cols
MERGE (v:PERSION {first: cols[0], last: cols[1]})
RETURN v
```
returns wrong result. person is missing first and last name.

```json
  {
    "v": {
      "id": 2533274790395920,
      "label": "PERSION",
      "properties": {}
    }
  }
```

but a slight change(return v, cols) works

```cypher
WITH ['jon', 'snow'] AS cols
MERGE (v:PERSION {first: cols[0], last: cols[1]})
RETURN v, cols
```
very strange.

**Comment by jrgemignani** [comment]
@mingfang Thank you for finding this bug. We will look into fixing it.

**Comment by jrgemignani** [comment]
@mingfang I found the issue and am working on a fix.

**Comment by jrgemignani** [comment]
@mingfang I should have a PR for the fix today. This particular bug is due to PG function `remove_unused_subquery_outputs`. For whatever reason, the PG logic feels that it is okay to remove the variable by replacing it, in place, with a NULL constant. The fix involves wrapping the variable with a volatile function so that it is kept.

**Comment by mingfang** [comment]
@jrgemignani 
Amazing detective work! 
Thanks for figuring it out so quickly.

**Comment by jrgemignani** [comment]
PR #1636 created to fix this issue in the master branch.

**Comment by mingfang** [comment]
@jrgemignani 
Thanks. 
Is the master compatible with PG16?

**Comment by jrgemignani** [comment]
@mingfang The master branch is currently PG16.

**Comment by mingfang** [comment]
I might not be building the master branch correctly because now I'm seeing a weird completely unrelated error with `unwind` clause. 
Here is my output
```sql
SELECT * FROM cypher('test', $$
     unwind ['a'] as v
     return v
$$) AS (v agtype)
 ```       
PostgresError: function age_unnest(agtype, boolean) does not exist

**Comment by jrgemignani** [comment]
@mingfang You may need to drop the extension and then reload it.

```
psql-16.1-5432-pgsql=# SELECT * FROM cypher('test', $$ unwind ['a'] as v return v $$) AS (v agtype);
  v
-----
 "a"
(1 row)

psql-16.1-5432-pgsql=#
```

**Comment by mingfang** [comment]
I was just about to say the master will need an upgrade script to change the `age_unnest()`.

**Comment by mingfang** [comment]
confirmed fixed
