### ISSUE TITLE
Apache AGE on alpine linux

### ISSUE THREAD

**Issue by ganesh-karthick** [apache/age#1652]
In the docs , we see installation for ubuntu, fedora, centos . 

Would it be possible to list the steps for alpine linux install with required libraries ?

**Comment by jirutka** [comment]
[postgresql-age](https://pkgs.alpinelinux.org/packages?name=postgresql-age&branch=edge) is currently in the testing repository in Alpine Linux Edge. I’ll move it to the community repository and it will be available in the upcoming Alpine Linux v3.20.

**Comment by aked21** [comment]
@jirutka 
It appears that the [postgresql-age](https://pkgs.alpinelinux.org/packages?name=postgresql-age&branch=edge) package is in the community repository.
Thank you!
