### ISSUE TITLE
Warning when building AGE on MacOS 

### ISSUE THREAD

**Issue by saygoodbyye** [apache/age#1662]
**Describe the bug**
Warning when building AGE on MacOS 

**How are you accessing AGE (Command line, driver, etc.)?**
Accessing AGE through command line.

**What data setup do we need to do?**
Apache AGE (PG15 branch) with PostgreSQL (REL_15_STABLE).

**What is the necessary configuration info needed?**
MacOS Sonoma 14.4
```shell
egor@MacBook-Air-Egor ~/Work/age (PG15) $ clang --version
Apple clang version 15.0.0 (clang-1500.3.9.4)
Target: arm64-apple-darwin23.4.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```
```shell
./configure CFLAGS=" -Og" --enable-tap-tests --enable-debug --enable-cassert --prefix=/tmp/pgsql
```

**What is the command that caused the error?**
```shell
egor@MacBook-Air-Egor ~/Work/age (PG15) $ make
```
```shell
src/backend/parser/cypher_gram.c:2198:5: warning: variable 'cypher_yynerrs' set but not used [-Wunused-but-set-variable]
int yynerrs;
    ^
src/backend/parser/cypher_gram.c:68:17: note: expanded from macro 'yynerrs'
#define yynerrs cypher_yynerrs
                ^
1 warning generated.
```

**Expected behavior**
Build without warnings

Best regards,
Egor Chindyaskin
Postgres Professional: https://postgrespro.com/

**Comment by Muhammad00Taha** [comment]
To resolve this warning, you could consider removing or modifying the declaration of cypher_yynerrs in the cypher_gram.c file. Since it's not being used, removing it entirely should resolve the warning.
