### ISSUE TITLE
MERGE incorrectly creates multiple vertices

### ISSUE THREAD

**Issue by mingfang** [apache/age#1691]
```sql
SELECT * FROM cypher('playground', $$
unwind ["foo", "foo"] as each
merge (v:TEST {name: each})
return v
$$) AS (v agtype)
```
returns
```json
[
  {
    "v": {
      "id": 3659174697238531,
      "label": "TEST",
      "properties": {
        "name": "foo"
      }
    }
  },
  {
    "v": {
      "id": 3659174697238532,
      "label": "TEST",
      "properties": {
        "name": "foo"
      }
    }
  }
]
```
creates two vertices when it should only create one. (confirmed with neo4j)

**Comment by mingfang** [comment]
maybe same as https://github.com/apache/age/issues/1446

**Comment by jrgemignani** [comment]
@mingfang This is expected behavior. The key `name` is a property of a vertex, in this case. Vertices and edges are allowed to have the same properties.

**Comment by mingfang** [comment]
@jrgemignani please note in my test case the problem is that there MERGE created two vertices with the same name, and not one vertex and one edge.

**Comment by jrgemignani** [comment]
@mingfang Yes. I was just stating that this is also the case for edges. Vertices can have duplicate properties and edges can have duplicate properties. Properties are not unique.

**Comment by mingfang** [comment]
I'm sorry but I don't think that's correct.
I've tested this in neo4j and it only results in one vertex created, not two like in AGE.
Here is the neo4j doc that speaks directly to this
https://neo4j.com/docs/cypher-manual/current/clauses/merge/#merge-merge-single-node-specifying-both-label-and-property
`Merging a single node with both label and property matching an existing node will not create a new node:`

**Comment by jrgemignani** [comment]
@mingfang I stand corrected. It seems odd, though, that properties would be unique in this sense. We will likely need to adjust the contains versus equals operator for this case.

**Comment by mingfang** [comment]
Also this is only a problem when multiple MERGE are called in the same query.
e.g. this works as expected, only one vertex is created
```
SELECT * FROM cypher('playground', $$
unwind ["foo"] as each
merge (v:TEST {name: each})
return v
$$) AS (v agtype)

SELECT * FROM cypher('playground', $$
unwind ["foo"] as each
merge (v:TEST {name: each})
return v
$$) AS (v agtype)
```
I'm guessing if multiple MERGE in the same query somehow is not seeing each statement's "state" since the transaction is not committed yet.  Totally a wild guess.

**Comment by jrgemignani** [comment]
Yeah, the more that I look at it, the more it appears to fall there. Transaction bugs, though, can be a pain to fix. Especially, for merge.

**Comment by jrgemignani** [comment]
@mingfang This is an interesting one.

**Comment by jrgemignani** [comment]
@mingfang The particular cause for this issue is hard to easily describe, especially without getting very technical. Suffice to say, that MERGE (within the execution of a MERGE command instance) can't see what it has just created. 

In most cases, this isn't an issue because MERGE only CREATEs what isn't already there. However, when it is driven externally, it is possible for it to have duplicates for duplicated data. I'm not sure if this is the only case where this is possible, though.

I am looking into how to allow MERGE to know prior to inserting a duplicate **and** if this can resolve the issue. This may take some time, though, to implement.

**Comment by mingfang** [comment]
@jrgemignani 
Thanks for the update.  
I appreciate all your hard work.
Thanks!

**Comment by jrgemignani** [comment]
@mingfang Update: I currently have a fix for this and am reviewing it, creating test cases, and cleaning up the code. If all goes well, a PR should be available Monday or Tuesday.

**Comment by jrgemignani** [comment]
@mingfang PR #1718 should address this issue once it is reviewed and merged.

**Comment by mingfang** [comment]
@jrgemignani Amazing. Thanks again!

**Comment by jrgemignani** [comment]
@mingfang This should be fixed in the master branch now. If you could verify it, and close the ticket provided it resolves the issue,  that would be great.

**Comment by mingfang** [comment]
@jrgemignani 
confirm fixed. Thank you!
