### ISSUE TITLE
How to handle the param if there're single quotes in it?

### ISSUE THREAD

**Issue by noahxzhu** [apache/age#1722]
**Describe the bug**
An error is observed when a property parameter includes a single quote.

**How are you accessing AGE (Command line, driver, etc.)?**
- I'm using the apache-age-python package in a python project.

**What data setup do we need to do?**
```python
def upsert_triplet_test(subj: str, rel: str, obj: str) -> None:
    prepared_statement = f"""
        MERGE (n1:`Entity` {{id: %s}})
        MERGE (n2:`Entity` {{id: %s}})
        MERGE (n1)-[:`{rel.replace(" ", "_").upper()}`]->(n2)
    """

    ag.execCypher(
        prepared_statement,
        params=(
            subj,
            obj,
        ),
    )

    ag.commit()


upsert_triplet_test(
    "I", "Learned", "It's better for technology companies to be run by product people"
)
```

This is the error
```
    cursor.execute(stmt)
psycopg2.errors.SyntaxError: syntax error at or near "'s better for technology companies to be run by product people'"
```

**What is the necessary configuration info needed?**
- nothing

**What is the command that caused the error?**
```pgsql
SELECT * from ag_catalog.cypher('graph_store', $$
     MERGE (n1:`Entity` {id: 'I'})
     MERGE (n2:`Entity` {id: 'It's better for technology companies to be run by product people'})
     MERGE (n1)-[:`Learned`]->(n2)
$$) as (a ag_catalog.agtype);
```
Not sure how to handle this case

```
ERROR:  syntax error at or near "s"
LINE 3:      MERGE (n2:`Entity` {id: 'It's better for technology com...
```

**Expected behavior**
This merge operation should be succeed.

**Environment (please complete the following information):**
- Version: package version 0.0.7
- AGE Version: 1.5.0

**Additional context**
no

**Comment by noahxzhu** [comment]
When I use Neo4j, I can create like this, the edge label can also include single quote
![CleanShot 2024-04-05 at 21 59 12@2x](https://github.com/apache/age/assets/8643866/03d3a264-c5c7-4e36-851c-ea49cac7557b)

**Comment by jrgemignani** [comment]
@noahxzhu Did you try using the backslash for the cypher query? Your example above doesn't show it.

**Comment by jrgemignani** [comment]
@noahxzhu Additionally, this sounds more like a question than a bug.

**Comment by markgomer** [comment]
Can you put double quotes around the string?

```cypher
SELECT * from ag_catalog.cypher('graph_store', $$
     MERGE (n1:`Entity` {id: 'I'})
     MERGE (n2:`Entity` {id: "It's better for technology companies to be run by product people"})
     MERGE (n1)-[:`Learned`]->(n2)
$$) as (a ag_catalog.agtype);
```

This worked for me alright

**Comment by noahxzhu** [comment]
> Can you put double quotes around the string?
> 
> ```cypher
> SELECT * from ag_catalog.cypher('graph_store', $$
>      MERGE (n1:`Entity` {id: 'I'})
>      MERGE (n2:`Entity` {id: "It's better for technology companies to be run by product people"})
>      MERGE (n1)-[:`Learned`]->(n2)
> $$) as (a ag_catalog.agtype);
> ```
> 
> This worked for me alright

@markgomer 
I just copy and paste yours, it seems not work

![CleanShot 2024-04-05 at 23 46 19@2x](https://github.com/apache/age/assets/8643866/cb16b2aa-09b2-4a94-94bc-6e752b04c3b2)

**Comment by noahxzhu** [comment]
> @noahxzhu Did you try using the backslash for the cypher query? Your example above doesn't show it.
> 
> ```
> psql-16.1-5432-pgsql=# SELECT * from ag_catalog.cypher('test', $$
>      MERGE (n1:`Entity` {id: 'I'})
>      MERGE (n2:`Entity` {id: 'It\'s better for technology companies to be run by product people'})
>      MERGE (n1)-[:`Learned`]->(n2)
> $$) as (a ag_catalog.agtype);
>  a
> ---
> (0 rows)
> 
> psql-16.1-5432-pgsql=# SELECT * FROM cypher('test', $$ MATCH (v) RETURN v $$) AS (v agtype);
>                                                                       v
> 
> ------------------------------------------------------------------------------------------------------------------------------------
> ----------
>  {"id": 844424930131969, "label": "Entity", "properties": {"id": "I"}}::vertex
>  {"id": 844424930131970, "label": "Entity", "properties": {"id": "It's better for technology companies to be run by product people"}
> }::vertex
> (2 rows)
> 
> psql-16.1-5432-pgsql=#
> ```

not work on my side, I need to investigate the reason

**Comment by markgomer** [comment]
> > Can you put double quotes around the string?
> > ```cypher
> > SELECT * from ag_catalog.cypher('graph_store', $$
> >      MERGE (n1:`Entity` {id: 'I'})
> >      MERGE (n2:`Entity` {id: "It's better for technology companies to be run by product people"})
> >      MERGE (n1)-[:`Learned`]->(n2)
> > $$) as (a ag_catalog.agtype);
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This worked for me alright
> 
> @markgomer I just copy and paste yours, it seems not work
> 
> ![CleanShot 2024-04-05 at 23 46 19@2x](https://private-user-images.githubusercontent.com/8643866/320061243-cb16b2aa-09b2-4a94-94bc-6e752b04c3b2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIzMzI1MDgsIm5iZiI6MTcxMjMzMjIwOCwicGF0aCI6Ii84NjQzODY2LzMyMDA2MTI0My1jYjE2YjJhYS0wOWIyLTRhOTQtOTRiYy02ZTc1MmIwNGMzYjIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDVUMTU1MDA4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDE1Yzc4OGJmMTA3MDEwMWExYWM5MGUxYjU3MmRmMTdhYjg1N2IyNzBjM2ZlNDQ1Y2M0YzMxYjVjZjlmMDI0MCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.I_akTn9vwmn3CJ8uR-0tgiglnF06j2w1u2rO0p_QMHU)

Try setting the search_path:

```cypher
SET search_path TO ag_catalog;
```

I'm not sure why it is not working without this, though.

**Comment by noahxzhu** [comment]
> > > Can you put double quotes around the string?
> > > ```cypher
> > > SELECT * from ag_catalog.cypher('graph_store', $$
> > >      MERGE (n1:`Entity` {id: 'I'})
> > >      MERGE (n2:`Entity` {id: "It's better for technology companies to be run by product people"})
> > >      MERGE (n1)-[:`Learned`]->(n2)
> > > $$) as (a ag_catalog.agtype);
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > This worked for me alright
> > 
> > 
> > @markgomer I just copy and paste yours, it seems not work
> > ![CleanShot 2024-04-05 at 23 46 19@2x](https://private-user-images.githubusercontent.com/8643866/320061243-cb16b2aa-09b2-4a94-94bc-6e752b04c3b2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIzMzI1MDgsIm5iZiI6MTcxMjMzMjIwOCwicGF0aCI6Ii84NjQzODY2LzMyMDA2MTI0My1jYjE2YjJhYS0wOWIyLTRhOTQtOTRiYy02ZTc1MmIwNGMzYjIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDVUMTU1MDA4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDE1Yzc4OGJmMTA3MDEwMWExYWM5MGUxYjU3MmRmMTdhYjg1N2IyNzBjM2ZlNDQ1Y2M0YzMxYjVjZjlmMDI0MCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.I_akTn9vwmn3CJ8uR-0tgiglnF06j2w1u2rO0p_QMHU)
> 
> Try setting the search_path:
> 
> ```cypher
> SET search_path TO ag_catalog;
> ```
> 
> I'm not sure why it is not working without this, though.

After setting the search_path, now it's working, but why?

**Comment by noahxzhu** [comment]
Another question, should this work as it in Neo4j?
```
SELECT * from ag_catalog.cypher('graph_store', $$
	MERGE (n1:`TEST`{id: 'a\'bb'})
	MERGE (n2:`TEST`{id: 'bb \'s abc'})
	MERGE (n1)-[:`ABC_I'S_a`]->(n2)
$$) as (a ag_catalog.agtype);
```

**Comment by noahxzhu** [comment]
I still have the problem with the python driver, how to handle it with a param which contains single quotes, I digged into the python code, it do set the search_path, but not works
![CleanShot 2024-04-06 at 00 16 39@2x](https://github.com/apache/age/assets/8643866/2cee9924-e3df-432b-b796-8bb2d71f8dbd)

**Comment by jrgemignani** [comment]
@noahxzhu 

> After setting the search_path, now it's working, but why?

The search path is needed to see Cypher

**Comment by jrgemignani** [comment]
> Another question, should this work as it in Neo4j?
> 
> ```
> SELECT * from ag_catalog.cypher('graph_store', $$
> 	MERGE (n1:`TEST`{id: 'a\'bb'})
> 	MERGE (n2:`TEST`{id: 'bb \'s abc'})
> 	MERGE (n1)-[:`ABC_I'S_a`]->(n2)
> $$) as (a ag_catalog.agtype);
> ```

I'm not sure I understand what you are asking. Also, keep in mind that you will likely need to backslash all non wrapping quote characters.

**Comment by noahxzhu** [comment]
> > Another question, should this work as it in Neo4j?
> > ```
> > SELECT * from ag_catalog.cypher('graph_store', $$
> > 	MERGE (n1:`TEST`{id: 'a\'bb'})
> > 	MERGE (n2:`TEST`{id: 'bb \'s abc'})
> > 	MERGE (n1)-[:`ABC_I'S_a`]->(n2)
> > $$) as (a ag_catalog.agtype);
> > ```
> 
> I'm not sure I understand what you are asking. Also, keep in mind that you will likely need to backslash all non wrapping quote characters.

I mean, that query works in Neo4j, but I tried it in pg, it doesn't work. Can a label include quotes?
```
SELECT * from cypher('graph_store', $$
	MERGE (n1:`TEST`{id: 'a\'bb'})
	MERGE (n2:`TEST`{id: 'bb \'s abc'})
	MERGE (n1)-[:`ABC_IS\'_a`]->(n2)
$$) as (a agtype);
```

**Comment by noahxzhu** [comment]
The behavior in the python driver

NOT WORK
```
    prepared_statement = """
        MERGE (n1:`TEST` {id: 'a\'bb'})
        MERGE (n2:`TEST` {id: 'bb\'s abc'})
        MERGE (n1)-[:`ABC_IS_a`]->(n2)
    """

    ag.execCypher(
        prepared_statement,
    )

```

WORK
```
    prepared_statement = """
        MERGE (n1:`TEST` {id: "a'bb"})
        MERGE (n2:`TEST` {id: "bb's abc"})
        MERGE (n1)-[:`ABC_IS_a`]->(n2)
    """

    ag.execCypher(
        prepared_statement,
    )

```

NOT WORK
```
    prepared_statement = """
        MERGE (n1:`TEST` {id: 'a"bb'})
        MERGE (n2:`TEST` {id: 'bb"s abc'})
        MERGE (n1)-[:`ABC_IS_a`]->(n2)
    """

    ag.execCypher(
        prepared_statement,
    )

```

NOT WORK
```
    prepared_statement = """
        MERGE (n1:`TEST` {id: 'a\"bb'})
        MERGE (n2:`TEST` {id: 'bb\"s abc'})
        MERGE (n1)-[:`ABC_IS_a`]->(n2)
    """

    ag.execCypher(
        prepared_statement,
    )

```

**Comment by markgomer** [comment]
> I mean, that query works in Neo4j, but I tried it in pg, it doesn't work. Can a label include quotes?
> 
> ```
> SELECT * from cypher('graph_store', $$
> 	MERGE (n1:`TEST`{id: 'a\'bb'})
> 	MERGE (n2:`TEST`{id: 'bb \'s abc'})
> 	MERGE (n1)-[:`ABC_IS\'_a`]->(n2)
> $$) as (a agtype);
> ```

I tested this on AGE-viewer and it seems to be working... what is the error message you're getting?

**Comment by markgomer** [comment]
I had the same error showing up, but I worked around it by creating labels separately:

```sql
SELECT create_vlabel('graph_store', 'TEST');
SELECT create_elabel('graph_store', 'ABC_IS\'a');
```

Please check if this works for you

**Comment by noahxzhu** [comment]
> I had the same error showing up, but I worked around it by creating labels separately:
> 
> ```sql
> SELECT create_vlabel('graph_store', 'TEST');
> SELECT create_elabel('graph_store', 'ABC_IS\'a');
> ```
> 
> Please check if this works for you

unfortunately, it doesn't work on my side.

![CleanShot 2024-04-06 at 13 32 26@2x](https://github.com/apache/age/assets/8643866/0765b9c0-0526-47be-ac2e-91b5d90c6528)

**Comment by noahxzhu** [comment]
I'm testing some cases with the python driver, the behavior like below

# Case 1
```
def test(p: str):
    prepared_statement = """
        MERGE (n1:`TEST` {id: %s})
    """

    ag.execCypher(prepared_statement, params=(p,))
    ag.commit()


test("a's")
```
GOT
```
psycopg2.errors.SyntaxError: syntax error at or near "'s'"
LINE 1: SELECT * from cypher(NULL,NULL) as (v agtype);
```

# Case 2
```
def test(p: str):
    prepared_statement = """
        MERGE (n1:`TEST` {id: %s})
    """

    ag.execCypher(prepared_statement, params=(p,))
    ag.commit()


test('a"s')
```
GOT
```
psycopg2.errors.SyntaxError: unexpected character at or near "\"
LINE 1: SELECT * from cypher(NULL,NULL) as (v agtype);
```

# Case 3
I think we shouldn't add quotes for the params, right?

```
def test(p: str):
    prepared_statement = """
        MERGE (n1:`TEST` {id: '%s'})
    """

    ag.execCypher(prepared_statement, params=(p,))
    ag.commit()


test('a"s')

```
GOT
```
psycopg2.errors.SyntaxError: unexpected character at or near "\"
LINE 1: SELECT * from cypher(NULL,NULL) as (v agtype);
```

# Case 4
```
def test(p: str):
    prepared_statement = """
        MERGE (n1:`TEST` {id: '%s'})
    """

    ag.execCypher(prepared_statement, params=(p,))
    ag.commit()


test("a's")
```
GOT
```
psycopg2.errors.SyntaxError: syntax error at or near "a"
LINE 1: SELECT * from cypher(NULL,NULL) as (v agtype);
```

# Case 5
```
def test(p: str):
    prepared_statement = """
        MERGE (n1:`TEST` {id: "%s"})
    """

    ag.execCypher(prepared_statement, params=(p,))
    ag.commit()


test("a's")
```
GOT Succeed but the data like this
```
{"id": "'a''s'"}

![CleanShot 2024-04-06 at 18 11 00@2x](https://github.com/apache/age/assets/8643866/9c0e314a-20b9-45a5-bc23-773839ada0da)

```

# Case 6
```
def test(p: str):
    prepared_statement = """
        MERGE (n1:`TEST` {id: "%s"})
    """

    ag.execCypher(prepared_statement, params=(p,))
    ag.commit()


test('a"s')

GOT
```
psycopg2.errors.SyntaxError: syntax error at or near "s"
LINE 1: SELECT * from cypher(NULL,NULL) as (v agtype);
```

**Comment by noahxzhu** [comment]
Hi @mannas006
I just tried, it seems this doesn't for me
```
<class 'psycopg2.errors.SyntaxError'> syntax error at or near "'s better for technology companies to be run by product people'"
LINE 4:     MERGE (n2:`Entity` {id: 'It''s better for technology com...
```

**Comment by mannas006** [comment]
Hello @noahxzhu 
Thank you for informing me.

**Comment by Mocuto** [comment]
I'm posting to report that I'm experiencing this bug as well. I do not think that this is a question, as this bug only occurs while using the apache-age python driver. Nested quotation marks work fine when querying directly in psql. If I find a workaround I will report to this thread
