### ISSUE TITLE
How many vertex & edges can be added into a graph?

### ISSUE THREAD

**Issue by wen-bing** [apache/age#1748]
Hi 

When I try to use **load_labels_from_file** to import vertex from a csv file, I got an error said:

**pq: entry_id must be 1 .. 281474976710655**

the vertex's id in csv is a uint64_t integer value.

if I change the id to a uint32_t，then all vertex in csv can be loaded succedded.

Is this means the maximum vertex number is 281474976710655 ?

**Comment by rafsun42** [comment]
> Is this means the maximum vertex number is 281474976710655 ?


Yes, and that is the maximum for edges too. Though, this limitation applies per graph.

**Comment by wen-bing** [comment]
OK, 
Just worndering why not use 64 bits length

**Comment by rafsun42** [comment]
@wen-bing The actual ID is only 48 bit. Rest of the 16 bit is reserved for label ID to gain some performance benefits. Do you need to store more than 281474976710655 vertices?
