### ISSUE TITLE
Porting AGE to SQLite before MariaDB/MySQL

### ISSUE THREAD

**Issue by d4h0** [apache/age#1773]
Hi,

The [overview page](https://age.apache.org/overview/) states:

> Apache AGE® will be compatible with all relational databases in the future development, starting with MariaDB and MySQL.

I'm wondering if there is any chance that the team will port AGE first to SQLite instead.

The reason is, that SQLite is embeddable and there don't seem to be good options for embedded graph databases, yet (there are several good options for server-based graph databases, like the Postgres version of AGE).

As far as I know, SQLite is also by far the most used SQL database engine (measured by installations). SQLite is also popular on edge computing platforms (I believe), so this even might make AGE / graph databases usable there (which would be great).

**Comment by markgomer** [comment]
@aked21, @eyab, @jrgemignani, this is for your assessment.

**Comment by mingfang** [comment]
My vote is for `pglite` https://github.com/electric-sql/pglite
`pglite` brings Postgres to any WASM runtime include web browsers.
AGE on the edge/browser would be amazing.

**Comment by d4h0** [comment]
Wow, `pglite` looks pretty impressive. Unfortunately, it only seems to target JavaScript/TypeScript, so it isn't really comparable to SQLite (which probably has clients for most programming languages).

**Comment by ccapndave** [comment]
AGE running in SQLite would be an absolute game changer.

**Comment by marcobambini** [comment]
@d4h0 @ccapndave @mingfang @markgomer @cactis 

Hi, SQLite Cloud founder here.
We are interested in porting Apache ACE to SQLite for our soon to be announced sqlite.ai initiative.

**Comment by ccapndave** [comment]
It would be amazing.  We are developing a mobile Capacitor app with an embedded SQLite database.  The app stores a knowledge graph and we currently do everything in SQL using `vertex` and `edge` tables and it works, but its so unwieldy.  Having access to a real graph interface would make everything much more beautiful.

**Comment by markgomer** [comment]
> [@d4h0](https://github.com/d4h0) [@ccapndave](https://github.com/ccapndave) [@mingfang](https://github.com/mingfang) [@markgomer](https://github.com/markgomer) [@cactis](https://github.com/cactis)
> 
> Hi, SQLite Cloud founder here. We are interested in porting Apache ACE to SQLite for our soon to be announced sqlite.ai initiative.

@aked21

**Comment by jrgemignani** [comment]
@marcobambini @ccapndave @markgomer Our team, at the time, had looked into this and found it to not be feasible. Unfortunately, the website was never updated to reflect this.

The main problem here is that Apache AGE makes extensive use of specific PostgreSQL hooks and internals that are generally not available elsewhere. While the internal structures and functions used could be adjusted to work with SQLite, the necessary hooks to control the execution path are just not there. Please correct me if I'm wrong, though.

Apache AGE needs access to either the grammar or a hook immediately after the AST has been transformed, but before it is processed further. And this has to be for all commands, even non update commands. Without this, there isn't an easy way to implement openCypher and maintain a graph.

I know it isn't popular to hear this, but I don't want anyone going down this path unless they are fully aware of how it may end up.

**Comment by jrgemignani** [comment]
The website has been updated to remove the following to avoid confusion -

> Apache AGE® will be compatible with all relational databases in the future development, starting with MariaDB and MySQL.
