### ISSUE TITLE
Email Address in Readme file is not correct 

### ISSUE THREAD

**Issue by AneeqaCodes** [apache/age#1815]
users@age.apache.org this email address should be changed because when I send email it's replied back weirdly
![Screenshot_20240429-200058_1](https://github.com/apache/age/assets/87367157/69995de5-f0e5-414f-9725-367dbfd76b35)

**Comment by aked21** [comment]
Hi @AneeqaCodes,

I was able to send a message to users@age.apache.org

![image](https://github.com/apache/age/assets/76510292/7fb7d061-a035-4065-901a-0764d93e308c)

![image](https://github.com/apache/age/assets/76510292/d18fd35b-d293-4fd3-b63f-cc12aa1e986f)

Thanks

**Comment by dpdjvhxm** [comment]
@AneeqaCodes Hello

I was check this work well, try it again. 
If you still not work please share it more detail about it.
Also you can check it in [mailing list link](https://lists.apache.org/list.html?users@age.apache.org)

Thank you

**Comment by AneeqaCodes** [comment]
Well I'm closing this because I figured out that I received this reply earlier because I wasn't subscribed at the time. Later when I subscribed to the mailing list it worked perfectly.
