### ISSUE TITLE
Is that anyway how to package Apache AGE and  Apache AGE Viewer together docker image?

### ISSUE THREAD

**Issue by dpdjvhxm** [apache/age#1820]
Recently, I try to install Apache AGE and Viewer for try to understand these project well.
I found some difficult to install both if doesn't have any background about these. such as setup PostgreSQL and version issue.
However, I try install Apache AGE docker, It's really helpful and easy to setup, ready to go. 
Well still need some study for how to use docker but still much better than just install.
As I know Apache AGE Viewer is the visualization tool for Apache AGE, 
I suggest It would be good to have the Apache AGE +  Apache AGE Viewer docker image.
I'm not sure how it package or deploy about detail, I would like to share idea about this for future develop, 
Even its not that difficult I want to try it. 
If anyone know or idea let's share how to do.

**Comment by matt-gribben** [comment]
@dpdjvhxm You could fairly easily build a combined docker image? Make a dockerfile that pulls from pg16, installs age and installs age-viewer, and expose the relevant ports?
