### ISSUE TITLE
SQLSTATE 22003 when trying to insert a numeric value

### ISSUE THREAD

**Issue by JourneyToSilius** [apache/age#1836]
`ERROR: value "3082705652732369514543573" is out of range for type bigint (SQLSTATE 22003)`

I get this error when I try to insert a really large integer, it seems that age can't infer the type correctly, since this should be a numeric type in postgres. I have tried to type cast it to numeric ( this is on a prepared statement ) but it doesn't work. Is there any work around for this, or should this be stored as string ? Thanks

**Comment by jrgemignani** [comment]
@JourneyToSilius Could you provide the query and output?

**Comment by JourneyToSilius** [comment]
Query:
`SELECT * FROM cypher('test_graph', $$CREATE (a:simplestruct {largeint: $largeint, name: $name})$$, $1::agtype) AS (n agtype);`

AgeMap :  `{"largeint":3082705652732369514543573,"name":"test_struct"}`

executed as : 

```
	return func(ctx context.Context, conn postgres.DBTX) (pgconn.CommandTag, error) {
		return conn.Exec(ctx, wrapped, g.vertexData.AgeMap)
	}

```
result :

```
                Error:          Received unexpected error:
                                ERROR: value "3082705652732369514543573" is out of range for type bigint (SQLSTATE 22003)
                Test:           TestInferTypeInquery/Test_build_query_with_inferred_type
--- FAIL: TestInferTypeInquery (0.05s)
```

**Comment by jrgemignani** [comment]
@JourneyToSilius I will have to look at how that JSON is decoded. It might be that PG JSON doesn't support numeric. It might be that we added numeric and it needs a cast.

**Comment by JourneyToSilius** [comment]
I tried to type cast it to numeric but it doesn't work, or at least not the way I was doing it. Otherwise I'm not sure if JSONB actually supports numeric or it must be passed as string ... will wait for your response @jrgemignani  thanks

**Comment by jrgemignani** [comment]
@JourneyToSilius Try something like the following -

```
psql-16.1-5432-pgsql=# SELECT * FROM cypher('test', $$ CREATE (a:simplestruct {largeint: 123456789012345678901234567890::numeric, name: 'name'}) RETURN a $$) AS (a agtype);
                                                                       a

------------------------------------------------------------------------------------------------------------------------------------
-----------
 {"id": 844424930131969, "label": "simplestruct", "properties": {"name": "name", "largeint": 123456789012346000000000000000::numeric
}}::vertex
(1 row)

psql-16.1-5432-pgsql=#
```

**Comment by JourneyToSilius** [comment]
@jrgemignani thanks, that's what I tried before. If it works at the CLI it must be a string formatting problem then. I will try this out tomorrow and debug what's going on

**Comment by JourneyToSilius** [comment]
@jrgemignani : 

```
{"largeint":"3082705652732369514543573::numeric","name":"test_struct"}
--- PASS: TestInferTypeInquery (0.04s)
    --- PASS: TestInferTypeInquery/Test_build_query_with_inferred_type (0.01s)
PASS
```
works now. I was attempting to add the typecast in the actual prepared statement instead of in the JSONB, so it was my confusion. Thank you for your help

**Comment by jrgemignani** [comment]
@JourneyToSilius yw!

**Comment by JourneyToSilius** [comment]
I just realized I am inserting this : `{"largeint":"3082705652732369514543573::numeric","name":"test_struct"}` which means it's a string, and not a numeric type ? I'm I right ?
