### ISSUE TITLE
File \src\backend\commands\label_commands.c lines 270-282 repeated needlessly, only one copy of if block should remain

### ISSUE THREAD

**Issue by MironAtHome** [apache/age#1839]
**Describe the bug**
Branch release/PG14/1.5.0
File \src\backend\commands\label_commands.c
Lines 
![image](https://github.com/apache/age/assets/18360184/d2dbe820-f89f-4cb2-8227-72c7dea3d815)
repeat if block verbatim.
Should have only one copy of the same if block.

Code quality issue
Please verify other branches for same and fix if found

**Comment by markgomer** [comment]
@MironAtHome good find. Can you make a pull request fixing this?

**Comment by MironAtHome** [comment]
Branch or fork, please?

**Comment by MironAtHome** [comment]
Sounds like release branches are not to be modified.
Closed.
