### ISSUE TITLE
Please work around limitation of 100 or 50 fields for the function parameters such as agtype_build_map and internally invoked CREATE

### ISSUE THREAD

**Issue by MironAtHome** [apache/age#1840]
**Is your feature request related to a problem? Please describe.**
When working with data having vertice property count in excess of 100 Postgres functions exhibit build - in limit of 100 arguments.
Examples:
function agtype_build_map treats each parameter as separate, map field name and map field value, hence, it limits input to 50 fields / call. To scale number of fields it can handle one has to continuously invoke constructs such as 
agtype_add(
	            CypherInputParam_Var
	          , agtype_build_map(
    /* 54 */ field_name_54, field_value_54
    /* 55 */ field_name_55, field_value_55
....
similarly when CREATE invoked subsequently in the context of call to cypher function and CypherInputParam_Var as an input parameter to overcome per call limit of parameters/properties requires to initially create subset of 50 fields and subsequently call constructs such as 
CREATE (v:<vertice_name>
{... properties 1,2,3 ...
})
SET v += { properties 51... 100}
SET v += { properties 101... 150}
....
This limitation is grandfathered from functions servicing postgresql function check when using default build, as per [Appendix K. PostgreSQL Limits](https://www.postgresql.org/docs/current/limits.html#:~:text=100%20can%20be%20increased%20by,recompiling%20PostgreSQL%20query%20parameters%2065%2C535) document:

> 
> function arguments | 100 | can be increased by recompiling PostgreSQL
> 

However, I am not 100% convinced that custom compilation of Postgres is the right approach in this case.
In an ideal world it would be nice if Age used under the hood an limit compatible with limit of Age, which I believe is 65,535 properties per vertice ( please correct me if I am wrong ).

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jrgemignani** [comment]
@MironAtHome I can try to look into this tomorrow, time permitting. I recall something, somewhere, about this limit and creating a workaround. But, it's been a while.

**Comment by jrgemignani** [comment]
@MironAtHome It looks like `transform_cypher_map` function could use an update.

**Comment by jrgemignani** [comment]
@MironAtHome PR #1901 will fix this, it is currently in review.

**Comment by MironAtHome** [comment]
Just tried the fix.
Function agtype_build_map isn't fixed.
Getting message:
ERROR:  cannot pass more than 100 arguments to a function
LINE 1: CypherInputParam_Var := agtype_build_map( 
                                ^
So, I am assuming it's this function that is failing 100 argument check, and, if my understanding is correct, it is checked on entry, before function can start processing.
I am putting together an jsonb array hander.
Ideally we should also have something, where we put a record in, in the style of to_jsonb, to_agtype and get back map, with proper types. Not sure column naming rules fit property name of agtype, again, if you remember, recent ask regarding validation function, would come handy, ideally, we should extend something like a "default name normalizing" utility, with an option for the user to supply custom function, if they need some names to have special translation rules.
Array is simpler, I just fetch in name and value.

**Comment by jrgemignani** [comment]
@MironAtHome This is only fixed for agtype_build_map in the branches and not for SET. The releases don't have the fix. You would need to build from one of the branches.

**Comment by MironAtHome** [comment]
Took changes from branch PG16.
Will try to figure out what's wrong and get back.

**Comment by MironAtHome** [comment]
Checking regression test I am seeing the following. The call to function agtype_build_map seems to be missing:
![image](https://github.com/apache/age/assets/18360184/f989fa7a-1921-43a9-832c-cb6b3dc1bc0c)

**Comment by MironAtHome** [comment]
Have ran above scripts on the server with the build, which included fixes from branch PG16 and all completed successfully.
So, it does look like cypher parser is accepting 100+ parameters for various commands, however, the call to function agtype_biuld_map fails.
Looks like my original intent to add function call with jsonb block as input will be of use.
I may still need to check, if it is going to be array or set of json properties. The goal is to have something like
```
for m
in select * from t
loop
    agtype_map_input_parameter := jsonb_to_agtype_map(m);
    select into output_var
              t.a
   from cypher ('my_graph', $$
      CREATE (v:MyVertice { p1:$p1, .... })
   $$, agtype_map_input_parameter);
end loop
```
without having to split map building call into many - many "add_agtype(m, new_set)" calls.
The fix for CREATE call certainly helps greatly! Thank you.

**Comment by MironAtHome** [comment]
I have put together function
jsonb_to_agtype_map
that works for me. Will share it via same branch for PG14 and PG16 ports as before.
Please see if those have code that can be included or as an idea to improve upon.
Yeah, ideally, it would be nice to have one more function converting row to map, without having to use "to_jsonb" in between.

**Comment by jrgemignani** [comment]
> So, it does look like cypher parser is accepting 100+ parameters for various commands, however, the call to function agtype_biuld_map fails.

@MironAtHome Unfortunately, there is nothing that I can do to change PG's limit on function parameters. The only reason that I was able to "fix" it for some Cypher commands is because the transform logic allows us to code around it, because we can control how to build the function parameter list. But, we still have to look at each case in order to do that. Using a function directly will always run up against that limit.

**Comment by MironAtHome** [comment]
I hope this function jsonb_each_to_agtype_map_worker
here https://github.com/MironAtHome/age/blob/port/win32msvc/PG14/1.5.1/msvs32/xsrc/backend/utils/adt/agtype.c
is a good starting point to start adding functions that are able to add functionality, without running into function limitation

**Comment by MironAtHome** [comment]
Branch was updated with one more function
datum_to_agtype_map_worker
to perform similar work, except it now does not require intermediate step of converting query result into jsonb type variable and, on my mind, should be better with regards to type safety, since handling of variable type is now direct
column -> agtype
as opposed to field -> json key/value -> agtype.
I didn't have time beyond minimal test:

```
LOAD 'age';
SET search_path = ag_catalog, "$user", public;
DO
$RUN$
DECLARE
    AGMap_Var agtype;
BEGIN
	LOAD 'age';
    SET SEARCH_PATH TO ag_catalog;
    WITH t AS (
		SELECT 1 AS Col1, 'a' AS Col2
	)
    SELECT INTO AGMap_Var 
	       ag_catalog.datum_to_agtype_map(t)
	FROM t AS t;
	RAISE NOTICE 'AGMap_Var : %', AGMap_Var;
END;
$RUN$;
```

Please see if the two functions, datum_to_agtype_map_worker and jsonb_to_agtype_map can be promoted to age master.
