### ISSUE TITLE
OLTP vs OLAP Graph Querying

### ISSUE THREAD

**Issue by jnayak1** [apache/age#1874]
Searching the AGE documentation, I cannot find how the graph is structured internally. Is it structured similarly to Neo4j or something more like AWS Neptune? How is the data indexed?
The reason I ask these questions is because I'm curious as to whether AGE is applicable to OLTP or OLAP or both? AWS Neptune DB for instance is only for OLTP. Neo4j is capable of doing both.
OLTP queries for graph DBs are when you start at a node or a collection of nodes and traverse the graph.
OLAP on the other hand you are interested in answering questions where you need to scan the whole graph to find the answer.
My guess is that AGE is for OLTP queries but would like to know for sure.

**Comment by HackettJP** [comment]
Well i use it as OLAP , postgres OLTP to a dataware house postgres with fact tables with apache age at the back ,  how you view your data defines if it is OLTP or OLAP, defination of OLTP is now OLAP later. real time or not.

**Comment by jnayak1** [comment]
I guess what i am asking is, is AGE efficient for running OLAP queries?

**Comment by HackettJP** [comment]
True DB's performance all depends on the tin it sits on, I'm from an Postgres, Oracle 9iR1+, IBM-DB2, Abinitio , KDB+ background so money was not an issue. end of the day. 

you will just have to test it with the size of the data set.

There is indexing you have to build into the tables with apache age so you need to read the docs, configure hardware to suite.
I'm even starting to go down the route is model it in apache age, then hard coding it into C++, once i have query correct.

**Comment by shinhanbyeol** [comment]
I'm not a database expert, but
I think it might not be bad in oltp as we follow postgresql's transaction strategy, but I think graph database is more suited to olap than oltp.

and AGE is a schemaless structure
I thought that it might be possible to design more flexible when building a data mart or designing data like "star schema"

**Comment by MironAtHome** [comment]
> I'm even starting to go down the route is model it in apache age, then hard coding it into C++, once i have query correct.

Any link to an example would be appreciated ( if possible ) :)
