### ISSUE TITLE
unable to pull the docker image with 'latest' tag

### ISSUE THREAD

**Issue by byte-beaver** [apache/age#1882]
**Describe the bug**
when I tried the exact docker pull command from your portal, it fails saying "unable to find latest tag"

**How are you accessing AGE (Command line, driver, etc.)?**
- docker

**What data setup do we need to do?**
```NA
...
...
```

**What is the necessary configuration info needed?**
- NA

**What is the command that caused the error?**
```docker pull apache/age
```
```
ERROR:  something failed to execute
```

**Expected behavior**
docker image must be pulled using latest tag

**Environment (please complete the following information):**
- Version: [e.g. 0.4.0]

**Additional context**
To workaround, I had to use "dev_snapshot_master" tag

**Comment by torstenboettjer** [comment]
Having the same issue, looks like the link to the manifest file is broken.

**Comment by jrgemignani** [comment]
Which file?

**Comment by jrgemignani** [comment]
@byte-beaver dev_* are not supported. Only release_* are officially supported. Let me know where it states `latest` so that I can see about correcting it. We are still working on updating DH to more strictly follow Apache guidelines.

**Comment by jrgemignani** [comment]
I have put the `latest` tag back in place. However, per Apache guidelines, it points only to the latest Apache AGE release. For this tag, that is `PG16 1.5.0`.

**Comment by torstenboettjer** [comment]
Thanks, it's working now

**Comment by torstenboettjer** [comment]
@jrgemignani Not sure I get the question about the reference to `latest`. It is the default tag and added automatically, when no specific release is provided with the docker command (https://docs.docker.com/reference/cli/docker/image/tag/). Hence, using one of the following instructions resulted in the error:
- https://hub.docker.com/r/apache/age
- https://age.apache.org/age-manual/master/intro/setup.html
- https://age.apache.org/blog/2024-04-25-how-to-deploy-apache-age-docker-image-on-aws/

**Comment by jrgemignani** [comment]
@torstenboettjer I will see what can be done to update those links to be correct.
@markgomer Is this something you can do?

**Comment by jrgemignani** [comment]
@byte-beaver  @torstenboettjer I updated DockerHub to keep the **latest** tag. So, if this resolves the issue, please close the ticket :)
