### ISSUE TITLE
Performance issues with edge creation for larger dataset with 83K edges

### ISSUE THREAD

**Issue by dianaoa22** [apache/age#1925]
[Main.txt](https://github.com/user-attachments/files/15921715/Main.txt)
**Describe the bug**
I am creating 83K vertices and 83K edges by parsing a json file with JAVA. The vertex creation takes about 1 min however for edges it takes around 1hr+.

**How are you accessing AGE (Command line, driver, etc.)?**
- JDBC 

**What data setup do we need to do?**
```pgsql

Steps:

1. Attached program reads a JSON file, builds a graph structure in memory based on the JSON content, and then generates and executes Cypher queries to create this graph structure in a PostgreSQL database with the Apache AGE extension for graph processing.
2. Constructs the graph by recursively traversing the JSON structure and creating vertices and edges accordingly.
3. Code snippet attached, input json cannot be shared
4. Optimized with batch execution but no improvement seen, takes about 1 hr+ however the same in neo4j takes 14 mins.
[Main.txt](https://github.com/user-attachments/files/15900495/Main.txt)


**What is the necessary configuration info needed?**
- 

**What is the command that caused the error?**
```
```
```

```

**Expected behavior**
Execution time should be less atleast close to neo4j.

**Environment (please complete the following information):**
- JAVA 21 ,  postgres version PostgreSQL 16.2 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 8.5.0 20210514 (R
ed Hat 8.5.0-10), 64-bit


**Additional context**
Add any other context about the problem here.

**Comment by MironAtHome** [comment]
Do you have indexes on related fields used to create edge relationship?
I tried accessing linked file to look over but apparently couldn't get to the file.

**Comment by dianaoa22** [comment]
[Main.txt](https://github.com/user-attachments/files/15921717/Main.txt)

**Comment by dianaoa22** [comment]
[Code.txt](https://github.com/user-attachments/files/15922994/Code.txt)
Yes, I have created GIN index as the MATCH query used id inside the properties.
CREATE INDEX load_item_gin_idx ON ms_graph."Item" USING gin (properties);
CREATE INDEX

{
"id": 844424930132046,
"properties": {
"id": "3bd6197582434a01b340b889b357f3a4",
"label": "xxxx",
"properties": "{path: "/c/e", name: "test", s-id: "21977", description: "test", seattr: "2000", state: "enable", customer: "13"}"
}
}

**Comment by MironAtHome** [comment]
There are a few troubleshooting approaches I learned over the last week - end.
Please let me know if you are open to installing extensions, that can help to expose detailed wait information, regarding where query spends time, and turning on some of the troubleshooting options.
[This](https://github.com/postgrespro/sr_plan), [this](https://github.com/postgrespro/pg_query_state) and [this](https://github.com/postgrespro/pg_wait_sampling).
Feel free to add a comment here. Please don't just install these extensions, but rather see if those meet your Postgres version and see if ( entirely possible ) there are native, postgres itself, maintained extensions, or even built - in functions, that provide same level of troubleshooting.
This first step is just to ensure proper tooling is in place to attempt to identify slower parts of query prior attempting to fix.

**Comment by dianaoa22** [comment]
This would take some time, I will let you know once I have the data, thanks for the suggestions.

**Comment by MironAtHome** [comment]
Np at all.
One thing I was looking for is sample config.json file as it would help me to get to some test data faster.

**Comment by dianaoa22** [comment]
import json

# Original JSON data
data = {
    "root": {
        "child1": {
            "name": "test",
            "location": "test"
        },
        "child2": [
            {
                "child2-class": "classname",
                "child2-number": 1
            }
        ],
        "child3": [
            {
                "child4": [
                    {
                        "child4-pref": 1,
                        "child4-type": "type-schild5"
                    },
                    {
                        "child4-type": "type-schild5",
                        "child4-pref": 2
                    }
                ],
                "child5": [
                    {
                        "child5-number": 1,
                        "entryp": {
                            "econtrol": {
                                "ploc": "ploc-10001",
                                "state": "enable"
                            }
                        },
                        "inside": {
                            "mgmt": {
                                "state": "enable"
                            }
                        }
                    }
                ],
                "child3-type": "new-child53",
                "pref-number": 1
            },
            {
                "child3-type": "test-schild5-c",
                "pref-number": 2,
                "child4": [
                    {
                        "child4-pref": 1
                    },
                    {
                        "child4-pref": 2
                    }
                ],
                "child5": [
                    {
                        "entryp": {
                            "econtrol": {
                                "ploc": "ploc-10001",
                                "state": "enable"
                            }
                        },
                        "child5-number": 1,
                        "inside": {
                            "mgmt": {
                                "state": "enable"
                            }
                        }
                    }
                ]
            },
            {
                "child3-type": "new-child53",
                "pref-number": 3,
                "child4": [
                    {
                        "child4-type": "type-schild5",
                        "child4-pref": 1
                    },
                    {
                        "child4-type": "type-schild5",
                        "child4-pref": 2
                    }
                ],
                "child5": [
                    {
                        "inside": {
                            "mgmt": {
                                "state": "enable"
                            }
                        },
                        "child5-number": 1
                    }
                ]
            },
            {
                "child4": [
                    {
                        "child4-type": "type-schild5",
                        "child4-pref": 1
                    },
                    {
                        "child4-pref": 2,
                        "child4-type": "type-schild5"
                    }
                ],
                "child5": [
                    {
                        "inside": {
                            "mgmt": {
                                "state": "enable"
                            }
                        },
                        "child5-number": 1
                    }
                ],
                "child3-type": "new-child53",
                "pref-number": 4
            },
            {
                "child3-type": "new-child53",
                "pref-number": 5,
                "child4": [
                    {
                        "child4-pref": 1,
                        "child4-type": "type-schild5"
                    }
                ],
                "child5": [
                    {
                        "inside": {
                            "mgmt": {
                                "state": "enable"
                            },
                            "band": {
                                "band-no": "NQP-10001"
                            }
                        },
                        "child5-number": 1
                    }
                ]
            },
            {
                "child4": [
                    {
                        "child4-type": "type-schild5",
                        "child4-pref": 1
                    },
                    {
                        "child4-type": "type-schild5",
                        "child4-pref": 2
                    }
                ],
                "child5": [
                    {
                        "inside": {
                            "mgmt": {
                                "state": "enable"
                            }
                        },
                        "child5-number": 1,
                        "entryp": {
                            "econtrol": {
                                "state": "enable",
                                "ploc": "ploc-10001"
                            }
                        }
                    }
                ],
                "child3-type": "new-child53",
                "pref-number": 6
            },
            {
                "child3-type": "new-child53",
                "pref-number": 8,
                "child4": [
                    {
                        "child4-type": "type-schild5",
                        "child4-pref": 1
                    }
                ],
                "child5": [
                    {
                        "inside": {
                            "mgmt": {
                                "state": "enable"
                            },
                            "net": {
                                "test": "FRL-10001"
                            }
                        },
                        "child5-number": 1
                    }
                ]
            }
        ]
    }
}



def add_entries(data, num_entries):
    base_child3 = {
        "child3-type": "new-child53",
        "child4": [],
        "child5": [],
        "pref-number": None  # Will be set dynamically
    }

    base_child4 = {
        "child4-pref": None,  # Will be set dynamically
        "child4-type": "type-schild5"
    }

    base_child5 = {
        "child5-number": None,  # Will be set dynamically
        "entryp": {
            "econtrol": {
                "ploc": "ploc-10001",
                "state": "enable"
            }
        },
        "inside": {
            "mgmt": {
                "state": "enable"
            }
        }
    }

    # Generate new child3 entries
    new_child3s = []
    for i in range(1, num_entries + 1):
        child3 = base_child3.copy()
        child3['pref-number'] = i
        
        # Generate child4 entries for the child3
        child4_entries = []
        for j in range(1, 5):  # 4 child4 entries per child3 for example
            child4 = base_child4.copy()
            child4['child4-pref'] = j
            child4_entries.append(child4)
        child3['child4'] = child4_entries
        
        # Generate child5 entries for the child3
        child5_entries = []
        for j in range(1, 5):  # 4 child5 entries per child3 for example
            child5 = base_child5.copy()
            child5['child5-number'] = j
            child5_entries.append(child5)
        child3['child5'] = child5_entries
        
        new_child3s.append(child3)

    # Add new child3s to the data
    data['root']['child3'].extend(new_child3s)

# Specify the number of entries to add
num_entries = 100000

# Add the entries
add_entries(data, num_entries)

# Print the total number of child3 entries to confirm
print(f"Total child3 entries: {len(data['root']['child3'])}")

# Optional: Save the updated data to a file
with open('big_data.json', 'w') as file:
    json.dump(data, file, indent=4)

print("Data added successfully and saved to updated_data.json")

Run this python program to get a big data, I am unable to imprt the json due to size restriction of 25MB

**Comment by MironAtHome** [comment]
Thank you
