### ISSUE TITLE
How to extract values of a nested JSON and use in MATCH query, also can we index based on the properties of nested json?

### ISSUE THREAD

**Issue by dianaoa22** [apache/age#1931]
{
        "id": 844424930132109,
        "properties": {
            "id": "351",
            "label": "customer",
            "properties": "{path: \"/root/custA\", cust-name: \"DDDDD\", cust-id: \"51\", description: \"test\", time-out: \"2\", valid-state: \"enable\", role: \"46\"}"
        }
    }

Also, since the properties cannot have "-" all the properties for the node are added as a nested JSON.

**Comment by MironAtHome** [comment]
This worked for me:

```
select create_vlabel('test_graph', 'vertex1');
select create_vlabel('test_graph', 'customer');
select *
from cypher('test_graph', $$
	CREATE (v:customer
	{id:351, properties:{path:"/root/custA"
		               , `cust-name`: "DDDDD"
		               , `cust-id`: 51
		               , description: "test"
		               , `time-out`: 2
		               , `valid-state`: "enable"
		               , role: 46}})
   RETURN v
$$) as t(a agtype);
select *
from cypher('test_graph', $$
	MATCH (v:customer)
	   WHERE v.properties.role = 46
   RETURN v
$$) as t(a agtype);
```

Hope it helps.
