### ISSUE TITLE
Is data duplicated in parent and label/edge tables? What are the internals?

### ISSUE THREAD

**Issue by deniskilseev** [apache/age#1934]
When creating a node/edge in a graph it exists in both _ag_label_edge/vertex tables (parent tables) and appropriate label/edge-tables. But I couldn't find any triggers or materialized views, so it begs a question whether data is duplicated in base and class tables? Question rises when I started inserting data directly into underlying tables and can't comprehend how it ends up in parent table

Because if class-tables are just views of main tables, how indexes of label/edge tables are maintained?

**Comment by jrgemignani** [comment]
Nodes exist in their node label table. Edges exist in their edge label table. Each has a unique id, they are not duplicated. Now, can you create 2 or more nodes/edges with the same data but a different id, yes.

**Comment by deniskilseev** [comment]
Then what are parent tables? Are they like views combining all node label tables?
