### ISSUE TITLE
How to allow special characters in labels, backticks only works for property names.

### ISSUE THREAD

**Issue by dianaoa22** [apache/age#1952]
Cypher Query:

SELECT * FROM cypher('test_graph', $$
CREATE (:`universe:another-universe` {`instance-identifier`: '/universe:another-universe'}) $$)
as (n agtype);

nspdb=# SELECT * FROM cypher('test_graph', $$
nspdb$# CREATE (:`universe:another-universe` {`instance-identifier`: '/universe:another-universe'}) $$)
nspdb-# as (n agtype);
ERROR:  label name is invalid
LINE 1: SELECT * FROM cypher('test_graph', $$
                                           ^

Here I could pass the property name with backticks '`instance-identifier`' however for label it doesn't seem to allow. Somehow here backticks are hidden, by editing this you can get the actual query.

**Comment by jrgemignani** [comment]
@dianaoa22 We follow Neo4j's naming specifications - https://neo4j.com/docs/cypher-manual/current/syntax/naming/

**Comment by Tak1za** [comment]
> [@dianaoa22](https://github.com/dianaoa22) We follow Neo4j's naming specifications - https://neo4j.com/docs/cypher-manual/current/syntax/naming/

You say that AGE follows Neo4j's naming convention but label names with special characters is allowed with backticks which AGE doesn't allow.

```
SELECT * from cypher('varuntestdb', $$ return is_valid_label_name('`a b c`') $$) as (result agtype);
```
Returns false

```
SELECT * from cypher('varuntestdb', $$ return is_valid_label_name('`a.b.c`') $$) as (result agtype);
```
Returns false

Here's the same from Neo4j's documentation:

<img width="1045" height="635" alt="Image" src="https://github.com/user-attachments/assets/3f602aa0-db8c-4d30-bc73-b170f46a22f7" />

https://neo4j.com/docs/cypher-manual/current/syntax/naming/#symbolic-names-escaping-rules
