### ISSUE TITLE
List comprehension in WHERE clause results in server process segmentation fault

### ISSUE THREAD

**Issue by bravius** [apache/age#1955]
**Describe the bug**

List comprehension in a WHERE clause causes server process to terminate with "signal 11: Segmentation fault"

**How are you accessing AGE (Command line, driver, etc.)?**
- Node.js/DBeaver/psql

**What data setup do we need to do?**
```
SELECT * from cypher('graph', $$
    CREATE ({list:["one","two","three","four"]})
$$) as (a agtype);
```

**What is the necessary configuration info needed?**

- Age extension compiled from master

**What is the command that caused the error?**

```pgsql
SELECT * from cypher('graph', $$ 
    MATCH (n) WHERE size([e in n.list where e starts with "f"]) > 0 RETURN n
$$) as (result agtype);
```
Running the above example query results in server process segfault and lost driver connection.

**Expected behavior**

Completed query result.

**Environment (please complete the following information):**

- Age: master
- PGSQL version: 16
- OS: WSL Ubuntu "jammy"

**Additional context**

None.

**Comment by MuhammadTahaNaveed** [comment]
@bravius the bug is reproducible. I will try to come up with a fix as soon as possible, but it can take some time.
