### ISSUE TITLE
Reserved Keyword Handling: How to update a property which is a keyword.

### ISSUE THREAD

**Issue by dianaoa22** [apache/age#1988]
**Describe the bug**
Reserved Keyword Handling- Here below I have a graph test_graph with property match--keyword but I don't seem to have a way to update it.

nspdb=# SELECT *
nspdb-# FROM cypher('test_graph', $$
nspdb$#     MATCH (n:Person)
nspdb$#     RETURN n LIMIT 5
nspdb$# $$) AS (v agtype);
                                                                         v
----------------------------------------------------------------------------------------------------------------------------------------------------
 {"id": 3940649673949185, "label": "Person", "properties": {"id": 123, "city": "Lagos", "name": "Daniel", "match": "test", "title": "xyz"}}::vertex
(1 row)

nspdb=# SELECT * FROM cypher('test_graph', $$ MATCH (n:Person { id: 123 }) SET n.`match` = 'xyz'   $$) as (v agtype);
ERROR:  syntax error at or near "="
LINE 1: ...h', $$ MATCH (n:Person { id: 123 }) SET n.`match` = 'xyz'   ...
                                                             ^

**How are you accessing AGE (Command line, driver, etc.)?**
- [e.g. JDBC]

**What data setup do we need to do?**
```pgsql
...
SELECT * from cypher('my_graph_name', $$
  CREATE (a:Part {part_num: '123'}), 
         (b:Part {part_num: '345'}), 
         (c:Part {part_num: '456'}), 
         (d:Part {part_num: '789'})
$$) as (a agtype);
...
```

**What is the necessary configuration info needed?**
- [e.g. Installed PostGIS]

**What is the command that caused the error?**
```pgsql
SELECT * from cypher('my_graph_name', $$
  MATCH (a:Part {part_num: '123'}), (b:Part {part_num: '345'})
  CREATE (a)-[u:used_by { quantity: 1 }]->(b)
$$) as (a agtype);
```
```
ERROR:  something failed to execute
```

**Expected behavior**

**Environment (please complete the following information):**
- Version: [e.g. 0.4.0]

**Additional context**

**Comment by dianaoa22** [comment]
Tried with backticks too which doesnt seem to help.

**Comment by jrgemignani** [comment]
@dianaoa22 is this one or 2 issues?

**Comment by jrgemignani** [comment]
@dianaoa22 As for using keywords within queries, I don't think that you can atm. However, we could look into allowing it.

**Comment by dianaoa22** [comment]
@jrgemignani : It is one issue. Yes, I think there should be a way to allow it similar to neo4j https://neo4j.com/docs/cypher-manual/current/syntax/reserved/ where backticks encapsulation allows it.

**Comment by jrgemignani** [comment]
@dianaoa22 I'm looking into this to see if it is reasonably possible.

**Comment by jrgemignani** [comment]
@dianaoa22 PR #2005 addresses this and is currently in review.

**Comment by dianaoa22** [comment]
@jrgemignani Thanks for making an effort to fix this :)

**Comment by dianaoa22** [comment]
@jrgemignani -- When would the Dockerfile be updated with this build which has the fix so that I can verify the same? I see the last update is Build 2004 but the fix is in Build 2005. Please clarify.
