### ISSUE TITLE
Compilation error on MacOS 14.5

### ISSUE THREAD

**Issue by jccampagne** [apache/age#1991]
I tried to compile AGE on macOS 14.5 on a Mac M1.

I tried with Postgres installed with Brew, it didn't work.
So I tried with Postgres compiled from source code, it failed also (see below).
Postgres compiled and installed ok.

This is the output of the attempt to compile AGE:
```
 (git)-[master]-age % make PG_CONFIG=/Users/jc/bin/postgres/bin/pg_config   
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Werror=unguarded-availability-new -Wendif-labels -Wmissing-format-attribute -Wcast-function-type -Wformat-security -fno-strict-aliasing -fwrapv -Wno-unused-command-line-argument -Wno-compound-token-split-by-macro -Wno-deprecated-non-prototype -g -glldb -ggdb -Og -g3 -fno-omit-frame-pointer  -I.//src/include -I.//src/include/parser -I. -I./ -I/Users/jc/bin/postgres/include/server -I/Users/jc/bin/postgres/include/internal  -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk    -c -o src/backend/age.o src/backend/age.c
In file included from src/backend/age.c:20:
In file included from .//src/include/catalog/ag_catalog.h:25:
.//src/include/utils/agtype.h:458:25: error: unknown type name 'StringInfo'; did you mean 'fmStringInfo'?
int reserve_from_buffer(StringInfo buffer, int len);
                        ^~~~~~~~~~
                        fmStringInfo
/Users/jc/bin/postgres/include/server/fmgr.h:29:32: note: 'fmStringInfo' declared here
typedef struct StringInfoData *fmStringInfo;
                               ^
In file included from src/backend/age.c:20:
In file included from .//src/include/catalog/ag_catalog.h:25:
.//src/include/utils/agtype.h:459:25: error: unknown type name 'StringInfo'; did you mean 'fmStringInfo'?
short pad_buffer_to_int(StringInfo buffer);
                        ^~~~~~~~~~
                        fmStringInfo
...
```

If that's of any help, here the output of pg_config:
```
 (git)-[master]-age % /Users/jc/bin/postgres/bin/pg_config  
BINDIR = /Users/jc/bin/postgres/bin
DOCDIR = /Users/jc/bin/postgres/share/doc
HTMLDIR = /Users/jc/bin/postgres/share/doc
INCLUDEDIR = /Users/jc/bin/postgres/include
PKGINCLUDEDIR = /Users/jc/bin/postgres/include
INCLUDEDIR-SERVER = /Users/jc/bin/postgres/include/server
LIBDIR = /Users/jc/bin/postgres/lib
PKGLIBDIR = /Users/jc/bin/postgres/lib
LOCALEDIR = /Users/jc/bin/postgres/share/locale
MANDIR = /Users/jc/bin/postgres/share/man
SHAREDIR = /Users/jc/bin/postgres/share
SYSCONFDIR = /Users/jc/bin/postgres/etc
PGXS = /Users/jc/bin/postgres/lib/pgxs/src/makefiles/pgxs.mk
CONFIGURE =  '--enable-debug' '--enable-cassert' '--prefix=/Users/jc/bin/postgres/' 'CFLAGS=-glldb -ggdb -Og -g3 -fno-omit-frame-pointer'
CC = gcc
CPPFLAGS = -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk
CFLAGS = -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Werror=unguarded-availability-new -Wendif-labels -Wmissing-format-attribute -Wcast-function-type -Wformat-security -fno-strict-aliasing -fwrapv -Wno-unused-command-line-argument -Wno-compound-token-split-by-macro -Wno-deprecated-non-prototype -g -glldb -ggdb -Og -g3 -fno-omit-frame-pointer
CFLAGS_SL = 
LDFLAGS = -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk -Wl,-dead_strip_dylibs
LDFLAGS_EX = 
LDFLAGS_SL = 
LIBS = -lpgcommon -lpgport -lz -lreadline -lm 
VERSION = PostgreSQL 14.12
```

I tried a variety of configure options for postgres, but with no luck.

I looked the docs/video, etc:
* https://age.apache.org/age-manual/master/intro/setup.html
* https://www.youtube.com/watch?v=0-qMwpDh0CA

What am I missing?

**Comment by MironAtHome** [comment]
StringInfo is referenced in agetype.h here:
`#include "lib/stringinfo.h"`
This file should be located under
`/Users/jc/bin/postgres/include/server`
directory of the Postgres installation. Note, the complete path, is concatenated /Users/jc/bin/postgres/include/server +  lib/stringinfo.h

Definition of the StringInfo is line #44, it reads:
`typedef StringInfoData *StringInfo;`

If you could please download compressed archive of Postgres version 14 from its official distributor here:
https://www.enterprisedb.com/download-postgresql-binaries
uncompress it and point pg_config accordingly, it probably will fix the issue, unless something else is at play.

**Comment by jccampagne** [comment]
The files were all there.
It was actually a version mismatch.
I updated my postgres install to `16` and checked out the `PG16/v1.5.0-rc0` tag for Age.
Compiled Ok and test ran OK.

The documentation https://age.apache.org/getstarted/quickstart does mention Postgres version and to check them. A more precise note stating versions should be aligned would be a nice addition.

> Clone the  [github repository](https://github.com/apache/age)  or download the download an  [official release](https://github.com/apache/age/releases) . Run the pg_config utility and check the version of PostgreSQL. Currently, only PostgreSQL versions 11, 12, 13, 14, 15 & 16 are supported. If you have any other version of Postgres, you will need to install PostgreSQL version 11, 12, 13, 14, 15, or 16.

**Comment by MironAtHome** [comment]
> The files were all there. It was actually a version mismatch. I updated my postgres install to `16` and checked out the `PG16/v1.5.0-rc0` tag for Age. Compiled Ok and test ran OK.
> 
> The documentation https://age.apache.org/getstarted/quickstart does mention Postgres version and to check them. A more precise note stating versions should be aligned would be a nice addition.
> 
> > Clone the  [github repository](https://github.com/apache/age)  or download the download an  [official release](https://github.com/apache/age/releases) . Run the pg_config utility and check the version of PostgreSQL. Currently, only PostgreSQL versions 11, 12, 13, 14, 15 & 16 are supported. If you have any other version of Postgres, you will need to install PostgreSQL version 11, 12, 13, 14, 15, or 16.

Thanks @jccampagne 
It looks like ReadMe does suggest to install compatible version of Age for Postgres.
I have looked up branch PG16 and release/PG16/1.5.0 and all seem to have identical text with regards to same point.
If you have in mind precise wording you would feel a better expression, please share. I am sure Age team will give it proper consideration.
![image](https://github.com/user-attachments/assets/801afed1-7b91-4c59-af3a-746b94dc63d3)

Hope it helps.
