### ISSUE TITLE
Docker container - create_graph shows error message when using double quotes

### ISSUE THREAD

**Issue by MatheusFarias03** [apache/age#2003]
**Bug Description**
- The `crate_graph` function shows `column "<graph_name>" does not exist` error message when using double quotes to name the to be created graph.

**How are you accessing AGE (Command line, driver, etc.)?**
- A local application is accessing AGE through a docker container.

**What data setup do we need to do?**
 ```
docker pull apache/age

docker run \
    --name myPostgresDb  \
    -p 5455:5432 \
    -e POSTGRES_USER=postgresUser \
    -e POSTGRES_PASSWORD=postgresPW \
    -e POSTGRES_DB=postgresDB \
    -d \
    apache/age
```

**What is the necessary configuration info needed?**
```
docker exec -it myPostgresDb psql -U postgresUser -d postgresDB

LOAD 'age';

SET search_path = ag_catalog, "$user", public;
```

**What is the command that caused the error?**
```pgsql
SELECT * FROM create_graph("TEST_GRAPH");
```
```
ERROR:  column "TEST_GRAPH" does not exist
LINE 1: SELECT * FROM create_graph("TEST_GRAPH");
```

**Expected behavior**
```
NOTICE:  graph "TEST_GRAPH" has been created
```

**Environment (please complete the following information):**
- Version: latest version of apache/age container image

**Additional context**
What it does work is to use single quotes:

```pgsql
SELECT * FROM create_graph('TEST_GRAPH');
```
```
NOTICE:  graph "TEST_GRAPH" has been created
 create_graph
--------------

(1 row)

```

**Comment by shinyaaa** [comment]
PostgreSQL seems to recognize it as a table or column name if it is enclosed in double quotes.
https://www.postgresql.org/docs/current/sql-syntax-lexical.html#id-1.5.3.5.8.9.1
https://stackoverflow.com/questions/41396195/what-is-the-difference-between-single-quotes-and-double-quotes-in-postgresql

Therefore, I believe the above behavior is a specification, not a bug.
(I'm not very familiar with Apache AGE, so I could be wrong.)

**Comment by MuhammadTahaNaveed** [comment]
@MatheusFarias03  As @shinyaaa mentioned, PostgreSQL considers double-quoted strings as identifiers (tables or columns). This behavior is intentional and not a bug.
