### ISSUE TITLE
Unable to install AGE in Ubuntu 

### ISSUE THREAD

**Issue by lilei2894** [apache/age#2043]
**Describe the bug**
Hello, My environment is Ubuntu 24(VMware in Windows11) and PG16. I had download the AGE package [apache-age-1.5.0-src.tar.gz], than the next step when I install AGE, it reports error bwlow:
```
In file included from src/backend/age.c:20：
.//src/include/catalog/ag_catalog.h:23:10: fatal error: No such file or directory
  23 | #include"postgres.h"
     |          ^~~~~~~~~~~~
compilation terminated.
make: *** [<builtin>: src/backend/age.o] Error 1
```

**Expected behavior**
please fix it or tell me how to handle this
thanks

**Comment by lilei2894** [comment]
I search in Internet and find that when i install PG, shoose to "sudo apt install postgresql-server-dev-16", then its OK

**Comment by AndhikaWB** [comment]
Stumbled across this error too, I think this should be added to the docs, This dependency is currently not listed in the [quickstart](https://age.apache.org/getstarted/quickstart/) docs.

**Comment by jrgemignani** [comment]
@AndhikaWB @lilei2894 Feel free to submit a PR to add this to the documentation :)
