### ISSUE TITLE
AGE in Production

### ISSUE THREAD

**Issue by ishaan812** [apache/age#2047]
Hey guys, most of our setup is in AWS but on RDS, AGE is not supported yet. Wanted to hear more about how other folks are running AGE in production?

**Comment by MironAtHome** [comment]
VM deployed on prem.
Postgres + Age and one more extension deployed by product development and implementation team.
Postgres is enterprise approved and supported database, regardless, on prem or on cloud.
So, we were lucky to be supported by our enterprise policy.
