### ISSUE TITLE
Rust AGE driver

### ISSUE THREAD

**Issue by Dzordzu** [apache/age#207]
I've recently implemented a simple driver for rust, that allows to easily map types and execute cypher queries. Hope you'll enjoy my work.

https://github.com/Dzordzu/rust-apache-age
https://crates.io/crates/apache_age

I'm open to any kind of suggestions and contributions!

**Comment by JoshInnis** [comment]
@Dzordzu  this is awesome. Please consider making this a pull request. In the meantime, have you thought about situations where the user needs more than one field returned?

**Comment by Dzordzu** [comment]
@JoshInnis user can get more than one field from the query, BUT, he has to use map to gather results. I could not find any use case, where grouping within map could cause any problems.

@emotionbug There was a problem with types others than AgType. If one wants to use primitives, some kind of mapping between rust types and postgres type has to be performed. It CAN be implemented, but takes a lot of effort and time. The question is if that thing is worth it. In my opinion - no. One can just use AgType with proper generic type and get what they want. If I find some time I will create a PR, but currently I'm having (little to say) an interesting time. It may take, I think, up to month from now

**Comment by Dzordzu** [comment]
Also #145 should be closed?

**Comment by Dzordzu** [comment]
Closing in favour of #262
