### ISSUE TITLE
How to update index after importing from files

### ISSUE THREAD

**Issue by li2012xuan** [apache/age#2136]
I used the load_labels_from_file method to import node data, but the index is not updated automatically, and when I use the Where condition query, the data cannot be queried. 
What am I going to do？
Thanks.

**Comment by MuhammadTahaNaveed** [comment]
@li2012xuan You can use the [REINDEX](https://postgresql.org/docs/current/sql-reindex.html) command.

To reindex the whole graph/schema, use `REINDEX SCHEMA <graph_name>`, or if you want to reindex specific node/edge label, use `REINDEX TABLE <node/edge label>`.

**Comment by li2012xuan** [comment]
> @li2012xuan You can use the [REINDEX](https://postgresql.org/docs/current/sql-reindex.html) command.
> 
> To reindex the whole graph/schema, use `REINDEX SCHEMA <graph_name>`, or if you want to reindex specific node/edge label, use `REINDEX TABLE <node/edge label>`.
Thanks for your reply, that is worked for me.
But this command takes a long time, is there any other way to import large amounts of data and ensure index consistency?

**Comment by MuhammadTahaNaveed** [comment]
>this command takes a long time, is there any other way to import large amounts of data and ensure index consistency?

@lukehinds As of now, it isn't supported by age. However, PR #2117 addresses the issue of load_labels_from_file/load_edges_from_file not updating the indexes.

**Comment by li2012xuan** [comment]
> > this command takes a long time, is there any other way to import large amounts of data and ensure index consistency?
> 
> @li2012xuan As of now, it isn't supported by age. However, PR #2117 addresses the issue of load_labels_from_file/load_edges_from_file not updating the indexes.


Thanks, looking forward to the update.
