### ISSUE TITLE
Can't install or build from source for PostgreSQL 11 on Windows

### ISSUE THREAD

**Issue by ewrayjohnson** [apache/age#216]
I am posting this as a bug since I get errors.

First I tried **create extension age;** and got:
> ERROR:  could not open extension control file "C:/Program Files/PostgreSQL/11/share/extension/age.control": No such file or directory
> SQL state: 58P01

Since I could not find any windows binaries, I downloaded the source.
I first placed the following files in my C:\Program Files\PostgreSQL\11\share\extension folder:
> age.control
> age--1.0.0.sql

I again tried **create extension age;** and got:
> ERROR:  could not access file "$libdir/age": No such file or directory
> SQL state: 58P01

I then tried to run **make install** and got:
> Makefile:106: Files/PostgreSQL/11/lib/pgxs/src/makefiles/pgxs.mk: No such file or directory
> make: *** No rule to make target 'Files/PostgreSQL/11/lib/pgxs/src/makefiles/pgxs.mk'.  Stop.

I then downloaded PostgreSQL source and copied the contents of its **src** folder to my **C:\Program Files\PostgreSQL\11\lib\pgxs\src** folder and Then I tried again to run **make install** and got:
> C:/PROGRA~1/PostgreSQL/11/lib/pgxs/src/makefiles/pgxs.mk:226: /src/Makefile.shlib: No such file or directory
> make: *** No rule to make target '/src/Makefile.shlib'.  Stop.

I can't find any good instructions on how to get things installed and running on Windows.  

**HELP**

**Comment by muhammadshoaib** [comment]
Currently AGE supports Linux compilation. If you are on windows machine
trying docker would be quit useful in your case.

**Comment by muhammadshoaib** [comment]
We also have tested the AGE version with WSL you can also compile using WSL on windows.

**Comment by muhammadshoaib** [comment]
This issue has been considered resolved.
