### ISSUE TITLE
When will support pg13？

### ISSUE THREAD

**Issue by nieyankai** [apache/age#225]
You said that you will support pg13 in 2022 Q1，but now the Q1 is over and I can't see the support.

**Comment by aked21** [comment]
I know the support for PostgreSQL 12 is currently being worked on and will soon be available. I suppose the support for PostgreSQL 13 will follow soon after and hope won't take much time. Actually I would like see more involvement from the PostgreSQL community to the AGE project.

**Comment by jrgemignani** [comment]
Everyone in the software industry understands that dates are merely targets. We try to give our best estimates for when specific milestones will be met, but some functionality ends up being more difficult than expected. That pushes other items further out.

While we would like to have PG 13 support now, we are still working on finalizing some of the more complex implementations of the openCypher specification. Additionally, we are working on bridging to PG12 which is necessary to PG13.  Our roadmap, and priorities, without dates imposed, has always been the following.

1. Complete openCypher language specification.
2. Fix issues (performance and bugs) to #1 as they arise.
3. Create a roadmap for bringing in PG12.
4. Implement AGE in PG12.
5. Implement AGE in other, higher, PG versions.

We are finishing item #1. 
Item #2 is always ongoing. 
Items #3 and #4 are in progress. Although, #4 is just starting. 
Item #5 can't start until item #4 is complete, or nearly complete.

Most of our resources are currently on items #1 and #2.

**Comment by nieyankai** [comment]
OK, I got it

**Comment by HiperMaximus** [comment]
very excited about AGE, would be pretty interesting if you could share more about the development process, great work!

**Comment by muhammadshoaib** [comment]
We are currently performing final testing for PG12. It will be available very soon.

**Comment by HiperMaximus** [comment]
Pretty exciting news!

**Comment by clayrisser** [comment]
Awesome, @jrgemignani just following up, since it's two weeks since your message. Is there an alpha release of apache age for postgres 12?

**Comment by jrgemignani** [comment]
Yes -

https://github.com/apache/age/tree/AGE_PG12.1.0_ALPHA

**Comment by elvizlai** [comment]
any progress about pg13?

**Comment by jrgemignani** [comment]
Yes. An initial release will be available by the end of January 2023.

**Comment by beeman** [comment]
> Yes. An initial release will be available by the end of January 2023.

I would love to give this a spin when it becomes available!

**Comment by jrgemignani** [comment]
It is available in the **alpha/PG13** branch to pull down and build. We are currently working on getting an official release ready.
