### ISSUE TITLE
cluster & distributed support

### ISSUE THREAD

**Issue by kcmvp** [apache/age#237]
Does Apache Age support cluster & distribution ?

**Comment by Huzaiifaaaa** [comment]
Yes, Apache AGE do support cluster & distribution. It provides efficient data exchange between node & cluster via Arrow Flight Protocol, also it supports distributed query processing for parallel execution of queries.

**Comment by mahinash26** [comment]
Yes, Apache AGE does support clustering and distribution of data. Apache AGE is built on top of the Apache Hadoop ecosystem, which provides support for distributed computing and storage. AGE uses Hadoop Distributed File System (HDFS) to store graph data across a cluster of machines, and Apache YARN for resource management and scheduling.

AGE also provides support for Apache Spark, a powerful distributed computing framework that can be used for processing large-scale graph data. By leveraging the distributed processing power of Spark, AGE can efficiently process and analyze large graphs in parallel across a cluster of machines.

**Comment by jrgemignani** [comment]
@mahinash26 Could you please explain how you came to this conclusion

> Yes, Apache AGE does support clustering and distribution of data. Apache AGE is built on top of the Apache Hadoop ecosystem,

**Comment by mahinash26** [comment]
> @mahinash26 Could you please explain how you came to these conclusions
> 
> > Yes, Apache AGE does support clustering and distribution of data. Apache AGE is built on top of the Apache Hadoop ecosystem,
> 
> > AGE uses Hadoop Distributed File System (HDFS) to store graph data across a cluster of machines, and Apache YARN for resource management and scheduling.

I actually read a few articles and blogs regarding the underlying architecture of the Apache age. And they defined that Apache age architecture is based on Hadoop to enable parallel processing of graph data.

**Comment by jrgemignani** [comment]
@mahinash26 Could you link those article and blogs?

**Comment by mahinash26** [comment]
> @mahinash26 Could you link those article and blogs?

https://dev.to/awaisbinadil/apache-age-and-machine-learning-a-powerful-combination-319n

**Comment by jrgemignani** [comment]
@mahinash26 Thank you for bringing this to our attention.

**Comment by jrgemignani** [comment]
For anyone coming across this thread, Apache AGE is *not* built on Hadoop. AGE is an extension to PostgreSQL using PostgreSQL internals and techniques.
