### ISSUE TITLE
Failed to open countries.csv

### ISSUE THREAD

**Issue by allegrojm** [apache/age#242]
using postgresql11 and age trying the demo and following the docs but can't open the countries.csv. i.e. SELECT load_labels_from_file always returns 'error: failed to open ' the file. Tried absolute path name as in '/home/...' as well as relative as per the docs. Any ideas? Roadblocked with evaluating this project until I get past this.  Hard to debug. I'm using Ubuntu 22.04, postgres11 and AGE 1.0.0,
thanks for any help.

**Comment by JoshInnis** [comment]
Hi, is your session and server on the same machine? If not, which machine is the file on? Also, does your login have permissions to access the file? Absolute file paths might require permissions you account doesn't have.

**Comment by muhammadshoaib** [comment]
You can copy the file to your home directory before running the demo script. You can than use the absolute path to be sure that you are pointing out to the correct directory.
