### ISSUE TITLE
Research for integration of Python driver with networkx

### ISSUE THREAD

**Issue by muhammadshoaib** [apache/age#285]
networkx is one of well-known library for working with graphs in python. Our goal is to integrate networkx with AGE and bridge both open source tool. This will provide more liberty to developers working with Python and AGE to perform in-depth graph\ analytics.

**Comment by jasperblues** [comment]
This is cool @muhammadshoaib . . . I'm doing the same with [drivine.org](drivine.org) in NodeJS. You can then use this lib to build a higher level of abstraction, eg a GraphQL library that leverages the GraphDB to reduce boilerplate (generate all the CRUD), for example.

**Comment by KamleshKumar427** [comment]
Is this feature implemented or is currently under process?
