### ISSUE TITLE
Documentation link in README is wrong and returns 404

### ISSUE THREAD

**Issue by sidcool1234** [apache/age#286]
**Describe the bug**
Documentation link in README is wrong and returns 404.  It should be https://age.apache.org/age-manual/master/index.html instead of https://age.apache.org/docs/master/index.html.

**Expected behavior**
Link should not throw 404.

**Comment by pdpotter** [comment]
Thanks for reporting this issue. All documentation links should be updated now.

**Comment by Dzordzu** [comment]
Closed?
