### ISSUE TITLE
can we install Apache AGE ins windows?

### ISSUE THREAD

**Issue by AnwarsaeedDMU** [apache/age#287]
I read the documentation of apache age but I don't found that how to install it on windows 10. any idea about it and how to use the existing Rdb tables with AGE extension? any related articles or tutorials to it?

**Comment by MatheusFarias03** [comment]
You can install it using WSL (Windows Subsystem for Linux). I believe it comes pre-installed with Windows 10, but you can also install the Windows Terminal app on microsoft store, which gives you options to use PowerShell, Ubuntu, Command Prompt, etc. Then open Ubuntu there and install both PostgreSQL and AGE under the `$HOME` directory : use the command `cd ~` to go there. And PostgreSQL must be version 11 or the ALPHA version of 12.

**Comment by humzakt** [comment]
I recently published a blog regarding this. You can follow it step by step https://dev.to/humzakt/getting-started-with-age-and-postgresql-setting-up-and-modifying-the-source-code-49n3

**Comment by AhmedMo0** [comment]
Yes, you can by using WSL. Follow this [blog](https://dev.to/omarsaad/step-by-step-guide-to-install-postgresql-apache-age-on-windows-28gf) will help you

**Comment by pawankukreja01** [comment]
Yes, you can install apache age and PostgeSQL on WSL2 on windows. 
Here is complete guide to install, there are multiple parts of this manual to install PosgreSQL, Apache age and Age viewer: https://dev.to/vkt1271/complete-beginner-guide-to-install-postgresql-apache-age-on-windows-10-pro-with-wsl2-part-1-fco

**Comment by AadilBashir489** [comment]
You can install apache age on windows. Follow the link below for further guidance. 
[Link](https://dev.to/pawnsapprentice/ultimate-guide-to-installing-postgresql-apache-age-on-windows-10-with-wsl2-437m)

**Comment by ShanGor** [comment]
There is a binary ship with PG17, if you want to compile it by yourself, you can ref to it too.
https://github.com/ShanGor/apache-age-windows

Release files: https://github.com/ShanGor/apache-age-windows/releases/tag/PG17%2Fv1.5.0-rc0
