### ISSUE TITLE
Setup Development Environment

### ISSUE THREAD

**Issue by jrgemignani** [apache/age#291]
Sorry, I left out the description. But, it appears that everyone was able to successfully complete the task.

Set up a development environment for configuring, building, and compiling, PG and AGE. This means having some IDE, I use the gnu suite and a debugger.

**Comment by skkk98** [comment]
Completed Setup (Installed Ubuntu on Virtualbox)

**Comment by PragyanD** [comment]
Completed Setup

**Comment by marodins** [comment]
setup complete

**Comment by rafsun-yu** [comment]
Could you please elaborate what needs to be done for this task? So far, I completed the tasks 304 and 305 on my ubuntu machine.

**Comment by jrgemignani** [comment]
If you have done 293 & 294 then this task is completed. It was basically setting up a development environment, which you obviously have done.
