### ISSUE TITLE
Install the PostgreSQL (11.5 & 12.10) development source code into your development environment.

### ISSUE THREAD

**Issue by jrgemignani** [apache/age#293]
Install the PostgreSQL (11.5 & 12.10) development source code into your development environment. You will not be installing it to automatically run under root at system start up. Rather, you will be installing it such that you can bring it up (and down) locally under a regular development account.

**Comment by PragyanD** [comment]
Installed PostgreSQL under a directory on my Linux VM.

**Comment by skkk98** [comment]
I have PostgreSQL 11.17  installed. Is that fine? Or should I remove it and Install 11.5? Is it okay if both installed pg versions are under the folder /usr/lib/postgresql ?

**Comment by jrgemignani** [comment]
You can have multiple development versions of PG installed in your development directories. However, don't install them to run under root or under the system. You want to bring them up and down under your development account.

**Comment by susano0** [comment]
Is it okay to have PG 11.17 and 12.12 instead of 11.5 and 12.10? I couldn't find any way of installing specific "minor" versions of PG.

**Comment by jrgemignani** [comment]
You will need to download the PostgreSQL "source" and build it in your development environment. Go to the following link and on the left you'll see Source, under Downloads -

https://www.postgresql.org/download/

Btw, this also means that you will need to have gcc and gdb installed.

**Comment by susano0** [comment]
Getting error while running make install with PG 12.10

![Image](https://user-images.githubusercontent.com/25738879/190077506-f074d653-9801-4159-a467-6b4eb09b16e9.png)

**Comment by jrgemignani** [comment]
I don't know if these issues cause that error. 

- You shouldn't be using sudo for any of this. 
- You will need to download the source code for PG 11.5 & 12.10 and create directories for each PG version, under a development account. Not a root account. Root isn't necessary for any of this.
- You will need to follow the build instructions - which means using 'configure' - to build that PG version. See PG's INSTALL readme.
- You will need to then build the AGE extension into each specific version of PG.

**Comment by susano0** [comment]
PG 11.5 and PG12.10 installations were successful in 2 separate directories (tested them as well).  When I build the AGE extension with PG12, it throws this error (ag_graph.c -> insert_graph(args) -> error: void value not ignored), although with PG11 I was able to build and run the regression tests successfully.

**Comment by jrgemignani** [comment]
Are you building the correct AGE branch for PG12?

**Comment by susano0** [comment]
Yes, I used "AGE PG12.1.0 ALPHA" for PG12.

**Comment by susano0** [comment]
Do we need PG12.10 or PG12.1 (inferring from the title of the branch)? I will try with PG12.1.

**Comment by jrgemignani** [comment]
Is that the only error? What OS?

**Comment by jrgemignani** [comment]
Actually, that error shows that you aren't actually building the extension from the AGE ALPHA PG12 release.

**Comment by jrgemignani** [comment]
Actually, that error shows that you aren't actually building the extension from the AGE ALPHA PG12 release.

**Comment by susano0** [comment]
I am using Ubuntu 22.04 LTS. 

![Image](https://user-images.githubusercontent.com/25738879/190254509-5c36fcb4-1839-4b6e-9643-33e43df5f9c7.png)

**Comment by susano0** [comment]
Yes, thank you you were right, resolved. :)

**Comment by skkk98** [comment]
Where should these pg installations be? I created a folder(pgsql11) under documents and installed(make --prefix install) it in this created folder. But it doesn't seem to work. Should it be under /usr/local/ or something?

**Comment by jrgemignani** [comment]
Mine are under my development home directory, as an example.

**Comment by skkk98** [comment]
I currently have it in home/usr/pgsql-11.5, but when I change the usr(su - postgres) to test psql, I cannot find this. So should I move this installations inside the root(somewhere like /usr)

**Comment by skkk98** [comment]
I keep getting this error that postgres is not in sudoers file. This incident will be reported. Any idea what to do?

![Image](https://user-images.githubusercontent.com/25060717/190307652-19284b1e-c6d1-48a9-b252-06a1d9b2f879.jpg)

**Comment by skkk98** [comment]
I tried installing again everything from start. Now I am getting this error, Don't know what to do.

![Image](https://user-images.githubusercontent.com/25060717/190484816-8b308a47-525f-489a-b8ab-3c5c216416eb.jpg)

**Comment by jrgemignani** [comment]
There is no need to install or run PostgreSQL under root, so no need to have it in the sudoers file. You should install and run it directly under your development account. You will need to run the executable located in that developer account in the bin directory in the locally installed PostgreSQL directory.

**Comment by jrgemignani** [comment]
I have updated the above comment to make it more helpful.

Additionally, all 3 of you are encouraged to help each other out.

**Comment by marodins** [comment]
install completed pg 11.5 and 12.10

**Comment by rafsun-yu** [comment]
Installed pg 11.5 and 12.10.
