### ISSUE TITLE
Build the appropriate AGE build into both PostgreSQL development versions.

### ISSUE THREAD

**Issue by jrgemignani** [apache/age#294]
Build, make and install, the appropriate AGE build into both versions of PostgreSQL. Run 'make installcheck' for each version and put the results here.

**Comment by susano0** [comment]
PG 11.5 

![Image](https://user-images.githubusercontent.com/25738879/190077260-4da18d00-9602-4a3f-8af0-78fdbd4a76f0.png)

**Comment by susano0** [comment]
PG12.10

![Image](https://user-images.githubusercontent.com/25738879/190256596-14e0abad-0a10-4ddd-b738-ccb465065d47.png)

**Comment by PragyanD** [comment]
Installed Apache AGE into both but one test is failing. Will try solving the issue
![PG11 Test](https://user-images.githubusercontent.com/36222744/190946956-ecf9028f-4b30-4705-8808-b913e39f996b.jpg)
![PG12 Test](https://user-images.githubusercontent.com/36222744/190946967-9b4b5c58-a01c-4974-82a3-3ee84092ec53.jpg)

**Comment by skkk98** [comment]
Installed apache AGE into both pg version but `test expr` is failing in both versions.



![Image](https://user-images.githubusercontent.com/25060717/191209158-b044ed3a-3359-4bae-9658-66a5d50ff98a.png)




![Image](https://user-images.githubusercontent.com/25060717/191209199-0a0b9dc4-45f4-48ff-970f-605caba3b9b2.png)

**Comment by jrgemignani** [comment]
What OS distro and version are both of you using?

**Comment by jrgemignani** [comment]
You can use the following command to see what is different. You will need to execute it from the root of the distro - 

`diff regress/expected/expr.out regress/results/expr.out`

If the diff isn't large, you can paste the results in here. Or, if there appears to be a 'theme' to the diff, then just post an example.

**Comment by marodins** [comment]
![Image](https://user-images.githubusercontent.com/67288224/192215681-5a43c7f5-f5b8-40a6-9fc2-ca3cbc2c991f.png)
![Image](https://user-images.githubusercontent.com/67288224/192215682-193b6292-8d77-4862-8239-176a7444e3a5.png)

**Comment by rafsun-yu** [comment]
11.5


![Image](https://user-images.githubusercontent.com/86813745/192665987-cf939df0-1838-4e61-b09e-f5ddc2130280.png)

12.10



![Image](https://user-images.githubusercontent.com/86813745/192666870-25af4a00-5de9-44b1-b471-151b9e41d17e.png)
