### ISSUE TITLE
ERROR: too few arguments to function call(queryEnv, dest, completionTag) expected 8, have 7 at line src/backend/catalog/ag_catalog.c:98:68

### ISSUE THREAD

**Issue by mhmdawnallah** [apache/age#300]
I'm getting the following errors when I run:
`make install`

<img width="1404" alt="Screen Shot 2022-09-15 at 1 44 07 PM" src="https://user-images.githubusercontent.com/69568555/190396014-701adf4b-b67c-46b2-9e8b-490c8e0801cf.png">

**Comment by JoshInnis** [comment]
What version of Postgres and what branch of AGE are you using?

**Comment by mhmdawnallah** [comment]
I'm currently using **PostgreSQL 14 version** and **master branch**

**Comment by muhammadshoaib** [comment]
Currently we only support PG11 and PG12. We are working on other versions
as well.

**Comment by mhmdawnallah** [comment]
Okay, I've just migrated down to an older version of PostgreSQL server in my case 11.17 and still give me the same error stated above
<img width="399" alt="Screen Shot 2022-09-15 at 7 42 25 PM" src="https://user-images.githubusercontent.com/69568555/190474033-f33fe966-7445-4727-9627-64a22cad57cf.png">

**Comment by mhmdawnallah** [comment]
I'm currently using Mac arm 64 I don't know if it is applicable to run the project ?

**Comment by jrgemignani** [comment]
Which branch are you using for PG11? For PG11 it needs to be the **master** branch. Whereas, for PG12 needs to be the **ALPHA** branch.

**Comment by mhmdawnallah** [comment]
I'm using the master branch for my PostgreSQL version 11.17

**Comment by jrgemignani** [comment]
From the error message, you are building AGE against the incorrect version of PostgreSQL. The message states that the function prototype is expecting 8, but got only 7 parameters. That means that you are building AGE for PG11 against PG12. You probably still have the build pointing to the PG12 source.

**Comment by sep2** [comment]
For anyone interested, I had luck cross-building a linux/arm64 version of apache/age on linux/amd64. It should be possible doing so in a macbook with arm-based m1/m2 chips.

I'am following instructions here: https://docs.docker.com/build/building/multi-platform/

**Comment by dgroomes** [comment]
I had the same compilation error described by the original issue, I am using macOS, and thanks to jrgemignani's comment about the C function signature difference between Postgres 11 vs Postgres 12, I was able to solve my problem.

## Problem

I unknowingly had a HomeBrew-installed Postgres 14 on my PATH. When I execute `make install` in the Apache AGE project, the compiler would find Postgres 14 code. Postgres 14 is not supported.


## Workaround

Follow the helpful installation instructions in the Apache AGE README that guide you to point to a specific Postgres installation location when you run `make`. Specifically, run your `make install` command like this:

```shell
make PG_CONFIG=/path/to/postgres/bin/pg_config install
```

In my case, I had built and installed Postgres 11 from source, which installed to `/usr/local/pgsql`. So, I used

```shell
make PG_CONFIG=/usr/local/pgsql/bin/pg_config install
```

And the project compiled. ✅ .

---

I suggest anyone having issues share the output of their `pg_config` command. For me, this command made it clear that my environment was still pointing to Postgres 14 (despite my best efforts to install Postgres 11).
