### ISSUE TITLE
Build and install the appropriate AGE build into both PostgreSQL development versions.

### ISSUE THREAD

**Issue by jrgemignani** [apache/age#305]

**Comment by susano0** [comment]
PG11.17

![Image](https://user-images.githubusercontent.com/25738879/191394357-0c601fa6-e2a8-4e71-90be-2f4c79cacad5.png)

**Comment by susano0** [comment]
PG 12.12

![Image](https://user-images.githubusercontent.com/25738879/191394384-3c200be6-c927-4176-b905-50dfde1b6cf5.png)

**Comment by PragyanD** [comment]
Installed, the same test is failing. Will fix these issues
![newAGEinstall](https://user-images.githubusercontent.com/36222744/191404306-d6aa2869-74e0-407c-8de1-f6f75aa9112e.jpg)

**Comment by jrgemignani** [comment]
We definitely need to correct the issue with the expr regression test.

**Comment by skkk98** [comment]
Installed AGE extension into both PG(11.17 & 12.12) versions. Apparently all tests are passed. But my pg11.5 & 12.10 had `test expr` failed. weird because I didn't change anything in between.



![Image](https://user-images.githubusercontent.com/25060717/191676398-fea80881-e804-4069-aedb-671c1c63d785.png)




![Image](https://user-images.githubusercontent.com/25060717/191676426-ac218501-6fd0-4811-8186-e3ff0e75be65.png)

**Comment by rafsun-yu** [comment]
Installed AGE into PG11.17. Installcheck passes all 20 tests.

However, for PG12.12, installcheck gives the following error. What I did was checked into branch AGE_PG12.1.0_ALPHA, and run make install with appropriate PG_CONFIG. 
```
$ make PG_CONFIG=/home/rafsun82/postgresql-src/postgresql-12.12/new_build_dir/bin/pg_config installcheck
/home/rafsun82/postgresql-src/postgresql-12.12/new_build_dir/lib/pgxs/src/makefiles/../../src/test/regress/pg_regress --inputdir=./ --bindir='/home/rafsun82/postgresql-src/postgresql-12.12/new_build_dir/bin'    --load-extension=age --inputdir=.//regress --outputdir=.//regress --temp-instance=.//regress/instance --port=61958 --encoding=UTF-8 --dbname=contrib_regression scan graphid agtype catalog cypher expr cypher_create cypher_match cypher_unwind cypher_set cypher_remove cypher_delete cypher_with cypher_vle cypher_union cypher_merge age_load index drop
============== removing existing temp instance        ==============
============== creating temporary instance            ==============
============== initializing database system           ==============
============== starting postmaster                    ==============
running on port 61958 with PID 418801
============== creating database "contrib_regression" ==============
CREATE DATABASE
ALTER DATABASE
============== installing age                         ==============
ERROR:  incompatible library "/home/rafsun82/postgresql-src/postgresql-12.12/new_build_dir/lib/age.so": version mismatch
DETAIL:  Server is version 12, library is version 11.
command failed: "/home/rafsun82/postgresql-src/postgresql-12.12/new_build_dir/bin/psql" -X -c "CREATE EXTENSION IF NOT EXISTS \"age\"" "contrib_regression"
make: *** [/home/rafsun82/postgresql-src/postgresql-12.12/new_build_dir/lib/pgxs/src/makefiles/pgxs.mk:420: installcheck] Error 2 
```

**Comment by skkk98** [comment]
I'm not sure whether it'll help, but try running `make clean` and run the `installcheck` command again.

If it still doesn't work, try testing pg12.12 by running `bin/psql` in the postgresql-12.12 folder.
it says version 11 is being used, so you can also try reinstalling pg12.12.

**Comment by JoshInnis** [comment]
Did you switch to the Postgres 12 supported branch of AGE, `AGE_PG12.1.0_ALPHA`? Also you should run make clean when switching between versions.

**Comment by marodins** [comment]
PG 12.12


![Image](https://user-images.githubusercontent.com/67288224/192221464-bc42b1eb-3828-4615-bb8e-76034cca268c.png)

PG 11.17


![Image](https://user-images.githubusercontent.com/67288224/192221548-01137aa4-aa61-4ca9-af87-b6129e69c1d9.png)

**Comment by rafsun-yu** [comment]
@JoshInnis @skkk98  `make clean` solved the issue. Thanks.

PG 11.17
![Image](https://user-images.githubusercontent.com/86813745/192357156-a2625e8f-97d0-4acb-ad07-07b73f7e5a4b.png)

PG 12.12
![Image](https://user-images.githubusercontent.com/86813745/192357377-79fe87ef-b666-44dd-bec0-eab74fe5dfe5.png)
