### ISSUE TITLE
Facing errors while trying to make install the repo

### ISSUE THREAD

**Issue by Johan511** [apache/age#309]
I would like to contribute to this project and have tried to make the clone of the repo on my local system, during which I faced the following errors

Database : postgres 14

**src/backend/catalog/ag_catalog.c:97:68: error: incompatible type for argument 4 of ‘prev_process_utility_hook’**
prev_process_utility hook requires 8 arguments but, only 7 were passed. The repo does not pass the bool readOnlyTree argument

typedef void (*ProcessUtility_hook_type) (PlannedStmt *pstmt, const char *queryString, bool readOnlyTree, ProcessUtilityContext context, ParamListInfo params, QueryEnvironment *queryEnv, DestReceiver *dest, QueryCompletion *qc);

**src/backend/catalog/ag_catalog.c:100:62: error: incompatible type for argument 4 of ‘standard_ProcessUtility’**
standard_ProcessUtility is a function which requires 8 arguments but, only 7 were passed. The repo does not pass the bool readOnlyTree argument

extern void standard_ProcessUtility(PlannedStmt *pstmt, const char *queryString, bool readOnlyTree, ProcessUtilityContext context, ParamListInfo params, QueryEnvironment *queryEnv, DestReceiver *dest, QueryCompletion *qc);

I had greedily tried to fix these issues by setting readOnlyTree to false and tried compiling and still face this issue

**src/backend/catalog/ag_graph.c:67:15: error: void value not ignored as it ought to be**
src/backend/catalog/ag_graph.c:67 is
graph_oid = CatalogTupleInsert(ag_graph, tuple);

CatalogTupleInsert returns void while graph_oid has type short int.

I am very enthusiastic to try and fix these issues and be a part of the age community and would appreciate any suggestions on how I could fix the issues.

**Comment by jrgemignani** [comment]
PostgreSQL 14 is currently not supported. Currently, only PostgreSQL versions 11 & 12 are supported. 

Version 13 is being worked on and then 14 will be after that.

**Comment by Johan511** [comment]
Hi, can you guide me on use postgresql 11 source/header files during installation of the age extension. I have installed age and tried running make but still have the same errors

**Comment by jrgemignani** [comment]
Here is a link that should help.

https://age.apache.org/age-manual/master/index.html

**Comment by Johan511** [comment]
I have been following the age manual and have still got the same errors mentioned above

**Comment by jrgemignani** [comment]
Please see this issue -

https://github.com/apache/age/issues/300

**Comment by jrgemignani** [comment]
If this is resolved, please close the issue :)
