### ISSUE TITLE
CALL... YIELD clause ignores WHERE condition

### ISSUE THREAD

**Issue by dehowef** [apache/age#312]
**Describe the bug**
CALL ... YIELD clause ignores the WHERE condition. WHERE clauses used proceeding a CALL ... YIELD subquery will be ignored.

**How are you accessing AGE (Command line, driver, etc.)?**

psql commandline

**What is the command that caused the error?**
```pgsql
SELECT * FROM cypher('test', $$ CALL sqrt(1) YIELD sqrt WHERE sqrt = 2 RETURN sqrt$$) as (a agtype);
```
Result:
```
  a  
-----
 1.0
(1 row)
```

**Expected behavior**
Return value should be null; sqrt(1) != WHERE condition of 2.

**Environment (please complete the following information):**
- Version: latest version of master branch

**Comment by jrgemignani** [comment]
This is the offending line -

2184         if (is_ag_node(clause, cypher_call))

I changed it to -

2184         if (is_ag_node(clause->self, cypher_call))

It looks like just a typo that got overlooked.
