### ISSUE TITLE
Become familiar with the gdb debugger and PostgreSQL flow

### ISSUE THREAD

**Issue by jrgemignani** [apache/age#313]
This task is to help you become familiar with the GDB debugger and how a command is processed in PostgreSQL.

GDB is a full featured debugger with lots of capabilities. But, for most tasks, you only need to know a few commands and a basic instruction of how to use it. The GDB documentation is available online and if you have any questions. You can also comment here or message us if you have any questions.

To debug a PostgreSQL session  -

1. You will need to make sure that when you configured and built PostgreSQL, you did so with any debugging flags enabled.
2. PostgreSQL needs to be running.
3. The PostgreSQL session that you want to debug needs to be open.
4. Your GDB session needs to be in the **bin** directory for the PostgreSQL distribution that you are using.
5. You need to know the process of the **session** that you will be debugging.
6. You can then execute the command `gdb -tui postgres the_pid_number`
7. You will need to set one, or more, breakpoints (b) and then tell GDB to continue (c)

The basic GDB commands are -

- **b** for breakpoint, fx, `b exec_simple_query` or `b 930` 
- **c** for continue - continues to the next breakpoint
- **n** for next line
- **s** for step into
- **p** for print, fx, `p *node` 
- **d** for delete all breakpoints
- **q** for quit

A good breakpoint for the start of a PostgreSQL session is `exec_simple_query`. Unless you know of a specific area or function that you need to look at. For this task, `exec_simple_query` is a good start.

In this task you will use the debugger to trace the `SELECT 1;` statement from beginning to end (output). You do **not** need to worry about the planner (you'll know it when you see it). You do **not** need to worry about the details, just the general flow. It is **not** expected that you will completely understand most of what you see. However, it will help you get used to the debugger and a bit of how PostgreSQL processes commands.

An example, to get you started -

![Image](https://user-images.githubusercontent.com/1505136/193316271-f119e8b2-1249-4383-b485-63c20918e5d8.png)

The session will look something like the following -

![Image](https://user-images.githubusercontent.com/1505136/193317211-68092f26-275e-407a-ab24-392b7edaf4b9.png)

From there you would enter in a break point and tell it to continue -
![Image](https://user-images.githubusercontent.com/1505136/193317100-22f102cc-2ad4-46eb-97ad-d5aae22f51a2.png)

From your session enter the command `SELECT 1;` which is a good, and relatively simple one, to follow -

![Image](https://user-images.githubusercontent.com/1505136/193318651-f6d48359-169d-4541-936c-3605b4bee308.png)

The debugger session will then break at `exec_simple_query ` -

![Image](https://user-images.githubusercontent.com/1505136/193318491-f0357b2a-0f31-4f10-a09d-2f8e30346abb.png)

**Comment by rafsun-yu** [comment]
Started the task.

**Comment by susano0** [comment]
Completed the activity. Ran a simple query and then used the debugger to trace its execution.

**Comment by skkk98** [comment]
Started doing the task.

**Comment by rafsun-yu** [comment]
Completed the task. 

Note: In Ubuntu, gdb 10.x cannot read debug information even if compiled postres with debug flag, in case anyone may find it useful. Updating gdb to latest version fixed it.

**Comment by PragyanD** [comment]
Completed the task

**Comment by jrgemignani** [comment]
What directory are you rnning gdb from? Can you list its contents here. 
What is the gdb command that you are using? 
Can you show the postgres processes (ps command).

**Comment by jrgemignani** [comment]
You are in the correct directory. However, you need to specify the pid for your -> session <- to postgres. In the image above, that pid is 22152. It just looks like you're using the wrong pid.

**Comment by skkk98** [comment]
Even when I use 22152 it doesn't work. gives the same error(could not attach process).

**Comment by jrgemignani** [comment]
That pid will change if you exit the session. Is that process still there?

**Comment by jrgemignani** [comment]
This may be of help -

https://stackoverflow.com/questions/19215177/how-to-solve-ptrace-operation-not-permitted-when-trying-to-attach-gdb-to-a-pro

**Comment by skkk98** [comment]
It's still there. I tried exiting and starting the session again, and ran the gdb command again(with new pid) but still the same error.

**Comment by susano0** [comment]
try using sudo gdb

**Comment by jrgemignani** [comment]
There should be no need to use root or sudo. If the process is owned by your account, you will be able to debug it.

Using root or sudo suggests that the development setup may be incorrect.

**Comment by skkk98** [comment]
I'll try the article and see. I checked, and the process is owned by my account. Tried using sudo as well, it attaches to the process but still doesn't find breakpoint(doesn't even read postgres.c file)

**Comment by jrgemignani** [comment]
That might be due to the path variable and gdb running under root.

**Comment by jrgemignani** [comment]
I should mention, for anyone that needs to use **sudo** or **root** for this task, you are doing it incorrectly. You will need to fix your account.

You do not need to use either. So, if anyone completed this task using either **sudo** or **root**, you need to do this task again, without them.

**Comment by skkk98** [comment]
According to the article, It asks to change ptrace.conf or ptrace_scope, And in order to do that I have to use sudo, Should I use sudo?

**Comment by jrgemignani** [comment]
Yes, that is fine.

**Comment by susano0** [comment]
`echo 0 | sudo tee /proc/sys/kernel/yama/ptrace_scope`

This might help.

**Comment by jrgemignani** [comment]
Sometimes you will need root to change specific system settings. Especially, security settings. This may be a case where they are blocking gdb from connecting to a process.

**Comment by skkk98** [comment]
I tried doing what article said(Thanks @susano0!), Now it attaches to the process. But still gdb can't find the breakpoint. I think it's some path issue. Somehow it reads from src/port/path.c I'll see what I can do to fix this.

**Comment by rafsun-yu** [comment]
@skkk98 Did you run `c` command in gdb after running `SELECT 1;` in psql?

**Comment by rafsun-yu** [comment]
> I should mention, for anyone that needs to use **sudo** or **root** for this task, you are doing it incorrectly. You will need to fix your development environment.
> 
> You do not need to use either. So, if anyone completed this task using either **sudo** or **root**, you need to do this task again, without them.

@jrgemignani I installed postgres on `/usr/local/..`, so I needed to run 'make' commands on sudo. However, I can run postgres and psql process without sudo and they are owned by personal account. Do you think that's fine?

**Comment by skkk98** [comment]
@rafsun-yu yupp, I did. But it never finds `exec_simple_query`.

**Comment by jrgemignani** [comment]
@rafsun-yu You need to have PostgreSQL installed under a development account, not root nor an admin account. 

For me, as an example, I have a user account **jgemignani** on my home server with a home directory of **/home/jgemignani** and all of the PostgreSQL versions and AGE github repos that I use are under that account. This eliminates the need to use root or sudo for builds and for any management of the databases you use for testing. This keeps it all local.

Using root or sudo for builds is dangerous. You can easily mess up your system. Additionally, if this were a company provided server that you were sharing with other developers, you wouldn't have the privileges to use root nor sudo. You would need to install all of this under your own development account. The unix admin would make sure issues with security packages blocking gdb from debugging you processes, like above, were resolved.

So, **everyone** who hasn't installed PostgreSQL and AGE under their own development accounts, needs to go back and redo their development environments. 

Additionally, if PostgreSQL is installed on the system, under root, you will need to either disable it from starting or uninstall it altogether. This is because they will share the default port of 5432.

Hopefully, this helps. If you have additional questions on setting up your account, please let me know.

**Comment by marodins** [comment]
Completed this task.

**Comment by skkk98** [comment]
Completed this task.
