### ISSUE TITLE
Non-existent label results in error, rather than no matches

### ISSUE THREAD

**Issue by TropicalPenguin** [apache/age#314]
**Describe the bug**

If I have a match clause in a cypher query that uses a non-existent label, that pattern should merely not match anything. It should not be an error condition. For example, on any graph lacking the label foo, the result set for the following command is expected to be empty.

`postgres=# SELECT * FROM ag_catalog.cypher('G', $$ MATCH ()-[e:foo]->() RETURN e $$) AS (result1 ag_catalog.agtype);`

Instead, I get:

`ERROR:  label foo does not exists`

This is a major issue. Because if this remains an error condition, either labels need to be predefined even without nodes/edges using them (which could be unwieldy), or queries that operate conditionally upon any matches need to be split into multiple steps (and in turn, this kind of non-error would need to be distinguished from things that are actually errors).

**How are you accessing AGE (Command line, driver, etc.)?**
- Both via command line & Golang driver

**What data setup do we need to do?**
```pgsql
...
SELECT * FROM ag_catalog.create_graph('G');
...
```

**What is the necessary configuration info needed?**
- N/A

**What is the command that caused the error?**
```pgsql
postgres=# SELECT * FROM ag_catalog.cypher('G', $$ MATCH ()-[e:foo]->() RETURN e $$) AS (result1 ag_catalog.agtype);
```
```
ERROR:  label foo does not exists
```

**Expected behavior**
In the case of the above expression, an empty result set. If I replaced RETURN with DELETE, for example, I would expect the statement to not delete anything, rather than error.

**Environment (please complete the following information):**
- Version: 1.0.0

**Additional context**
N/A

**Comment by TropicalPenguin** [comment]
I now notice that this has been mentioned previously, in https://github.com/apache/age/issues/186.

@jrgemignani I can also confirm that neither RedisGraph nor Neo4j treat this as an error. Both simply return no results. This clearly becomes important with more complex queries. For example, I found this error in attempting the following:

```MATCH (a:A) WHERE ID(a)=1125899906842625 WITH a OPTIONAL MATCH (a)-[:incs]->(c)-[d:incs]-() WITH a,c,COUNT(d) AS deps WHERE deps<=1 DELETE a,c```

In the above, regardless of whther the 'incs' label existed or not, it is reasonable to expect that 'a' (assuming it exists) would certainly be deleted. Even if there were nothing else matched. At the moment, the whole statement just fails instead.

**Comment by jrgemignani** [comment]
I agree. I think that it should be in line with others and will see about making this a task to address it.

**Comment by jrgemignani** [comment]
This is now an active task to align this behavior with other graph databases, like Neo4j.

**Comment by dehowef** [comment]
I addressed this issue with an update to the main branch. Cheers

**Comment by TropicalPenguin** [comment]
Thank you so much @dehowef; I look forward to playing with it!
