### ISSUE TITLE
Support passing parameters to the cypher function without creating a prepared statement

### ISSUE THREAD

**Issue by booqoffsky** [apache/age#315]
Are there any plans to add the ability to directly pass parameters to the `cypher` function call?
For example:
```
SELECT * from cypher('test_graph',$$
MATCH (u:User {user_id: $user_id})
RETURN u.user_id $$, '{"user_id":"test_user"}') AS (a agtype);
```
Now this is causing an error:
`ERROR:  third argument of cypher function must be a parameter`

More than a year ago there were comments about such functionality:
https://github.com/apache/age/issues/43#issuecomment-799599013
https://github.com/apache/age/issues/76#issuecomment-860228285

**Comment by jrgemignani** [comment]
Is this not explained in #43 ? At the end, it is stated how to do it.

**Comment by booqoffsky** [comment]
The question is more about the functionality that was proposed in https://github.com/apache/age/issues/76#issuecomment-860228285

But considering the answer from #43 and the fact that the proposed functionality is not critical, am I right in assuming that it is not planned to be implemented now?
>Also, both AGE parameters and Postgres parameters can only be used in prepared statements.

**Comment by jrgemignani** [comment]
I think there is confusion, likely on both sides, of what a parameter is and how it is used.

The cypher function can take **PG parameters** as the 3rd argument, like you gave. However, a **PG parameter** isn't the same as a constant value, passed as a variable, which is what you are using.

Note the error messages -

```
psql-11.5-5432-pgsql=# SELECT * from cypher('test_graph',$$ MATCH (u:User {user_id: $user_id})
RETURN u.user_id $$, '{"user_id":"test_user"}') AS (a agtype);
ERROR:  third argument of cypher function must be a parameter
LINE 2: RETURN u.user_id $$, '{"user_id":"test_user"}') AS (a agtype...
                             ^
psql-11.5-5432-pgsql=# SELECT * from cypher('test_graph',$$ MATCH (u:User {user_id: $user_id})
RETURN u.user_id $$, $1) AS (a agtype);
ERROR:  there is no parameter $1
LINE 2: RETURN u.user_id $$, $1) AS (a agtype);
```

But, it looks like what you are asking is more like the following, which doesn't work either.

```
psql-11.5-5432-pgsql=# \set user_id '{"user_id":"test_user"}'
psql-11.5-5432-pgsql=# SELECT * from cypher('test_graph',$$ MATCH (u:User {user_id: $user_id})
RETURN u.user_id $$, :user_id) AS (a agtype);
ERROR:  syntax error at or near "{"
LINE 2: RETURN u.user_id $$, {"user_id":"test_user"}) AS (a agtype);

psql-11.5-5432-pgsql=# \set user_id '''{"user_id":"test_user"}'''
psql-11.5-5432-pgsql=# SELECT * from cypher('test_graph',$$ MATCH (u:User {user_id: $user_id})
RETURN u.user_id $$, :user_id) AS (a agtype);
ERROR:  third argument of cypher function must be a parameter
LINE 2: RETURN u.user_id $$, '{"user_id":"test_user"}') AS (a agtype...
                             ^
```

It should be possible, and relatively straightforward, to allow the 3rd value to take on a constant value. However, I'm not sure how useful adding that would be for users.

**Comment by booqoffsky** [comment]
Thanks for the detailed explanation! 

There was an idea that it would be possible to slightly reduce the amount of programming to execute a query with parameters calculated in the code (not to do PREPARE first and then EXECUTE). 

However, after trying psycopg3 (Postgresql adapter for Python), I found for myself that such code is enough to correctly execute the request:

```
cursor.execute(
            """
                SELECT * FROM cypher('test_graph', $$
                MATCH (u:User {user_id: $user_id})
                RETURN u.user_id
                $$, %(cypher_params)s)  AS (a agtype);
            """,
            params={
                "cypher_params": json.dumps(
                    {
                        "user_id": "test_user",
                    }
                )
            }
        )
```

So I think my question can be considered closed

**Comment by jrgemignani** [comment]
I'm glad you found an acceptable solution. If this changes, or if others find value in allowing the 3rd parameter to allow an object, instead of a parameter that is an object, we could look into allowing it.
