### ISSUE TITLE
Query to return list of graphs

### ISSUE THREAD

**Issue by susano0** [apache/age#316]
I feel there should be a query that would return the names of the different graphs I have created. After creating a bunch of graphs, it gets difficult to recall their names.

Creating a new query with the syntax `SELECT * FROM ag catalog.get graph list()` could be a solution to this issue.

Also, a further enhancement could be to associate a short description with the graph name.

**Comment by TropicalPenguin** [comment]
SELECT * FROM ag_catalog.ag_graph;

**Comment by TropicalPenguin** [comment]
Neo4J appears to offer such diagnostics; neatly overloaded for all vs specific graphs: https://neo4j.com/docs/graph-data-science/current/graph-list/
