### ISSUE TITLE
Server crash in attempt to return undefined variable from MATCH

### ISSUE THREAD

**Issue by TropicalPenguin** [apache/age#329]
**Describe the bug**
Using the sample commands/test program from https://github.com/apache/age/issues/328, if I replace the `RETURN c,deps` sub-clause with `RETURN c,d`

In that program, this query prompts the following error:
`panic: read tcp 127.0.0.1:53392->127.0.0.1:5434: read: connection reset by peer`

And if I try a command in psql soon afterwards:
```
WARNING:  terminating connection because of crash of another server process
DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
HINT:  In a moment you should be able to reconnect to the database and repeat your command.
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
The connection to the server was lost. Attempting reset: Succeeded.
```

**How are you accessing AGE (Command line, driver, etc.)?**
- Golang Driver, psql

**What data setup do we need to do?**
See https://github.com/apache/age/issues/328

**What is the necessary configuration info needed?**
- N/A

**What is the command that caused the error?**
```
MATCH (a:A) WHERE ID(a)=0 WITH a OPTIONAL MATCH (a)-[:incs]->(c)-[d:incs]-() WITH a,c,COUNT(d) AS deps WHERE deps<=1 RETURN c,d
```

**Expected behavior**
An error stating that the variable d is undefined (since only 'deps' is preserved by the WITH, not d itself), rather than closing the connection.

**Environment (please complete the following information):**
- Version: 1.0.0

**Additional context**
N/A

**Comment by jrgemignani** [comment]
I see this still needs to be addressed.

**Comment by dehowef** [comment]
I am currently looking into this issue-- I have tried to reproduce the issue on my machine, but rather than blowing up the server connection, it returns a result for the d variable when it should not have. I suspect this may tie into the issue you mentioned @TropicalPenguin . Thanks for pointing this out.
