### ISSUE TITLE
Cypher SET Clause for Copying All Properties

### ISSUE THREAD

**Issue by TropicalPenguin** [apache/age#343]
**Is your feature request related to a problem? Please describe.**
Currently, the AGE implementation of the Cypher SET clause expects a variable name.

If a variable name isn't provided, the following error is currently noted:
`ERROR:  SET clause expects a variable name`

This means that if I want to copy all properties from one entity to another, I would need to know all possible properties by name before creating a given query. An example of where copying all properties can be useful is "renaming" a relation in a single query (creating the new, copying the properties, and deleting the old).

**Describe the solution you'd like**
The same SET syntax [used by Neo4J](https://neo4j.com/docs/cypher-manual/current/clauses/set/#set-copying-properties-between-nodes-and-relationships) and [RedisGraph](https://github.com/RedisGraph/RedisGraph/pull/2051) 

**Describe alternatives you've considered**
Querying all properties in first query, using results from first query to create a second query containing the SET clause.

**Additional context**
I created a similar request [for RedisGraph](https://github.com/RedisGraph/RedisGraph/issues/2045) last year, and they found it pretty trivial to support.

**Comment by jrgemignani** [comment]
I was not aware that the SET commands implementation of the Cypher specification was incomplete. I will look into addressing this.

**Comment by TropicalPenguin** [comment]
Hi @jrgemignani; in case it's of interest to anyone on this project, I've opened bounties on this (https://app.bountysource.com/issues/114119785-cypher-set-clause-for-copying-all-properties) issue, and also on #369. https://app.bountysource.com/issues/114119874-crash-on-edge-merge-after-edge-match

**Comment by TropicalPenguin** [comment]
> Hi @jrgemignani; in case it's of interest to any contributor to this project, I've opened bounties on this (https://app.bountysource.com/issues/114119785-cypher-set-clause-for-copying-all-properties) issue, and also on #369. https://app.bountysource.com/issues/114119874-crash-on-edge-merge-after-edge-match

@jrgemignani It would be really nice to have an associated label to indicate this issue has one.

**Comment by jrgemignani** [comment]
As per the last one, I'm not sure what you mean by label. This is already labeled as a bug.

**Comment by parvit** [comment]
Hi @TropicalPenguin, it says here https://neo4j.com/docs/cypher-manual/current/deprecations-additions-removals-compatibility/#_deprecated_features_2 that the ``` SET a=b ``` syntax is deprecated in 5.2, and ``` SET a=properties(b) ``` is recommended instead.

Should we allow both for this change or only the recommended one? thanks

**Comment by TropicalPenguin** [comment]
Semantically, the new style is *much* more intuitive. And pretty consistent with [related syntax](https://github.com/apache/age/issues/366).

**Comment by parvit** [comment]
Hi @TropicalPenguin @jrgemignani, I was trying to understand how to implement this change and it seems that some of the pieces are already there, but i'm missing one key thing: how exactly do i obtain the in the code the list of properties from a ColumnRef ? thank you for the support.

**Comment by TropicalPenguin** [comment]
I won't be able to give you much more of a clue than https://github.com/apache/age/blob/ccd413dc15410d7262e754f21f0970f1861c9430/src/backend/utils/adt/agtype.c#L4807-L4840

**Comment by parvit** [comment]
Thanks i'll look into it.

**Comment by TropicalPenguin** [comment]
Looks like line 4834 is the key.

**Comment by jrgemignani** [comment]
@TropicalPenguin @parvit I would like to note that this issue is **currently** being worked on (looked into), by other PMCs and committers, interns in this particular case. Please give them the opportunity to work on it. Especially, since this is a case of where functionality is missing, potentially due to an oversight, and that needs to be addressed. I do appreciate you bringing this issue to our attention!

@TropicalPenguin Please hold back on submitting **bounties** for features that aren't implemented yet, or appear to be missed or overlooked. This is an area that PMCs and committers need to address and rectify, using the proper channels and proper procedures - many that you are not a party to. There are a lot of internal discussions, design decisions, and roadmaps that go into a feature - they take time. Plus, we don't want to have a duplication of work and the messiness that may cause. We don't want the **bounties** to start causing issues or too much noise so, let's try to find a happy medium. Do feel free to ask if something falls into this category. 

Additionally, as a side note, SET, along with the other update commands, are extremely tricky to get functioning correctly due to subtle interactions and requirements. Think, transaction and command ids, begin/commit blocks, chained commands, etc. They are not trivial and there are design considerations and tradeoffs that we need to discuss and make. 

john

**Comment by parvit** [comment]
@jrgemignani Well don't worry too much, at this point i'm stepping out. Good luck.

**Comment by TropicalPenguin** [comment]
@jrgemignani Hmm, this becomes complicated. There's a much weaker incentive for me to create a bounty in the first place if I know that a given item is under active development.

For what it's worth, now that one is already submitted in this case, I'm happy to still honor it, assuming that doing so doesn't contravene the [note you made](https://github.com/apache/age/issues/369#issuecomment-1341511955) about Apache AGE not officially "support[ing bounties] monetarily _or otherwise_" (emphasis mine).

This wouldn't seem to require being privy to such private channels, if, for example, project views like https://github.com/orgs/apache/projects/96/views/1 were in sync with such ongoing work. Given that they're already partly filled in, I assume there's no particular confidentiality issue here, just a logistical one.

> We don't want the bounties to start causing issues or too much noise so, let's try to find a happy medium.

I certainly don't mean to stir up noise. What makes it tricky is those (seemingly rare, fortunately) cases where my own development goals & their desired time-frames have dependencies like this. In such a situation, often even an imperfect - and quite possibly expected to be temporary - solution is better than no solution. I would hope that if I do find a need to support such work independent of AGE (whether remaining in this project's issue tracker, or - if it would usefully avert such noise - through a currently-hypothetical fork for such likely-temporary feature development), that it can feed back positively in _some_ way into the (more general) community project. I hope there can be a happy medium.

**Comment by jrgemignani** [comment]
@parvit @TropicalPenguin I don't mean to discourage anyone from contributing to the project, quite the opposite. But, I do feel that everyone should try to coordinate their efforts. Some of these discussions, like how to implement this specific feature, need to be discussed/addressed before implementing it. Especially, if there are questions about how to implement it.

For example -

> Hi @TropicalPenguin, it says here https://neo4j.com/docs/cypher-manual/current/deprecations-additions-removals-compatibility/#_deprecated_features_2 that the SET a=b syntax is deprecated in 5.2, and SET a=properties(b) is recommended instead.
> 
> Should we allow both for this change or only the recommended one? thanks

This is something that needs to be discussed by the Apache AGE PMCs, committers, and community. 

Additionally, as this would likely require changes to the grammar file to support, there is a lot to think about on whether or which, we support, or not. 

To answer the question -

> Should we allow both this change or,...

 My position would be to say yes, if the grammar permits it without causing side effects. But, again, it isn't just my decision.

Btw, If either of you would like to be a part of these discussions and decisions, you are more than welcome to become committers to the Apache AGE project.

**Comment by jrgemignani** [comment]
@TropicalPenguin IMHO, I think the issue here, for all parties, is that we are all learning this - not so well defined (yet) process, and it is messy. 

As an Apache AGE PMC, I'm trying to find a way to coordinate everyone's efforts without stepping on anyone's toes nor causing a duplication of any work nor giving preferential treatment to anyone. And, I fully realize that some is inevitable, no matter how hard I may try. But, I still try.

As a user, you ideally need the feature/fix, right now, A.S.A.P. and there is nothing wrong with that position either.

We also have different perspectives for that fix. I want it to be correct and as complete as possible. You just want an adequate solution, sooner rather than later. Both are valid within the proper context.
 
In walk bounties,... I like the idea of bounties, I really do. However, in a development environment, I see them as causing problems due to their monetary component. 
- Do I approve a bounty over another submission, or not, provided they are equivalent? And both are submitted reasonably close.
- What happens if the bounty submission isn't approved, but the fix was valid? 
- How much support do I give to someone working on a bounty? 
- What if the feature/fix requires design and implementation decisions to be made?
- What if one of the Apache AGE PMCs were to complete a bounty?
- Should that bounty be given to whomever fixes the issue the bounty is tied too?

Those are just some concerns of mine. But, let's try to see if we can coordinate the bounties and iron them out along the way.

> @jrgemignani Hmm, this becomes complicated. There's a much weaker incentive for me to create a bounty in the first place if I know that a given item is under active development.

If I were aware you might put a bounty on the item, I might have mentioned that the issue was already under review. Although, technically, I **sort of** did.

> I was not aware that the SET commands implementation of the Cypher specification was incomplete. I will look into addressing this.

Let's try to improve our communication and see if we can make these work.

john

**Comment by TropicalPenguin** [comment]
I think what is at issue here is mostly not bounties, even if they may add some interesting wrinkles. But rather gatekeeping standards. People will of course differ on what kind of constraints these standards would enforce. Personally, I'd see their primary role as promoting and preserving the interests of users.

And this standard seems to dissolve a lot of the messiness in the concerns you mentioned, and the questions you highlighted. 

Firstly, it renders this a very odd standard for an open source project:
> @TropicalPenguin Please hold back on submitting bounties for features that aren't implemented yet, or appear to be missed or overlooked. This is an area that PMCs and committers need to address and rectify, using the proper channels and proper procedures - many that you are not a party to. There are a lot of internal discussions, design decisions, and roadmaps that go into a feature - they take time. Plus, we don't want to have a duplication of work and the messiness that may cause. We don't want the bounties to start causing issues or too much noise so, let's try to find a happy medium. Do feel free to ask if something falls into this category.

Which one can see simply by replacing the word 'bounties' in the above with 'patches' or 'pull requests'. Given that the goal of the former is to stimulate the latter, the precedent would be identical.

I think you at least implicitly realised this when the language was toned down in later remarks:
> I don't mean to discourage anyone from contributing to the project, quite the opposite. But, I do feel that everyone should try to coordinate their efforts.

I think open source ecosystems offer richer potential for coordination than what people might generally see in more corporate settings. In this kind of environment, I don't see independent streams of work as violating coordination at all. The byproducts of each stream can reveal each-others' mutual blindspots; code and ideas can be shared between them, which can further inform future developments.

Done well, I think gatekeeping can serve this.

So, as a general point on bounties before some thoughts on the questions you've highlighted... I think the _only_ obligation created by a bounty is for those offering the incentive, to deliver the reward to those who are the first to provide a solution they alone are happy with to a given issue. _Anything_ more than that is extraneous to the bounty itself.

> Do we approve a bounty over another submission, or not, provided they are equivalent? And both are submitted reasonably close.

I think this is conflating bounties with work product. Approval of bounties falls *only* to bounty providers. The gatekeeping of work product making its way into a given repo can proceed as it would even without bounties. In the (probably not too common, in practice) situations where there are multiple submissions, or anticipated submissions, the gatekeepers can decide which they prefer (if any), or can decide on parts of each to combine.

> What happens if the bounty submission isn't approved, but the fix was valid?

Mostly upside, I'd expect. Though the extent of upside will be modulated by whether the submission was rejected for good reasons. Even if something isn't approved in one form, it's still capable of providing the desired solution to whoever opened the bounty, assuming they're capable of integrating it into their own deployment. If it was rejected for good reasons, there would likely be an even better solution later, in the mainline repo, which anyone using the placeholder solution can then migrate to, if they wish (with the current case this is simple, since it's with regard to query syntax, as opposed to lower-level data structures, for which changes are more consequential). Having a given solution in the central repo mostly just makes things more convenient.

> How much support do we give to someone working on a bounty?

This is one of the more interesting questions here. I think it'll be subjective, not only to the person asking it of themselves, but also according to what the bounty is for and who is working on it, and even depending on what support is being called for. It'll be easy to imagine someone working on the same problem having different incentives to someone working on other problems. At which point I personally would hope to go back to the ideal of 'promoting and preserving the interests of users'. And there may be some situations where acting by such a principle would mean *not* supporting. Very contextual though.

> What if the feature/fix requires design and implementation decisions to be made?

I'm fond of the mantra "release early, release often", because it avoids the pretense that everything needs to be anticipated before work can begin, and instead allows the work itself to reveal answers to questions that were difficult to foresee. Which goes back to my earlier comments on coordination

> What if one of the Apache AGE PMCs were to complete a bounty?
> Should that bounty be given to whomever fixes the issue the bounty is tied too?

I think the only difficulty here arises when a team of people is credited for a solution. But if they coordinated in the first place to achieve that, I expect they can negotiate how to apportion credit amongst themselves. But I think this up to the team, not those providing the bounty itself.

> Should we even work on an feature/fix/issue that has a bounty on it?

Similarly subjective to the question of support. I guess a primary variable of interest becomes: how discerning is the bounty provider of the quality of a given solution? (and "can I provide feedback to assist this discernment?"); that is, if I expect my work to be of a higher standard, but someone else is going to cut corners (assuming the bounty provider will accept it) just to get the bounty, why would I bother? I imagine attitudes would be different depending on the issue in question, and personal sense of those funding the bounty.

Personally, I think that as long as a project has good gatekeeping, this dynamic has way more upside than downside. It circumvents "making the perfect the enemy of the good". And good solutions in the short term can facilitate better solutions in the medium-to-long term.

**Comment by jrgemignani** [comment]
@TropicalPenguin 

I'm just trying to best coordinate everyone's efforts and reduce duplication where I see it. To me, it makes no sense to have multiple people working on the same task, independently. Doing so is just a waste of resources for all parties involved. And, I do not see bounties as necessarily fostering collaboration, I see them as likely fostering competition and potentially resentment. As this is an open source project, it is also important to point out, some of the contributors are actually donating their time and expertise to the project. 

I do think that at this point we "generally" understand each others positions, although, we likely disagree on many points. But, that is the nature of the software development process. So, I guess we'll fumble forward and hopefully find that happy middle ground on the way.

**Comment by c0d3x27** [comment]
It sounds like you would like to be able to use the SET clause in AGE to copy all properties from one entity to another, without having to specify each property name individually.

One alternative you could consider is using the FOREACH clause in your query to iterate over all of the properties of the source entity and set them on the destination entity. The FOREACH clause allows you to execute a block of statements for each element in a list, so you could use it to loop over all of the properties of the source entity and set them on the destination entity one by one.

For example, you could use a query like the following to copy all properties from one node to another:

`MATCH (source:Label)
MATCH (destination:Label)
FOREACH (property IN keys(source) |
  SET destination[property] = source[property]
)`

This query would match the source and destination nodes, then use the FOREACH clause to iterate over all of the properties of the source node. For each property, it would use the SET clause to set the corresponding property on the destination node to the value of the source property.

Alternatively, you could consider using the apoc.create.setProperties procedure from the APOC library to copy all properties from one node to another in a single call. This procedure takes two node IDs as arguments and copies all properties from the first node to the second.

For example, you could use a query like the following to copy all properties from one node to another:
`MATCH (source:Label)
MATCH (destination:Label)
CALL apoc.create.setProperties(destination, source) YIELD node
RETURN node`

This query would match the source and destination nodes, then use the apoc.create.setProperties procedure to copy all properties from the source node to the destination node in a single call.

**Comment by rafsun42** [comment]
> It sounds like you would like to be able to use the SET clause in AGE to copy all properties from one entity to another, without having to specify each property name individually.
> 
> One alternative you could consider is using the FOREACH clause in your query to iterate over all of the properties of the source entity and set them on the destination entity. The FOREACH clause allows you to execute a block of statements for each element in a list, so you could use it to loop over all of the properties of the source entity and set them on the destination entity one by one.
> 
> For example, you could use a query like the following to copy all properties from one node to another:
> 
> `MATCH (source:Label) MATCH (destination:Label) FOREACH (property IN keys(source) | SET destination[property] = source[property] )`
> 
> This query would match the source and destination nodes, then use the FOREACH clause to iterate over all of the properties of the source node. For each property, it would use the SET clause to set the corresponding property on the destination node to the value of the source property.
> 
> Alternatively, you could consider using the apoc.create.setProperties procedure from the APOC library to copy all properties from one node to another in a single call. This procedure takes two node IDs as arguments and copies all properties from the first node to the second.
> 
> For example, you could use a query like the following to copy all properties from one node to another: `MATCH (source:Label) MATCH (destination:Label) CALL apoc.create.setProperties(destination, source) YIELD node RETURN node`
> 
> This query would match the source and destination nodes, then use the apoc.create.setProperties procedure to copy all properties from the source node to the destination node in a single call.

Thanks for mentioning these alternative solutions. However, I already started implementing the updates discussed above.

**Comment by rafsun42** [comment]
Hi @jrgemignani, I have few points to clarify.

1. Should we allow `SET a = b` as well? It's supported in openCypher, but deprecated in the recent version of Neo4j.
> Good question; noting the approach that @jrgemignani described in an earlier issue...
> 
> > First, and foremost, we try to implement the openCypher specification as closely as possible. Where there is ambiguity or vagueness in the openCypher specification, we look to Neo4j for possible clarification. When there is still ambiguity or vagueness, we try to think of what our user base would expect - what makes sense.
> 
> .. and since [the latest openCypher spec](https://s3.amazonaws.com/artifacts.opencypher.org/openCypher9.pdf) still documents the a=b syntax, I think it should be supported. Now, personally - given the influence Neo4J has over Cypher's evolution - I also think the new syntax should be supported too. Maybe given that you're asking the question, this is sufficient to indicate 'ambiguity or vagueness', if not in the specification then certainly in what the user base would expect upside_down_face .

2. I noticed that we currently don't support updating a label by `SET n:NewLabel`. Should I work on this as part of the same issue?

**Comment by jrgemignani** [comment]
@rafsun42 If the two forms can coexist in the grammar, then we should attempt to support the deprecated form as well. However, if they can't coexist, then we should just support the recent version. However, I can't see why they wouldn't be able to coexist in the grammar.

For `SET n:NewLabel`, each label has its own table. So, it is not as simple as just changing the label, you would need to - 
- Create a new label table, if needed.
- Move the specified component to the new table.
- Remove the old component.
- Remove the old table, if empty.
- Plenty of checks to make sure it can be rolled back on failure.

As it would be rather involved, this would probably be best with its own issue/ticket.

**Comment by rafsun42** [comment]
For the `Set n:NewLabel` concern, created this issue #464

**Comment by rafsun42** [comment]
@jrgemignani Sent the PR (#468) for this issue.

**Comment by TropicalPenguin** [comment]
@rafsun42 Thank you so much! I'll try testing the functionality with my data set as soon as I can!

**Comment by TropicalPenguin** [comment]
Hi @rafsun42; I think I've put your solution (at least for the `SET a = b` case) through fairly strenuous testing now. Seems to work great! You're welcome to take advantage of the bounty if you like.

**Comment by jrgemignani** [comment]
@TropicalPenguin @rafsun42 That bounty is between you two.

**Comment by c0d3x27** [comment]
> > It sounds like you would like to be able to use the SET clause in AGE to copy all properties from one entity to another, without having to specify each property name individually.
> > One alternative you could consider is using the FOREACH clause in your query to iterate over all of the properties of the source entity and set them on the destination entity. The FOREACH clause allows you to execute a block of statements for each element in a list, so you could use it to loop over all of the properties of the source entity and set them on the destination entity one by one.
> > For example, you could use a query like the following to copy all properties from one node to another:
> > `MATCH (source:Label) MATCH (destination:Label) FOREACH (property IN keys(source) | SET destination[property] = source[property] )`
> > This query would match the source and destination nodes, then use the FOREACH clause to iterate over all of the properties of the source node. For each property, it would use the SET clause to set the corresponding property on the destination node to the value of the source property.
> > Alternatively, you could consider using the apoc.create.setProperties procedure from the APOC library to copy all properties from one node to another in a single call. This procedure takes two node IDs as arguments and copies all properties from the first node to the second.
> > For example, you could use a query like the following to copy all properties from one node to another: `MATCH (source:Label) MATCH (destination:Label) CALL apoc.create.setProperties(destination, source) YIELD node RETURN node`
> > This query would match the source and destination nodes, then use the apoc.create.setProperties procedure to copy all properties from the source node to the destination node in a single call.
> 
> Thanks for mentioning these alternative solutions. However, I already started implementing the updates discussed above.

Ok, welcome no problem

**Comment by jrgemignani** [comment]
PR merged.

**Comment by rafsun42** [comment]
@jrgemignani thanks!
