### ISSUE TITLE
NULL as a boolean type.

### ISSUE THREAD

**Issue by MuhammadTahaNaveed** [apache/age#368]
I have a question about `typecasting NULL as boolean`.

- In the documentation it is written that you can typecast null to boolean type null `explicitly using NULL::boolean` typecasting.
![image](https://user-images.githubusercontent.com/85064039/203741910-fe035e69-257f-47bf-8a69-d6335d981fcb.png)

- But when I tried doing that, it generated error saying `typecast boolean not supported  `.
![image](https://user-images.githubusercontent.com/85064039/203742459-50255d90-5ef9-4962-afbe-579ac12a0938.png)

Am I doing it wrong or is there any other reason for that ?

**Comment by jrgemignani** [comment]
There is no support in AGE for typecasting `::` anything as a Boolean.

Can you link where in our documentation it states this?

**Comment by jrgemignani** [comment]
@MuhammadTahaNaveed Thank you!

Our team will discuss if this should be added or if it should be removed from the documentation.

**Comment by dehowef** [comment]
I have removed the misleading segment from the documentation.
