### ISSUE TITLE
Does Apache AGE support label inheritance? 

### ISSUE THREAD

**Issue by aked21** [apache/age#374]

**Comment by JoshInnis** [comment]
We do not currently support label inheritance, however it is on the roadmap to be worked on soon.

**Comment by JoshInnis** [comment]
Label inheritance utilizes the table inheritance feature that Postgres provides. https://www.postgresql.org/docs/11/tutorial-inheritance.html

We already use inheritance, vertices and edges without labels go into a top level table and all vertices and edges with labels are placed in tables. So when you do MATCH(n) with no label the way AGE is written the tables that inherit from the top table with no label are also included.

It is possible to have a label inherit from another label, which would allow for a hierarchy of labels to be available for the user. It is also possible for a label to inherit from more than one label. 

The way to make a label that inherits from another label would be to add a field to create_elabel and create_vlabel called parents which is a list of labels to inherit from (with the default being NULL)

**Comment by jasperblues** [comment]
The way I see it, as long as a vertex can be assigned multiple labels,eg `City:Capital` we can match on the base (City) or specifically match Capitals. Then if we're interested in the type, we can return the labels. 

What benefit does inheritance bring on top of this?

**Comment by jrgemignani** [comment]
@jasperblues In AGE, you cannot assign multiple labels - it is either default, unlabeled, or has a specific label. But, they can't be in City and Capital, fx.
