### ISSUE TITLE
[Bitnine Tech] label names in AGE are case sensitive.

### ISSUE THREAD

**Issue by EunjungSong87** [apache/age#377]
Hello, 

Currently, the names are stored case-sensitively for the label name in AGE as follows: 

![image](https://user-images.githubusercontent.com/47842118/205864300-4543b03c-722e-4d60-ac20-0315c7e8e654.png)

Postgresql automatically stores objects in lower case in pg_catalog when they are created. If names are stored in case-sensitive cases like AGE label now, it seems that there will be many restrictions on the user's use of cypher. 

I would appreciate it if you could check and respond to this issue.
Thank you.

**Comment by jrgemignani** [comment]
Can you please elaborate why you think this will induce restrictions? Please provide an example showing this?

I should point out, the tables that AGE uses are for **internal use only**. They are not for users to manually manipulate. In other words, you do so at your own risk.

**Comment by imranzaheer612** [comment]
You can take a look at this issue. https://github.com/apache/age/issues/56

According to neo4j labels are case-sensitive. `Names are case-sensitive and thus, :PERSON, :Person and :person are three different labels, and n and N are two different variables.` https://neo4j.com/docs/cypher-manual/current/syntax/naming/

See Open Cypher Specification https://opencypher.org/resources/

**Comment by jrgemignani** [comment]
If this has answered your question adequately, please close the ticket.

**Comment by EunjungSong87** [comment]
There was confusion for a while because our other products were not case sensitive. Thanks for the detailed explanation, I'll close the question.
