### ISSUE TITLE
Deleting a single or all vertices with the DELETE clause

### ISSUE THREAD

**Issue by MatheusFarias03** [apache/age#387]
Hi! I was reading the AGE documentation about the DELETE clause and saw some examples there. One of these examples stated that, to delete a single vertex, the following query must be typed:

```sql
SELECT * 
FROM cypher('graph_name', $$
	MATCH (v:Useless)
	DELETE v
$$) as (v agtype);
```
But then, right after this example, it shows how to delete all vertices and edges and it is written that "Running a Match clause will collect all nodes". The example to delete all nodes was:

```sql
SELECT * 
FROM cypher('graph_name', $$
	MATCH (v:Useless)
	DETACH DELETE v
$$) as (v agtype);
```

So, in the "Deleting a single vertex" example, since it is using the Match clause, wouldn't it also delete all vertices?

Documentation : https://age.apache.org/age-manual/master/clauses/delete.html

**Comment by jrgemignani** [comment]
@MatheusFarias03 Yeah, those examples are probably not the best. 

The MATCH command will return whatever you ask it to return. That could be all of the vertices or edges in the selected graph, or just a desired subset of them. 

The DELETE command will delete whatever vertices or edges you pass to it.

**Comment by MuhammadTahaNaveed** [comment]
> SELECT * 
> FROM cypher('graph_name', $$
> 	MATCH (v:Useless)
> 	DELETE v
> $$) as (v agtype);

I think what they are trying to say by the term `"Delete single vertex"`is that this query will delete the vertices(with label Useless) that has no edge.

> 
> SELECT * 
> FROM cypher('graph_name', $$
> 	MATCH (v:Useless)
> 	DETACH DELETE v
> $$) as (v agtype);

while in this case `"Delete all vertices and edges"`, DETACH option will delete all the edges associated with the vertex (with label Useless) and then delete the vertices.

- Here is a small example depicted below. I have created 2 vertices with label "USELESS". Now the command below will delete them all if there is no edge associated.

![image](https://user-images.githubusercontent.com/85064039/207436803-479c8b3b-180b-422a-8172-c74aed927931.png)

- Now I have created two vertices with label "USELESS" and both have edge associated with them. So the command below will first delete all the edges associated with the verteices(with label USELESS) and then the vertices.

![image](https://user-images.githubusercontent.com/85064039/207439215-896a278f-1010-4d88-b228-aadf9d6c7dfd.png)

This is what I think the documentation means.

**Comment by jrgemignani** [comment]
Yeah, it could be more clear.

**Comment by imranzaheer612** [comment]
I think it could be like

To delete a single or multiple nodes having no edges we use this
```
SELECT * 
FROM cypher('graph_name', $$
	MATCH (v:Useless)
	DELETE v
$$) as (v agtype);
```

To delete a single or multiple nodes having edges we use this
```
SELECT * 
FROM cypher('graph_name', $$
	MATCH (v:Useless)
	DETACH DELETE v
$$) as (v agtype);
```

**Comment by imranzaheer612** [comment]
As if we the former delete query,  we would get an error
```
ERROR:  Cannot delete vertex v, because it still has edges attached. To delete this vertex, you must first delete the attached edges.

```
