### ISSUE TITLE
Which Branch to use for Pull Request?

### ISSUE THREAD

**Issue by fatimafatimaprogrammer** [apache/age#392]
Hey you'll For pull request are we supposed to create a new branch or pull through default Master Branch

**Comment by Nimra-1234** [comment]
@fatimafatimaprogrammer 
We follow some steps here.
1. We take pull from master so that we have latest code and our code can auto merge with master/main branch(no code conflict).
2. After that we create our separate branch and do changes there and create PR.

**Comment by jrgemignani** [comment]
For AGE for PostgreSQL 11 base the PR off the **master** branch. That will be the branch that the PR will get merged into.
For AGE for PostgreSQL 12 base the PR off the **PG12** branch. That will be the branch that the PR will get merged into.

**Comment by jrgemignani** [comment]
If this has answered you question adequately, please close the ticket.
