### ISSUE TITLE
Filtering does not work inside with clause

### ISSUE THREAD

**Issue by nib1nt** [apache/age#394]
**How are you accessing AGE (Command line, driver, etc.)?**
- Command line

**What is the command that caused the error?**
```pgsql
SELECT * from cypher('my_graph_name', $$
 WITH 1 as n 
 WHERE n > 1
 RETURN n 
$$) as (n agtype);
```

**Expected behavior**
It should return nothing, it is returning 1 row.

**Environment (please complete the following information):**
- Version: 1.1.0

**Comment by imranzaheer612** [comment]
Ya, even a simple expression can't be evaluated correctly while using `WITH` clause.

![bug-age](https://user-images.githubusercontent.com/62287456/208159538-cb013591-15d2-456c-b234-5f4b65f7de5e.png)

**Comment by Hunaid2000** [comment]
I believe this issue is related to #351 and #238.
