### ISSUE TITLE
Segmentation fault when executing query

### ISSUE THREAD

**Issue by sep2** [apache/age#395]
**Describe the bug**
A segmentation fault is occured when query.

**How are you accessing AGE (Command line, driver, etc.)?**
JDBC

**What data setup do we need to do?**
```pgsql
select create_graph('graph');

select *
from cypher('graph', $$
create (n:Project {name: 'Project A'}),
       (m:Project {name: 'Project B'}),
       (a:Task {name: 'Task A', size: 10}),
       (b:Task {name: 'Task B', size: 5}),
       (c:Task {name: 'Task C', size: 7}),
       (x:Person {name: 'John', age: 55}),
       (y:Person {name: 'Bob', age: 43}),
       (z:Person {name: 'Alice', age: 33}),
       (n)-[:Has]->(a),
       (n)-[:Has]->(b),
       (m)-[:Has]->(c),
       (a)-[:AssignedTo]->(x),
       (b)-[:AssignedTo]->(y),
       (c)-[:AssignedTo]->(y)
$$) as (n agtype);
```

**What is the command that caused the error?**
```pgsql
SELECT * FROM ag_catalog.cypher('graph', $$
match (p:Project)-[:Has]->(t:Task)-[:AssignedTo]->(u:Person)
with distinct t, {tn: t.name, user: collect(u)} as task
with distinct p, {pn: p.name, task: collect(task)} as project
return project
$$) as (p agtype);
```

```
LOG:  server process (PID 224) was terminated by signal 11: Segmentation fault
```

**Expected behavior**
Should not terminate the server.

**Environment (please complete the following information):**
- Version: 1.1.0 inside docker

**Additional context**
None.

**Comment by sep2** [comment]
This another query did not terminate the process:
```
SELECT * FROM ag_catalog.cypher('graph', $$
match (p:Project)-[:Has]->(t:Task)-[:AssignedTo]->(u:Person)
with p, t, collect(u) as users
with p, {tn: t.name, users: users} as task
with p, collect(task) as tasks
with {pn: p.name, tasks:tasks} as project
return project
$$) as (p agtype);
```

but return error message: `ERROR:  container is not an agtype array`. The query runs fine in neo4j.

**Comment by Hunaid2000** [comment]
Hi @sep2. I believe this issue is related to #351 and #238

**Comment by MuhammadTahaNaveed** [comment]
> This another query did not terminate the process:
> ```
> SELECT * FROM ag_catalog.cypher('graph', $$
> match (p:Project)-[:Has]->(t:Task)-[:AssignedTo]->(u:Person)
> with p, t, collect(u) as users
> with p, {tn: t.name, users: users} as task
> with p, collect(task) as tasks
> with {pn: p.name, tasks:tasks} as project
> return project
> $$) as (p agtype);
> ```
> 
> but return error message: `ERROR:  container is not an agtype array`. The query runs fine in neo4j.
> 

@jrgemignani Your pr #1036 may solve this issue as well.

**Comment by jrgemignani** [comment]
There may be an issue with the collect aggregate function. That is where it throws the error.

**Comment by jrgemignani** [comment]
I found part of the issue and am looking at the best way to address it.

**Comment by jrgemignani** [comment]
I am working on a PR to fix this now.

**Comment by jrgemignani** [comment]
I have created PR #1039 to address this issue.

**Comment by jrgemignani** [comment]
This issue is now resolved in the **master** (PostgreSQL version 13) branch.
