### ISSUE TITLE
Accessing variables not included in WITH clause terminates the server

### ISSUE THREAD

**Issue by MuhammadTahaNaveed** [apache/age#396]
**Describe the bug**
Returning any variable not included in `with clause` terminates the server

**How are you accessing AGE (Command line, driver, etc.)?**
Command line

**What data setup do we need to do?**
```pgsql
...
SELECT * FROM cypher('new_issue',$$
     CREATE (v),(u),(w),
            (v)-[:hasFriend]->(u),
            (u)-[:hasFriend]->(w)
$$) as (a agtype);
...
```

**What is the command that caused the error?**
```pgsql
SELECT * FROM cypher('new_issue',$$
      MATCH p=(v)-[*1..2]->(u) 
      WITH p,length(p) AS path_length 
      RETURN v,path_length
$$) as (a agtype,b agtype);
```
```
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
The connection to the server was lost. Attempting reset: Failed.
```

**Expected behavior**
I know that I should only be accessing the variables defined in the scope of WITH clause, but I don't think accessing others should terminate the server.

**Environment (please complete the following information):**
- Version: 1.1.0

**Comment by TropicalPenguin** [comment]
Seems likely to be related to https://github.com/apache/age/issues/329
