### ISSUE TITLE
Dependencies problem 

### ISSUE THREAD

**Issue by saadjameel** [apache/age#397]
Sometime while running AGE-Viewer from Ubuntu **(TERMINAL APP)** I get error messages of dependencies. 
and sometime while starting NPM run start I get this. Any one has any idea? 

Errors were encountered while processing:
 /var/cache/apt/archives/nodejs_14.21.1-deb-1nodesource1_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by imranzaheer612** [comment]
I guess it is happening due to a broken installation. Try installing the viewer again in a separate clean dir.

**Comment by Pratikkapsime** [comment]
You can also try reconfiguring dpkg ( dpkg is used to install, remove, and provide information about **. deb packages**. dpkg) database. Using this: **$ sudo dpkg --configure -a**

**Comment by M4rcxs** [comment]
Maybe its a problem with your nodejs, I think you can try to check your nodejs. 

**Following these steps:**

`sudo apt update`

`sudo apt install nodejs`

`sudo apt install npm`

Other alternative is to check your npm packages.

`npm outdated`

This command will list every package outdated. Or you just can reinstall the AGE Viewer too.

**Comment by RahimullahShaheen** [comment]
It is possible that AGE Viewer is not compatible with the current version of your node js. As mentioned in the documentation the recommended version is 14.16.0 or above.
Make sure you have the required version of node js. To check the version simply type:
`node -v`

To install the desired version of node js run the following command:
`nvm install 14.16.0`

Or you can also try to fix any broken dependencies through the following command:
`sudo apt --fix-broken install`

**Comment by waleedahmed0001** [comment]
The error message you received indicates that there were issues while processing the package "nodejs_14.21.1-deb-1nodesource1_amd64.deb" during an attempted installation or update.

These commands can solve the errors.

```
sudo apt update
sudo apt --fix-broken install
sudo apt clean
npm install
sudo apt install nodejs

```

**Comment by Omar-Saad** [comment]
First Run the following command to remove all the data present in the cache folder.

```
npm cache clean --force
```

Then run the following command to install all the required dependencies.

```
npm install
```

Also make sure that the node version that you have is 14.6 to be compatible with AGE-Viewer because this was mentioned in the documentation.
