### ISSUE TITLE
Rollbacking transactions in AGE not supporting.

### ISSUE THREAD

**Issue by KamleshKumar427** [apache/age#426]
I created a graph named 'new_graph' and populated it with some nodes and edges.
and then applied the following command to delete and then roll back the deleted data.

**BEGIN;**

**SELECT * from cypher('new_graph', $$
        MATCH (V)
        detach delete (V)
$$) as (a agtype);**
 
!! above command deleted the relationship and nodes.

**ROLLBACK;**

!! but after the rollback command, data is not retrieved back.

**Rolling back transactions is a very crucial part of any database, It must also be fully functional in AGE as well.**

Also while inspecting these commands it occasionally throws the following error.
 
![image](https://user-images.githubusercontent.com/95052507/209471157-2c0c77b7-c52e-4639-b984-ba01a9253eb5.png)

**Comment by imranzaheer612** [comment]
But it worked in my case.

```bash
demo=# BEGIN; SELECT * from cypher('graph_name', $$
MATCH (V) detach delete (V) $$) as (a agtype);
BEGIN
 a 
---
(0 rows)

demo=# SELECT * from cypher('graph_name', $$
MATCH (V) RETURN (V) $$) as (a agtype);
 a 
---
(0 rows)

demo=# rollback;
ROLLBACK
demo=# SELECT * from cypher('graph_name', $$
MATCH (V) RETURN (V) $$) as (a agtype);
                                  a                                  
---------------------------------------------------------------------
 {"id": 281474976710657, "label": "", "properties": {}}::vertex
 {"id": 844424930131969, "label": "label", "properties": {}}::vertex
 {"id": 844424930131970, "label": "label", "properties": {}}::vertex
(3 rows)

demo=# 

```
I added some nodes to the graph. Deleted them. Rolled back successfully. Let me try deleting nodes having relationships.

**Comment by imranzaheer612** [comment]
Ya, it's working in the case of nodes with relationships too.
Do you have mulitple sessions running? Try taking a look at the log files to sew what happened.

**Comment by KamleshKumar427** [comment]
No, I didn't have multiple sessions open. But still, it was not working. 
I think you are running it in the terminal. Can you please once try it in age viewer and then 
communicate it?

**Comment by imranzaheer612** [comment]
Yes in my case it's working with the AGE-viewer too. I guess there might be some error in your setup. Did you try generating the error again?

**Comment by JoshInnis** [comment]
We gotta have some more info. Your session crashed and your data was lost? So... there are two issues here. You crashed AGE with DETACH DELETE and data you entered before this transaction was lost?

**Comment by KamleshKumar427** [comment]
Yes, the server crashed and the data was lost. 
I don't know why the server crashed, but now I have tried it twice and it's working fine.
Thanks @JoshInnis  and @imranzaheer612

**Comment by jrgemignani** [comment]
@KamleshKumar427 What was the dataset you were using the command against?

**Comment by KamleshKumar427** [comment]
> @KamleshKumar427 What was the dataset you were using the command against?

I don't have the exact same dataset now, But It was a dataset of 7-8 nodes(with 2 to 3 properties each) and there were 5 edges between them. Pretty simple dataset.

**Comment by jrgemignani** [comment]
@KamleshKumar427 If you can try to recreate it, or something similar that causes this error, that would be great. Without it, or another dataset that reproduces the error, it is difficult to debug.

**Comment by jrgemignani** [comment]
Additionally, I was unable to recreate the error.

**Comment by KamleshKumar427** [comment]
> Yes, the server crashed and the data was lost. I don't know why the server crashed, but now I have tried it twice and it's working fine. Thanks @JoshInnis and @imranzaheer612

@jrgemignani I tried to recreate the same scenario earlier, but now it is working correctly without any error.
I tried with a nearly similar dataset that cause this error earlier.

**Comment by KamleshKumar427** [comment]
Hello, 
Rolling back transactions is working perfectly fine, I think there was something
else which was taking the server down.
So Closing this issue.
Guys thanks for helping out!
