### ISSUE TITLE
Fork the MariaDB Source Code

### ISSUE THREAD

**Issue by eyab** [apache/age#451]

**Comment by Steves452** [comment]
Hi, I am the new Operations Manager Steve from Vancouver Team.

**Comment by FahadZaheerfzr** [comment]
Hey, I am Fahad Zaheer.

**Comment by fatimafatimaprogrammer** [comment]
hey I'm Urooj Fatima. Excited for this project

**Comment by umer200** [comment]
Hello, Its Syed Umer Tariq. 
To the mooooon !!

**Comment by rafsun42** [comment]
Hi! It's Rafsun.

**Comment by abdulmanann** [comment]
Hi! I'm Abdul Manan. I'm excited to work on this project!

**Comment by abduu11aahh** [comment]
Hi! I am Abdullah. Excited for this project !!

**Comment by waleedahmed0001** [comment]
Hi! I am Waleed, excited to work on this project

**Comment by TalhaMunir-JD** [comment]
Hi I am Talha and I am excited to start working on this project

**Comment by JawadAliAbbasi** [comment]
Hi,
Jawad Ali here
Excited!

**Comment by TalhaMunir-JD** [comment]
The link to the repository which is to be forked is: https://github.com/MariaDB/server

**Comment by fatimafatimaprogrammer** [comment]
here is a link to get started with exploring MariaDB storage Engine https://mariadb.com/kb/en/storage-engines/

**Comment by waleedahmed0001** [comment]
We just have to just fork the MariaDB source code.

[Source Code](https://github.com/MariaDB/server)

But before doing it, it would be great if we consult some online resources for Maria Db. I am mentioning some resources from where we can get help

- The first thing is the MariaDB documentation from where we can complete the basics of MariaDB. 

[MariaDB documentation](https://mariadb.org/documentation/)

- For Maria Db server documentation:

[Server Documentation](https://mariadb.com/kb/en/documentation/)

- For videos, you can get help from this channel:

[YouTube Channel](https://www.youtube.com/channel/UCT2rydFTpxunueD-CtIQoWA)

**Comment by umer200** [comment]
This link is where you can find the link to fork marinade and if interested in previous branches that can also be found here:

**Comment by rafsun42** [comment]
It can help compiling and setting up gdb: https://discord.com/channels/1022177873127280680/1065439249589096459/1078778289306476544

**Comment by abduu11aahh** [comment]
Fork of the maria-server  by AgeDB-Enterprise is [](https://github.com/AgeDB-Enterprise/maria-server)

**Comment by fatimafatimaprogrammer** [comment]
The current process of compiling MariaDB from source Code can be quite cumbersome, with a lot of manual intervention required to ensure that dependencies are correctly installed and updated.

**Comment by abdulmanann** [comment]
I would recommend the guide by Arunesh to fork and setup MariaDB using source code https://www.arunesh.ca/docs/mariaDB/install-maria-db-from-source-code

**Comment by waleedahmed0001** [comment]
Must update your ubuntu to version 22.04 else the installation guide will not work
