### ISSUE TITLE
Match / Create / Set / Remove / Delete / Merge / Call / Yield Clause

### ISSUE THREAD

**Issue by eyab** [apache/age#452]
Match / Create / Set / Remove / Delete / Merge / Call / Yield Clause

**Comment by FahadZaheerfzr** [comment]
Fahad Zaheer

**Comment by fatimafatimaprogrammer** [comment]
hey I'm Urooj Fatima. Excited for this project

**Comment by umer200** [comment]
Hello, Its Syed Umer Tariq !!

**Comment by Steves452** [comment]
Hi, I am the new Operations Manager Steve from Vancouver Team.

**Comment by rafsun42** [comment]
Hi! It's Rafsun.

**Comment by abdulmanann** [comment]
Hi! I'm Abdul Manan. I'm excited to work on this project!

**Comment by abduu11aahh** [comment]
Hi! I am Abdullah. Excited for this project !!

**Comment by waleedahmed0001** [comment]
Hi! I am Waleed, excited to work on this project

**Comment by TalhaMunir-JD** [comment]
Hi I am Talha and I am excited to start working on this project

**Comment by JawadAliAbbasi** [comment]
Hi,
Jawad Ali here
Excited

**Comment by TalhaMunir-JD** [comment]
Match clause:
Match clause is used for searching specific values. It is mostly used with Against function. For example in below query searches the table student where the name column contains the word Talha:
SQL: 
SELECT * FROM student WHERE MATCH(name) AGAINST(‘Talha’);


Create clause:
The create clause is used to create a new table, index, or view in the database. E.g. the following query creates a new table student with fields id, name, and email.
SQL:
CREATE TABLE student (
    id INT PRIMARY KEY,
    name VARCHAR(255),
    email VARCHAR(255)
);


Set clause:
The set clause is used to update the values in a table. E.g. the following query updates the email address of the student whose id is 1
SQL:
UPDATE student SET email='new@email.com' WHERE id=1;


Delete Clause:
Delete clause is used to remove rows from the table. E.g following query removes all rows from the table student whose email column is empty
SQL:
DELETE FROM student where email = ‘’;



Merge Clause:
The merge clause combines data from 2 or more sources into a single table. It is mostly used with union or union all operators. Just like following SQL statement combines data from student and courses tables.
SQL:
SELECT id, name ‘student’ as type FROM students
UNION
SELECT id, courseName, 'course' as type FROM courses;


Call clause:
The call clause is used to execute a stored method. For example the following query calls the a stored procedure get_student_information.
SQL:
CALL get_student_information(1);


Yield clause:
Yield clause is used to return data from a stored method or a function. For example the following function is used to return a result set containing information of students.
SQL:
CREATE PROCEDURE get_student_information (id INT)
BEGIN
    SELECT * FROM students WHERE id = id;
    YIELD;
END;

**Comment by abduu11aahh** [comment]
To add custom extensions to CREATE , you can use PostgreSQL's  parser functions. These functions allow you to define custom rules for parsing text documents . You can create a custom parser function by writing a C language function and then registering it with PostgreSQL using the CREATE FUNCTION command.

**Comment by abdulmanann** [comment]
- Match Clause: A clause used to search for specific values within a table, often used in conjunction with the Against function.
- Create Clause: A clause used to create a new table, index, or view in the database.
- Set Clause: A clause used to update the values of one or more columns in a table.
- Delete Clause: A clause used to remove one or more rows from a table.
- Merge Clause: A clause used to combine data from two or more sources into a single table, often used with the Union or Union All operators.
- Call Clause: A clause used to execute a stored procedure or function.
- Yield Clause: A clause used to return data from a stored procedure or function. Note that this clause is not a standard SQL clause and may not be supported by all database management systems.
- Return Clause: A clause used to return a value from a stored procedure or function. This is similar to the Yield Clause, but is a standard SQL clause and is supported by most database management systems.

**Comment by umer200** [comment]
Match Clause:  used to look for a match for a specific pattern
Create Clause:  used to create a table, index, view, trigger or user-defined functions
Set Clause: used to update/set the value for one or more fields in a table
Delete Clause: used to delete/remove one or more records from the table
Merge Clause: used to merge data from different sources into one target table
Call Clause: used to call procedures (hooks, triggers, user-defined functions)
Yield Clause: used to return a result value from a function without terminating the function which can be used in asynchronous calls.

To use all these functions in our AGE extension we will need to create a wrapper for these functionalities in order to smoothly perform all these operations.
