### ISSUE TITLE
All Functions

### ISSUE THREAD

**Issue by eyab** [apache/age#454]

**Comment by FahadZaheerfzr** [comment]
Fahad Zaheer

**Comment by fatimafatimaprogrammer** [comment]
hey I'm Urooj Fatima. Excited for this project

**Comment by umer200** [comment]
Hello, Its Syed Umer Tariq !!

**Comment by Steves452** [comment]
Hi, I am the new Operations Manager Steve from Vancouver Team.

**Comment by JawadAliAbbasi** [comment]
Hi,
Jawad Ali here
Excited!

**Comment by waleedahmed0001** [comment]
Hi! I am Waleed, excited to work on this project
