### ISSUE TITLE
Frameworks decision for backend and frontend

### ISSUE THREAD

**Issue by eyab** [apache/age#501]

**Comment by saadjameel** [comment]
Lets discuss on frameworks

**Comment by KamleshKumar427** [comment]
Hello everyone! 
I am looking forward to working on this project!

**Comment by AhmarZaidi** [comment]
I'd like to work on this project.

**Comment by MJinH** [comment]
looking forward to working on this project with everyone

**Comment by Nimra-1234** [comment]
Excited to work on that

**Comment by sarthak-19** [comment]
Glad to be part of this project.
For a discussion on framework, I worked on this, please have a look and then continue the discussion : https://github.com/apache/age-viewer/issues/87#issuecomment-1373450762

**Comment by Pratikkapsime** [comment]
Glad to be a part of this project!

**Comment by JYage** [comment]
Hi, I am the new Operations Manager Jayden from Vancouver Team.

**Comment by Steves452** [comment]
Hi, I am the new Operations Manager Steve from Vancouver Team.

**Comment by marodins** [comment]
Please assign me to this task, thank you.

**Comment by pranaviprachi** [comment]
Hello, I'm Prachi Pranavi, I'm excited to start with this project.

**Comment by AdeelAhmedIqbal** [comment]
Hello, I'm Adeel Ahmed. Glad to be a part of this project!

**Comment by M4rcxs** [comment]
Hello, I'm Marcos and I'm so excited to start with this project!

**Comment by farooquememon385** [comment]
Hello, I'm Muhammad Farooq, I'm excited to start with this project.

**Comment by Hasan-Iqtedar** [comment]
Looking forward to study more about this project and contribute.
