### ISSUE TITLE
Data Modeling: Connectivity with PG/MySql

### ISSUE THREAD

**Issue by eyab** [apache/age#502]

**Comment by KamleshKumar427** [comment]
Hello everyone! 
I am looking forward to working on this project!

**Comment by AhmarZaidi** [comment]
I'd like to work on this project.

**Comment by MJinH** [comment]
looking forward to working on this project with everyone

**Comment by sarthak-19** [comment]
Looking forward to collaborate with everyone on this project.

**Comment by saadjameel** [comment]
Excited to start this project.

**Comment by JYage** [comment]
Hi, I am the new Operations Manager Jayden from Vancouver Team.

**Comment by Steves452** [comment]
Hi, I am the new Operations Manager Steve from Vancouver Team.

**Comment by Nimra-1234** [comment]
I am looking forward to work on this project!

**Comment by marodins** [comment]
Please assign me to this task, thank you.

**Comment by KamleshKumar427** [comment]
Hello, I just notice that I am not assigned this task, Please assign me to this task, thank you.

**Comment by pranaviprachi** [comment]
Hello, I'm Prachi Pranavi, I'm excited to start with this project.

**Comment by AdeelAhmedIqbal** [comment]
Hello, I'm Adeel Ahmed. Glad to be a part of this project!

**Comment by farooquememon385** [comment]
Hello, I'm Muhammad Farooq, I'm Happy to be part of this project."

**Comment by Hasan-Iqtedar** [comment]
Looking forward to study more about this project and contribute.
