### ISSUE TITLE
Hybrid queries/Cypher queries module

### ISSUE THREAD

**Issue by eyab** [apache/age#505]

**Comment by AhmarZaidi** [comment]
I'd like to work on this project.

**Comment by MJinH** [comment]
looking forward to working on this project with everyone

**Comment by sarthak-19** [comment]
Looking forward to collaborate with everyone on this project.

**Comment by saadjameel** [comment]
Excited to start this project.

**Comment by JYage** [comment]
Hi, I am the new Operations Manager Jayden from Vancouver Team.

**Comment by Steves452** [comment]
Hi, I am the new Operations Manager Steve from Vancouver Team.

**Comment by Nimra-1234** [comment]
I am looking forward to work on this project!

**Comment by KamleshKumar427** [comment]
Hello everyone!
I am looking forward to working on this project!

**Comment by KamleshKumar427** [comment]
Hello, I just notice that I am not assigned this task, Please assign me to this task, thank you.

**Comment by pranaviprachi** [comment]
Hello, I'm Prachi Pranavi, I'm excited to start with this project.

**Comment by M4rcxs** [comment]
Hello, I'm Marcos and I'm so excited to start with this project!

**Comment by farooquememon385** [comment]
Hello Everyone, I'm Muhammad Farooq, I'm excited to start with this project.

**Comment by Hasan-Iqtedar** [comment]
Looking forward to study more about this project and contribute.
