### ISSUE TITLE
Understanding PostgreSQL and It's Front End/Back End Protocol

### ISSUE THREAD

**Issue by eyab** [apache/age#508]

**Comment by JYage** [comment]
Hi, I am the new Operations Manager Jayden from Vancouver Team.

**Comment by Steves452** [comment]
Hi, I am the new Operations Manager Steve from Vancouver Team.

**Comment by uhayat** [comment]
PgPool-II is a middle where between Client and PostgreSQL database, and It communicate with client and PostgreSQL server using PostgreSQL Front End/Back End(FE/BE) protocol. One need to understand this protocol flows to understand PgPool-II working.

**Comment by KamleshKumar427** [comment]
Hello everyone! 
I am looking forward to working on this project!

**Comment by moeed-k** [comment]
Hello, Moeed here. I'll be working on this task.

**Comment by Zahid07** [comment]
Hello, I'm Zahid and I'll be working on this project.

**Comment by Steves452** [comment]
Hi, I am the new Operations Manager Steve from Vancouver Team.

**Comment by aru-d-at** [comment]
@uhayat Hi, I'll be working on this project later. May I know if you have any resources for reference?

**Comment by uhayat** [comment]
@aru-d-at reference documentation of Frontend/Backend Protocol
https://www.postgresql.org/docs/current/protocol.html

**Comment by JawadAliAbbasi** [comment]
Hi Guys

Excited to work on this project.

**Comment by abdulmanann** [comment]
Hi! I'm excited to work on this project!

**Comment by abduu11aahh** [comment]
Hi! I am Abdullah. Excited for this project !!

**Comment by waleedahmed0001** [comment]
Hi! I am Waleed, excited to work on this project

**Comment by KunjMaheshwari** [comment]
Please assign this issue to me

**Comment by uhayat** [comment]
@eyab  project was completed, issue can be closed.
