### ISSUE TITLE
Implement Cypher Queries in Parser

### ISSUE THREAD

**Issue by eyab** [apache/age#511]

**Comment by uhayat** [comment]
PgPool-II import the parser from PostgreSQL, parser need to be updated for AGE supported queries.

**Comment by KamleshKumar427** [comment]
Hello everyone! 
I am looking forward to working on this project!

**Comment by moeed-k** [comment]
Hello, Moeed here. I'll be working on this task.

**Comment by JYage** [comment]
Hi, I am the new Operations Manager Jayden from Vancouver Team.

**Comment by Steves452** [comment]
Hi, I am the new Operations Manager Steve from Vancouver Team.

**Comment by Zahid07** [comment]
Hello, I'm Zahid and I'll be working on this task.

**Comment by aru-d-at** [comment]
Hi, I will soon be working on this project.

**Comment by JawadAliAbbasi** [comment]
Hi Guys

Excited to work on this project.

**Comment by abdulmanann** [comment]
Hi! I'm excited to work on this project!

**Comment by abduu11aahh** [comment]
Hi! I am Abdullah. Excited for this project !!

**Comment by waleedahmed0001** [comment]
Hi! I am Waleed, excited to work on this project

**Comment by uhayat** [comment]
@eyab  project was completed, issue can be closed.
