### ISSUE TITLE
Getting to know about build struct of PostgreSQL and Apache AGE

### ISSUE THREAD

**Issue by eyab** [apache/age#513]

**Comment by abdinabi123** [comment]
Hello Eya, I will be the OM for this project.

**Comment by uhayat** [comment]
Getting to know the PG build system would help in creating directory structure for AGE extension
Following are the official repositories for PG RPM and Debian packages
https://salsa.debian.org/postgresql/postgresql
https://git.postgresql.org/gitweb/?p=pgrpms.git;a=summary

**Comment by sarthak-19** [comment]
I'm really excited to work on this project.

**Comment by AhmarZaidi** [comment]
I'd like to work on this project. Really exited.

**Comment by Steves452** [comment]
Steve here for back up my interns. Good luck guys.

**Comment by sarthak-19** [comment]
Thank you @Steves452 😀

**Comment by AhmarZaidi** [comment]
@Steves452 Thanks 😄!

**Comment by uhayat** [comment]
@eyab please close this ticket as project was completed.
