### ISSUE TITLE
Create RHEL/CentOS 7 RPMs

### ISSUE THREAD

**Issue by eyab** [apache/age#515]

**Comment by uhayat** [comment]
This would be great task for usability, users will be able to a install age with just few commands like
`yum install postgresql-15-age`
or
`dnf install postgresql-15-age`

**Comment by sarthak-19** [comment]
Looking forward to collaborate with everyone on this project.
Indeed packaging AGE will be quiet handy for user to install extensions

**Comment by AhmarZaidi** [comment]
I'd like to work on this project. Really excited.

**Comment by Steves452** [comment]
Steve here for back up my interns. Good luck guys.

**Comment by uhayat** [comment]
@eyab please close this ticket as project was completed.
