### ISSUE TITLE
Create Bitrock Installer for Apache AGE extension for all support PG versions

### ISSUE THREAD

**Issue by eyab** [apache/age#517]

**Comment by uhayat** [comment]
Bitrock is most widely used installer in PG community so it would make it easier to create AGE Installer

**Comment by sarthak-19** [comment]
Excited to work on this project

**Comment by AhmarZaidi** [comment]
I'd like to work on this project. Really excited.

**Comment by Steves452** [comment]
Steve here for back up my interns. Good luck guys.

**Comment by uhayat** [comment]
@eyab please close this ticket as project was completed.
