### ISSUE TITLE
Create RHEL-9 and Rocky Linux RPMs

### ISSUE THREAD

**Issue by eyab** [apache/age#519]

**Comment by uhayat** [comment]
Create RPM for Rocky Linux 9 which would be compatible for RHEL 9 too.

**Comment by sarthak-19** [comment]
Looking forward to collaborate with everyone on this project.

**Comment by AhmarZaidi** [comment]
I'd like to work on this project. Really excited.

**Comment by Steves452** [comment]
Steve here for my interns. Good luck guys.

**Comment by uhayat** [comment]
@eyab please close this ticket as project was completed.
