### ISSUE TITLE
Based on the input parameters required to develop the following analysis module below, develop a Python module that queries arbitrary graph data, loaded in AGE, in the form of a linked list

### ISSUE THREAD

**Issue by eyab** [apache/age#531]

**Comment by JYage** [comment]
Hi, I am the new Operations Manager Jayden from Vancouver Team.

**Comment by Steves452** [comment]
Hi, I am the new Operations Manager Steve from Vancouver Team.

**Comment by muneebkhan4** [comment]
Hi, I am Muneeb. I am AGE intern. I choose to work on it as my Project-1.

**Comment by Munmud** [comment]
Hi, I am Moontasir, an AGE intern. I choose to work on it as my Project-1.

**Comment by MJinH** [comment]
looking forward to working on this project with everyone

**Comment by Nimra-1234** [comment]
Excited to start that project

**Comment by Pratikkapsime** [comment]
Glad to be a part of this project
