### ISSUE TITLE
Develop an error message function when queries data that does not satisfy the constraints

### ISSUE THREAD

**Issue by eyab** [apache/age#533]

**Comment by Munmud** [comment]
Hi, I am Moontasir, an AGE intern. I choose to work on it as my Project-1.

**Comment by JYage** [comment]
Hi, I am the new Operations Manager Jayden from Vancouver Team.

**Comment by Steves452** [comment]
Hi, I am the new Operations Manager Steve from Vancouver Team.

**Comment by saadjameel** [comment]
Looking forward on working on this project.

**Comment by muneebkhan4** [comment]
Hi, I am Muneeb. I am AGE intern. I choose to work on it as my Project-1.

**Comment by MJinH** [comment]
looking forward to working on this project with everyone
