### ISSUE TITLE
Understand the community detection algorithm using eigenvectors by referring to the referenced papers

### ISSUE THREAD

**Issue by eyab** [apache/age#535]

**Comment by JYage** [comment]
Hi, I am the new Operations Manager Jayden from Vancouver Team.

**Comment by muneebkhan4** [comment]
Hi, I am Muneeb. I am AGE intern. I choose to work on it as my Project-2.

**Comment by Munmud** [comment]
Hi, I am Moontasir, an AGE intern. I choose to work on it as my Project-2.

**Comment by MJinH** [comment]
looking forward to working on this project with everyone

**Comment by muneebkhan4** [comment]
I studied and understood the research papers on comparative study of different Community Detection Algorithms using on eigen values, eigen vectors and modularity factor.

https://www.pnas.org/doi/10.1073/pnas.0601602103
