### ISSUE TITLE
Define the input/output parameters of the algorithm required to perform community detection on arbitrary graph data stored in AGE

### ISSUE THREAD

**Issue by eyab** [apache/age#536]

**Comment by Munmud** [comment]
Hi, I am Moontasir, an AGE intern. I choose to work on it as my Project-2.

**Comment by muneebkhan4** [comment]
Hi, I am Muneeb. I am AGE intern. I choose to work on it as my Project-2.

**Comment by MJinH** [comment]
looking forward to working on this project with everyone
