### ISSUE TITLE
Develop the algorithm module by using Python as an interface and C or Fortran as a computation

### ISSUE THREAD

**Issue by eyab** [apache/age#537]

**Comment by Munmud** [comment]
Hi, I am Moontasir, an AGE intern. I choose to work on it as my Project-2.

**Comment by JYage** [comment]
Hi, I am the new Operations Manager Jayden from Vancouver Team.

**Comment by muneebkhan4** [comment]
Hi, I am Muneeb. I am AGE intern. I choose to work on it as my Project-2.

**Comment by MJinH** [comment]
looking forward to working on this project with everyone
