### ISSUE TITLE
Write a user manual based on the above examples (for general users)

### ISSUE THREAD

**Issue by eyab** [apache/age#538]

**Comment by Munmud** [comment]
Hi, I am Moontasir, an AGE intern. I choose to work on it as my Project-2.

**Comment by JYage** [comment]
Hi, I am the new Operations Manager Jayden from Vancouver Team.

**Comment by muneebkhan4** [comment]
Hi, I am Muneeb. I am AGE intern. I choose to work on it as my Project-2.

**Comment by MJinH** [comment]
looking forward to working on this project with everyone

**Comment by Crazyraturi** [comment]
how can i start contributing
