### ISSUE TITLE
Implement predicate functions: all, any, single, none, isEmpty

### ISSUE THREAD

**Issue by rafsun42** [apache/age#551]
**Is your feature request related to a problem? Please describe.**
While these functions are not present in the Cypher specification, but they are implemented in Neo4j. I found some of them very useful, particularly `all` and `any`.

Descriptions of these functions are exactly similar to the ones described here: https://neo4j.com/docs/cypher-manual/current/functions/predicate.

**Describe the solution you'd like**
N/A

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by jrgemignani** [comment]
@rafsun42 These sound like a good idea to add. I would only suggest creating issues for each one.

**Comment by imranzaheer612** [comment]
Yes, there is only one predicate function defined in age yet, `exists()`.
Others should also be implemented.
https://age.apache.org/age-manual/master/functions/predicate_functions.html

**Comment by rafsun42** [comment]
This issue is broken down into #552, #553, #554, #555, #556.
