### ISSUE TITLE
Any plans for merge actions?

### ISSUE THREAD

**Issue by TropicalPenguin** [apache/age#571]
I just ran into `ERROR:  syntax error at or near "ON"` when trying to use merge actions (`ON CREATE`, `ON MATCH`) in a MERGE clause.

Now I see that work on these was already begun quite some time ago in https://github.com/apache/age/pull/219, raising an issue in the hopes that someone will continue these efforts.

**Comment by jrgemignani** [comment]
@TropicalPenguin It appears to have not been followed through somewhere. I will see if I can't get this moving forward again.

**Comment by LuckyLub** [comment]
I see that the above mentioned pull request #219 has been closed without merging. I was wondering if this functionality is on a roadmap to be implemented?  @jrgemignani, in #219 you mention 'our list of tasks', is there somewhere we can check that list?

**Comment by jrgemignani** [comment]
@LuckyLub No external roadmap yet, we are working on making one available, though.
