### ISSUE TITLE
Scaler function "coalesce()" Syntax

### ISSUE THREAD

**Issue by fatimafatimaprogrammer** [apache/age#572]
I was going through the scaler functions and didn't get the syntax of this particular function **coalesce()** as in its syntax there are two arguments 
first **expression** with opening square bracket **[**
second **expression** with closing square bracket  **]** and asterick **"*"**

![image](https://user-images.githubusercontent.com/63642648/212546757-4b4cb5d0-fbe2-4ae9-84b0-eeeb04a2d7ad.png)

Can someone please explain what does these two parameters refer to?? Are there actually 2 parameters or some other way of writting single expression parameter which i'm not getting.

As in given example they are passing simple expression 

![image](https://user-images.githubusercontent.com/63642648/212546993-f37b6cbb-a9c3-4995-8c3f-b74f70e8b97a.png)

**Comment by rafsun42** [comment]
In regex, `[, expression]*` means 0 or more `,expression`. I think the function takes 1 or more `expression`.
