### ISSUE TITLE
How to load a CSV file.

### ISSUE THREAD

**Issue by Zahid07** [apache/age#573]
I am using apache age and I have a CSV file with a bunch of data in it. I want to populate my graph using the information in the csv file, so can anyone help me with this, and also tell me if I have to preprocess my CSV file so that it is readable by the function which is going to be called by apache age.

**Comment by MuhammadTahaNaveed** [comment]
I think documentation covers this in detail. https://age.apache.org/age-manual/master/intro/agload.html
