### ISSUE TITLE
How to Implement relationship between 2 graphs

### ISSUE THREAD

**Issue by Zahid07** [apache/age#574]
Is there any way that I can implement a relationship between 2 nodes from different graphs, or do I have to make another graph work around that.

**Comment by Munmud** [comment]
There is not way to create a relationship between two nodes in separate graphs. You can write some SQL to create a crosswalk table between two nodes in other graphs, but if you want to create an edge between two nodes, they need to be in the same graph.

You can make a new graph and import both those nodes into that graph and make a relationship. However the id, start_id and end_id that a vertex and edge have are only unique in a per graph level, and trying to link the two vertices together will cause data integrity issues.
