### ISSUE TITLE
Dockerhub apache/age image build file doesn't match with apache/age github repo docker file

### ISSUE THREAD

**Issue by Munmud** [apache/age#575]
Where I can find the build file of [apache/age image](https://hub.docker.com/r/apache/age)

In dockerhub there is a backlink to apache/age repo. But the dockerfile in the github repo doesn't match with Dockerhub image
![Screenshot from 2023-01-19 07-47-36](https://user-images.githubusercontent.com/53787290/213337000-9591229f-5533-4e3e-94af-14177306b32e.png)

**Comment by jrgemignani** [comment]
@Munmud Why was this closed?
