### ISSUE TITLE
Missing Update Files in PG12-v1.1.1 Release

### ISSUE THREAD

**Issue by guruguruguru** [apache/age#577]
Hi,

in the new release for PG12-v1.1.1 there is no extension update file included, only the initial installation file age--1.1.1.sql

Is that expected? How to proceed on an update here? Drop and recreate the extension?
Dropping does not seem to be a good option when there are already objects depending on the extension.

`age=# alter extension age update;
ERROR:  extension "age" has no update path from version "1.1.0" to version "1.1.1"
`

Thanks,
Dennis

**Comment by guruguruguru** [comment]
To add: In the latest PG11 release the update file is also missing:

`./age--1.2.0.sql
./age--0.7.0--1.0.0.sql
./age--1.0.0--1.1.0.sql
./age--0.6.0--0.7.0.sql
./age--0.5.0--0.6.0.sql
`

**Comment by jrgemignani** [comment]
> To add: In the latest PG11 release the update file is also missing:
> 
> `./age--1.2.0.sql ./age--0.7.0--1.0.0.sql ./age--1.0.0--1.1.0.sql ./age--0.6.0--0.7.0.sql ./age--0.5.0--0.6.0.sql `

Per the RELEASE file for PG11 there isn't an upgrade path due to a core table being extended.

**Comment by jrgemignani** [comment]
There isn't a difference for PG12, though. I will need to check if it just needs an empty update file.

**Comment by jrgemignani** [comment]
@guruguruguru The new draft release has the script added.

**Comment by guruguruguru** [comment]
@jrgemignani thank you! yes combining the issues was not the best idea, sorry for that!

**Comment by guruguruguru** [comment]
age=# \dx
                 List of installed extensions
  Name   | Version |   Schema   |         Description          
---------+---------+------------+------------------------------
 age     | 1.1.0   | ag_catalog | AGE database extension
 plpgsql | 1.0     | pg_catalog | PL/pgSQL procedural language
(2 rows)

age=# alter extension age update;
ALTER EXTENSION
age=# \dx
                 List of installed extensions
  Name   | Version |   Schema   |         Description          
---------+---------+------------+------------------------------
 age     | 1.1.1   | ag_catalog | AGE database extension
 plpgsql | 1.0     | pg_catalog | PL/pgSQL procedural language
(2 rows)

Worked now, thank you!

**Comment by jrgemignani** [comment]
@guruguruguru If this has resolved the issue for you, please close it at your earliest convenience.
