### ISSUE TITLE
"Fixing missing packages and vulnerabilities in age-viewer package when installing from GitHub"

### ISSUE THREAD

**Issue by moiz697** [apache/age#579]
i am trying to install the age-viewer from GitHub by following these steps:

Cloning the repository
Changing directory to age-viewer
Running "npm run setup"
However, I am encountering issues with missing packages and 34 vulnerabilities (3 moderate, 22 high, 9 critical). I have attempted to resolve this by running "npm audit fix --force", but it did not work.

I am looking for a solution to fix the missing packages and vulnerabilities in the age-viewer package that I am trying to install from GitHub.

**Comment by jrgemignani** [comment]
@moiz697 @eya This issue belongs under https://github.com/apache/age-viewer/issues

**Comment by AbdulSamad4068** [comment]
@moiz697 Have you tried switching to a different registry or mirror by using the --registry flag with the npm command, for example:

`npm audit fix --force --registry=https://registry.npmjs.org/`
This ensures that npm uses the default npm registry for package retrieval.
After applying the fixes, run `npm audit` again to verify that the missing packages and vulnerabilities are resolved.
