### ISSUE TITLE
Unable to connect Apache Age-Viewer to PostgreSQL Database

### ISSUE THREAD

**Issue by moiz697** [apache/age#580]
I have tried all the steps provided in the documentation to connect Apache Age-Viewer to my PostgreSQL database, but I am still unable to connect. I have verified that the PostgreSQL server is running, the user and password are correct and have the necessary permissions, and the specified port (5455) is open and accessible. But I still can't connect.

I am using the following versions:

Apache Age-Viewer: 14.16.0
PostgreSQL: 12.13

**Comment by jrgemignani** [comment]
@moiz697 @eyab This issue belongs under https://github.com/apache/age-viewer/issues

**Comment by jrgemignani** [comment]
Please close this issue once it is added under the viewer.

**Comment by moaz178** [comment]
It is possible that there is some issues related to the versions. I suggest you change your postgres and AGE versions. Here is the link for a step-by-step guide on how to do it and which versions are the best.

https://theundersurfers.netlify.app/age-installation/

Try to use the steps in this article. Video is also attached for guidance.

**Comment by M4rcxs** [comment]
Please try updating both your PostgreSQL and Apache AGE, as there may be issues with older versions.

**Comment by Omar-Saad** [comment]
Try first to run postgres and age in the terminal and make sure that they are working good.
Also make sure that you are using the correct user name and password while connecting to the database.
Another thing the default postgres port is 5432 not 5455 unless you changed it.
If you still facing  an issue you can follow this tutorial to install and run age-viewer: 
https://dev.to/omarsaad/step-by-step-guide-to-install-apache-age-viewer-1o5d

**Comment by dukeofhazardz** [comment]
Check if there are any firewalls or network restrictions that may be blocking the connection. You can try temporarily disabling the firewall or any other network security software and attempt to connect again. And also try to check the PostgreSQL server logs for any error messages related to the connection attempt. The logs may provide more information on why the connection is failing.

**Comment by mahinash26** [comment]
I faced a similar problem, so I referred to these two links:
1. [https://age.apache.org/age-manual/master/intro/setup.html#pre-installation](https://age.apache.org/age-manual/master/intro/setup.html#pre-installation)
2. [https://theundersurfers.netlify.app/age-installation/](https://theundersurfers.netlify.app/age-installation/)
