### ISSUE TITLE
gradle-wrapper.jar missing in jdbc driver

### ISSUE THREAD

**Issue by abdulmanann** [apache/age#581]
I am encountering an issue when attempting to build the JAR file for the age JDBC driver in order to test it in my Java project. Upon running the command "./gradlew assemble" using the Gradle wrapper, I receive the following error message:

```bash
 ./gradlew assemble
Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain
Caused by: java.lang.ClassNotFoundException: org.gradle.wrapper.GradleWrapperMain
```
I have verified that the gradle/wrapper directory is missing the gradle-wrapper.jar file.

**Comment by fatimafatimaprogrammer** [comment]
Observing this error message 
Your gradle wrapper is missing, broken or corrupted.


**Restoring gradle wrapper:**

It used to be that you needed to add a wrapper task to your build.gradle to restore gradle wrapper and all its dependencies. For instance:

task wrapper(type: Wrapper) {
    gradleVersion = '4.1'
}
Newer versions of gradle do not require this. It is now a built-in task. Just run:

gradle wrapper
You can also supply additional flags to specify versions etc

gradle wrapper --gradle-version 6.2 --distribution-type all
When you run this task, a gradle wrapper script, and the required jar files are added to your source folders. Properties are stored in gradle/wrapper/gradle-wrapper.properties

(You may need to install gradle locally to run this. brew install gradle on mac for instance. See more detailed instructions [here](https://docs.gradle.org/current/userguide/installation.html#installation))

**Comment by abdulmanann** [comment]
Yes, it will work but there will be no point of using the gradle wrapper then. I have added the missing jar file and updated the README in PR #584. Kindly look into it

**Comment by fatimafatimaprogrammer** [comment]
> Yes, it will work but there will be no point of using the gradle wrapper then. I have added the missing jar file and updated the README in PR #584. Kindly look into it

okay thats Great 
If this has answered you question adequately, please close the ticket.

**Comment by mahinash26** [comment]
You are seeing an error message when attempting to build the JAR file for the age JDBC driver using the Gradle wrapper. The error message suggests that there may be an issue with the Gradle wrapper configuration in your project. To resolve the issue, try running the **./gradlew wrapper** command to download and install the necessary wrapper files, verify that the **gradle-wrapper.jar** file is present in the **gradle/wrapper** directory, and delete the gradle and .gradle directories if necessary. If none of these steps work, try manually downloading and installing the Gradle distribution for your project.

**Comment by AbdulSamad4068** [comment]
You have to ensure that file is present in the "gradle/wrapper" directory of your project. Ensure it hasn't been accidentally deleted or moved.

verify that you have a valid Gradle installation on your system and that the correct Gradle version is specified in your project's configuration. Check the "gradleVersion" property in files like "build.gradle" or "settings.gradle" and make any necessary corrections.

If the issue persists, you can regenerate the Gradle wrapper files. Use the appropriate command, either `gradle wrapper` or `gradlew wrapper`, in your project's root directory. This will recreate the necessary Gradle wrapper files based on your Gradle installation and project configuration.

Now build the JAR file, execute the command `./gradlew assemble` in your project's root directory. This will initiate the build process using the Gradle wrapper.

**Comment by abdulmanann** [comment]
Thank you for your responses. The issue lies because the wrapper file is missing. As I stated above, installing gradle will work but there will be no point in using the gradle wrapper then. I have added the missing jar file in PR https://github.com/apache/age/pull/584. That will add the missing jar file and then there will be no need to install the gradle separately.
