### ISSUE TITLE
Functional requirements for PSQL-based CLI tool for AGE

### ISSUE THREAD

**Issue by aked21** [apache/age#631]

**Comment by aked21** [comment]
This is to define the requirements / features of the CLI-based query tool and the step-by-step tasks associated with the project.

**Comment by ibrarahmad** [comment]
I will take care of it

**Comment by aked21** [comment]
Thank you so much @ibrarahmad

**Comment by JawadAliAbbasi** [comment]
Hi Guys

Excited to work on this project.

**Comment by carlasanches** [comment]
Hello, I'm Carla. I'm excited to start with this project.

**Comment by kenwoon** [comment]
Hello! I am Ken, a newly appointed intern for this project, and I look forward to working with everyone here.

**Comment by fatimafatimaprogrammer** [comment]
hey I'm Urooj Fatima. Excited for this project

**Comment by moiz697** [comment]
excited to work on this project
