### ISSUE TITLE
How to use this Apache Age from .Net 7.0?

### ISSUE THREAD

**Issue by glazkovalex** [apache/age#640]
For Apache Age there is a driver for Python, Golang and a couple of other languages, but there is no driver in C# for .Net 7.0. How to use this graph DBMS from .Net 7.0?

If there is, give a link to an example connection from .Net.

**Comment by FahadZaheerfzr** [comment]
There is no driver for .Net yet but what you can do is use some existing library to connect to PostgreSQL and then load Apache Age using PostgreSQL queries. Once you load it you can run the queries just like in PostgreSQL. For loading Apache Age make sure you have Apache Age installed and set up in localhost.

To load Apache Age use these commands

```
CREATE EXTENSION IF NOT EXISTS age;
LOAD 'age';
SET search_path = ag_catalog, "$user", public;
```

**Comment by uhayat** [comment]
Use Npgsql which is PG driver for C#. I ideally there should be a AGE plugin for Npgsql.

**Comment by hammadsaleemm** [comment]
hammadsaleem1100@gmail.com
How to use this Apache Age from .Net 7.0? #640

To use it from .NET 7.0, you can follow these general steps:

Install the Npgsql library, which is the .NET data provider for PostgreSQL.

Install Apache Age as a PostgreSQL extension.

Connect to your PostgreSQL database using Npgsql.

Execute Age queries in PostgreSQL using the Npgsql command object.

Here's an example C# code snippet to connect to a PostgreSQL database and execute an Age query:

using Npgsql;

var connString = "Host=myserver;Username=mylogin;Password=mypass;Database=mydatabase";
using var conn = new NpgsqlConnection(connString);
conn.Open();

var cmd = new NpgsqlCommand("MATCH (n) RETURN n", conn);
var reader = cmd.ExecuteReader();
while (reader.Read())
{
    // Process the results
}

reader.Close();

Note that the Age query is a standard PostgreSQL query with the syntax of the Cypher query language. You can also use the Npgsql adapter to execute Age commands, which have a similar syntax to Cypher queries.

**Comment by M4rcxs** [comment]
An alternative is to use [Npgsql.org ](https://www.npgsql.org) whose is a driver of PostgreSQL for C#, but for now does not exist a driver for Apache AGE from .NET, maybe in the future this feature will be developed to Npgsql

**Comment by eyab** [comment]
@glazkovalex Any updates on this issue?

**Comment by glazkovalex** [comment]
> [hammadsaleem1100@gmail.com](mailto:hammadsaleem1100@gmail.com) Как использовать Apache Age из .Net 7.0? #640
> 
> Чтобы использовать его из .NET 7.0, вы можете выполнить следующие общие шаги:
> 
> Установите библиотеку Npgsql, которая является поставщиком данных .NET для PostgreSQL.
> 
> Установите Apache Age как расширение PostgreSQL.
> 
> Подключитесь к базе данных PostgreSQL с помощью Npgsql.
> 
> Выполняйте запросы Age в PostgreSQL с помощью командного объекта Npgsql.
> 
> Вот пример фрагмента кода C# для подключения к базе данных PostgreSQL и выполнения запроса Age:
> 
> использование Npgsql;
> 
> var connString = "Host=myserver;Имя пользователя=mylogin;Пароль=mypass;База данных=mydatabase"; используя var conn = new NpgsqlConnection(connString); конн.Открыть();
> 
> var cmd = new NpgsqlCommand("MATCH (n) RETURN n", conn); вар читатель = cmd.ExecuteReader(); while (reader.Read()) { // Обрабатываем результаты }
> 
> читатель.Закрыть();
> 
> Обратите внимание, что запрос Age — это стандартный запрос PostgreSQL с синтаксисом языка запросов Cypher. Вы также можете использовать адаптер Npgsql для выполнения команд Age, синтаксис которых аналогичен запросам Cypher.



> [hammadsaleem1100@gmail.com](mailto:hammadsaleem1100@gmail.com) How to use this Apache Age from .Net 7.0? #640
> 
> To use it from .NET 7.0, you can follow these general steps:
> 
> Install the Npgsql library, which is the .NET data provider for PostgreSQL.
> 
> Install Apache Age as a PostgreSQL extension.
> 
> Connect to your PostgreSQL database using Npgsql.
> 
> Execute Age queries in PostgreSQL using the Npgsql command object.
> 
> Here's an example C# code snippet to connect to a PostgreSQL database and execute an Age query:
> 
> using Npgsql;
> 
> var connString = "Host=myserver;Username=mylogin;Password=mypass;Database=mydatabase"; using var conn = new NpgsqlConnection(connString); conn.Open();
> 
> var cmd = new NpgsqlCommand("MATCH (n) RETURN n", conn); var reader = cmd.ExecuteReader(); while (reader.Read()) { // Process the results }
> 
> reader.Close();
> 
> Note that the Age query is a standard PostgreSQL query with the syntax of the Cypher query language. You can also use the Npgsql adapter to execute Age commands, which have a similar syntax to Cypher queries.

Thank you!

**Comment by rafsun42** [comment]
@LakshyaNandwana Does your query work on command line?

**Comment by LakshyaNandwana** [comment]
@rafsun42 Yes, the query can be executed from the command line.

**Comment by rafsun42** [comment]
@LakshyaNandwana Have you loaded age and add ag_catalog to search path from your c# code?

**Comment by LakshyaNandwana** [comment]
@rafsun42 Can you pleae send me the code on how to add ag_catalog to search path from c# code?

**Comment by rafsun42** [comment]
@LakshyaNandwana That is a command just like SELECT. So you should be able to run it as you run SELECT from C# code.

**Comment by LakshyaNandwana** [comment]
@rafsun42 Thank you, the query works after adding the ag_catalog to search path.

**Comment by hhaynes-rower** [comment]
I suppose we can all shift forward to talk about .NET 8 now. 👍 😄 

Of course this is about more than simply getting queries out to Postgres but also about efficient compute and memory handling on the "application" side of things. I'll be looking at ways to build a convenient wrapper/extension for Npgsql and have alreayd started looking at some other attempts that have been made over the years.

**Comment by Allison-E** [comment]
Hi. I've created an AGE driver for .NET, and it currently supports only .NET 8 (support for other versions and .NET Standard coming soon). You can check it out here: [https://github.com/Allison-E/pg-age](https://github.com/Allison-E/pg-age).

To know how it works, you should take a look at the [wiki](https://github.com/Allison-E/pg-age/wiki) (even though it's still under construction).

Your contributions and suggestions are welcomed 😄.

**Comment by houstonhaynes** [comment]
Emannuel this is awesome! I've forked it and will spend some quality time with it over the US holiday this week. Thanks!

**Comment by glazkovalex** [comment]
> Hi. I've created an AGE driver for .NET, and it currently supports only .NET 8 ...
> ...
> Your contributions and suggestions are welcomed 😄.

@Allison-E, hellow!
A very interesting project! 
Support.Net.Standard is completely optional, since Npgsql.Entity Framework is Core.PostgreSQL is still under .Net 8. 
It would be very useful to support Linq in queries, that is, [hybrid queries to relational data and graph data](https://dev.to/dukeofhazardz/exploring-apache-age-hybrid-queries-49p8) in a single Linq query, as well as mapping the results to objects! So that you can combine a Linq query to relational data with a text subquery in the Cypher Query Language via [User-defined function](https://learn.microsoft.com/en-us/ef/core/querying/user-defined-function-mapping), [EF.Functions](https://learn.microsoft.com/en-us/ef/core/querying/database-functions) and [Interceptors](https://learn.microsoft.com/en-us/ef/core/logging-events-diagnostics/interceptors). That is, so that the Entity Framework Core outputs, for example, these queries:


```demo=# SELECT p.name FROM Persons AS p WHERE p.id in (
demo(# SELECT id FROM cypher('my_graph', $$
demo$# MATCH (v:Person) RETURN v.id $$)
demo(# AS (id int));
```
```
    name
------------
 "Daniel"
 "Emmanuel"
(2 rows)
```
