### ISSUE TITLE
entry_id error while loading csv

### ISSUE THREAD

**Issue by DeoLeung** [apache/age#644]
**Describe the bug**
```bash
ERROR:  entry_id must be 1 .. 281474976710655
```
```sql
SELECT * FROM create_graph('neurond');
SELECT create_vlabel('neurond','entity');
SELECT * FROM load_labels_from_file('neurond',
                             'entity,
                             '/var/lib/postgresql/data/entity.csv');
```
loading a file with ~240k line and id ranging from 10k to 330k, after processing for 50s then it fails

**How are you accessing AGE (Command line, driver, etc.)?**
raw sql

**Environment (please complete the following information):**
- Version: [e.g. 0.4.0]
postgresql 12.13
age v1.1.1-rc1

**Comment by DeoLeung** [comment]
similar for edges, from a file of around 100k
```bash
ERROR:  label_id must be 1 .. 65535
```
```sql
SELECT create_elabel('neurond','belongs');
SELECT * FROM load_edges_from_file('neurond',
                             'belongs',
                             '/var/lib/postgresql/data/relation.csv');
```

**Comment by jrgemignani** [comment]
This could be due to a patch for the PG11 version needing to be applied here.

**Comment by fatimafatimaprogrammer** [comment]
According on the error messages you supplied, there appears to be a problem with the label id and entry id values when attempting to import data from CSV files into the 'neurond' database.

The error messages suggest that the label id must be between 1 and 65535 and the entry id must be between 1 and 281474976710655.
It's possible that the values in your CSV files are outside of the permitted ranges, creating the errors.

One possible option noted in the comments is to apply a PostgreSQL 11 patch.
It's vital to note that keeping your database software up to date with the newest patches and upgrades is typically a good idea, since these frequently include critical bug fixes and security improvements.

**Comment by Munmud** [comment]
I found the same error. While debugging I found that this is happening because its getting some garbage value at the end of csv file.

**Comment by eyab** [comment]
@DeoLeung Could you please update us on this issue?

**Comment by ticomse** [comment]
My situation:

I used the CREATE command to create around 340,000 vertices.
Apache Age automatically assigned ids with values like '20829148276967924'. (I believe that this is a 64-bit number.)

When I try to load vertices from a file, I get this error:
psycopg2.errors.InvalidParameterValue: entry_id must be 1 .. 281474976710655

I'm pretty sure that 281474976710655 is MAXINT for a 48-bit integer.

It seems like psycopg2 has an input validation check that causes it to discard ids that are too large.

Any thoughts about how to fix or workaround this issue?

Thanks

**Comment by LuckyLub** [comment]
I ran into the same issue.

```
psycopg2.errors.InvalidParameterValue: label_id must be 1 .. 65535
```
Though I don't understand why there would be a range for the label ids, I have checked and the start_id and end_id do not exceed the indicated range of 1-65535. 

The file resulting in the error: [edges_afwijking_afhandeling.csv](https://github.com/apache/age/files/13675428/edges_afwijking_afhandeling.csv)
PG: 14
AGE: 1.4
python: 3.12
psycopg2==2.9.9

**Comment by jrgemignani** [comment]
This is referring to the label id which is imbedded in the id. But, unless you are creating more than 65535 distinct labels, it shouldn't complain.

**Comment by jrgemignani** [comment]
We have a new version of Apache AGE and Python driver. Is this still an issue?

**Comment by aa-dish** [comment]
Is there any final solution of the label_id error 1......65535 error?
