### ISSUE TITLE
Can we use AGE with postGIS togeteher ?

### ISSUE THREAD

**Issue by bioinfornatics** [apache/age#657]
Dear,

I would like both modelize a graph of data and walking through and in same time I would like perform some [geospatial](https://postgis.net/) query.
So can can we combine these extensions for a same dataset ?

Thanks

Best regards

**Comment by FahadZaheerfzr** [comment]
Yes you can, by using PostgreSQL you can use both AGE and PostGIS by adding them to the database to provide additional functionality. By combining AGE and PostGIS, you can model and query both graph and geospatial data in a single PostgreSQL database. This allows you to perform graph algorithms and queries on your graph data, and also perform geospatial operations on your geospatial data, all within a single integrated system.

**Comment by FahadZaheerfzr** [comment]
Yes, you can use both AGE and PostGIS in PostgreSQL by adding them to the database to provide additional functionality. You can model and query both graph and geospatial data in a single PostgreSQL database by combining AGE and PostGIS. This enables you to run graph algorithms and queries on your graph data, as well as geospatial operations on your geospatial data, all from a single integrated system.

**Comment by bioinfornatics** [comment]
thanks a lot @FahadZaheerfzr that seems promising

have a nice day
