### ISSUE TITLE
Bulk import/export using Arrow ?

### ISSUE THREAD

**Issue by lmeyerov** [apache/age#669]
We are thinking about using AGE as part of some compute-tier systems, so fast ingest/export matters. Think 10k-100M edges. If we have parquet or arrow format data, is there a good path here, and any doc pointers? (I could not find)

**Comment by rafsun42** [comment]
Have you considered using AGE's python driver with PyArrow?

**Comment by lmeyerov** [comment]
Is there an example here? I'm worried if it just converts to odbc underneath

**Comment by rafsun42** [comment]
The python driver is a wrapper of psycopg2, which is a wrapper of libpq. Libpq is more specific to Postgres so you may get better performance. Generally, the driver builds SQL query string and executes through psychopg2. 

I don't have exact performance metrics for large data sets. If you want to run benchmark test, I may be able to assist you here.

Link to the driver: https://github.com/apache/age/tree/master/drivers/python

**Comment by lmeyerov** [comment]
Thanks -- yes, odbc for postgres is too slow for our interactive compute workloads. I think arrow community is making a new protocol w postgres support, but I haven't tracked that nor know whether it'd combine well with AGE

**Comment by eyab** [comment]
@lmeyerov do you have any updates on this? Did you find a solution?

**Comment by lmeyerov** [comment]
No, we are still curious about bulk ingest/export for use with analytics pipelines, esp subsecond interactive & GPU at 100MB-10GB scales

**Comment by lmeyerov** [comment]
I think ADBC is the relevant protocol snowflake and others are adopting here
