### ISSUE TITLE
add geometry to vertex attributes

### ISSUE THREAD

**Issue by YouthGoblin** [apache/age#682]
**Is your feature request related to a problem? 

yes, I want to use the geometry type of postgis directly as a vertex and create an index for it

**Describe the solution you'd like**

At present, for the graphical relationship of geometric type, first manually calculate their positional relationship, and then add their name to the graph, regardless of the addition or the final query, the process is very cumbersome, I hope there is a more concise way to deal with them relationship and can quickly query

**Comment by maazzzzz** [comment]
Hi @YouthGoblin, sorry for the late reply. could you please elaborate on your workflow a bit more? perhaps share the queries for the workflow that you've described.

**Comment by eyab** [comment]
@YouthGoblin can we have more details in this regard, please?
