### ISSUE TITLE
MATCH (A) MATCH (A {prop: 'val'} ) ... Fails when it should not.

### ISSUE THREAD

**Issue by dehowef** [apache/age#701]
**Describe the bug**

There is unintended behavior when a user tries to MATCH a node with property constraints after already MATCHing a node with the same variable name.

**How are you accessing AGE (Command line, driver, etc.)?**

Command Line

**What data setup do we need to do?**

Have AGE running.

**What is the necessary configuration info needed?**
- N/A

**What is the command that caused the error?**
```pgsql
SELECT * FROM cypher('my_graph', $$ MATCH (a) MATCH (a {prop:'val'}) RETURN a $$ ) AS (a agtype);

```
```
postgres=# SELECT * FROM cypher('my_graph', $$ MATCH (a) MATCH (a {prop:'val'}) RETURN a $$ ) AS (a agtype);
2023-02-22 01:29:05.230 PST [59866] ERROR:  missing FROM-clause entry for table "a" at character 34
2023-02-22 01:29:05.230 PST [59866] STATEMENT:  SELECT * FROM cypher('pilots', $$ MATCH (a) MATCH (a {s:'as'}) RETURN a $$ ) AS (a agtype);
ERROR:  missing FROM-clause entry for table "a"
LINE 1: SELECT * FROM cypher('my_graph', $$ MATCH (a) MATCH (a {prop:'val'...
```

**Expected behavior**

The program should detect the variable and return the according result. The RTE is not being detected and the program is throwing an error.

**Environment (please complete the following information):**
- Version: PG11 Version 1.1.X, Fedora OS 36

**Additional context**

**Comment by dehowef** [comment]
The issue seems to lie in transform_cypher_node() in cypher_clause.c
--

Because of how previously transformed match clauses are stored in the RTE, they are undetectable by create_property_constraints(). All of previous clauses are pooled into an RTE with the alias "_', and the find_rte() logic responsible detecting previously declared variables cannot produce property_constraints.

**Comment by jrgemignani** [comment]
@dehowef I checked and this issue goes back to, at least, 1.0.0, that was as far back as I went. It is also in PG12 and PG13 versions. So, it isn't anything new and was likely just overlooked as a case.
