### ISSUE TITLE
The cypher function terminated the connection due to missing query argument

### ISSUE THREAD

**Issue by mohayu22** [apache/age#718]
**Bug Description:**
I ran a query on my graph using the following code:
`SELECT * FROM cypher('demo_graph') as (v agtype);`

However, I forgot to include the query argument for the Cypher function. As a result, the server closed the connection unexpectedly, and I received the error message.
```
server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
The connection to the server was lost. Attempting reset: Failed.
```
**Expected Result:**
I was expecting an exception to be raised (throw an Error)  instead of the connection being terminated.

**Setup:**
Command Line: start postgres with pg_ctl --> connect to database with psql

**Environment:**
PostgreSQL v11.18 | Latest Apache Age | Ubuntu 20.04.5 LTS

**Comment by jrgemignani** [comment]
@mohayu22 Thank you for catching this. It appears that when I added in some code for driver integration, an edge case was overlooked. I will correct it.

**Comment by jrgemignani** [comment]
@mohayu22 The master has been updated with a fix for this issue.
