### ISSUE TITLE
Why AGE does not consider path as a list?

### ISSUE THREAD

**Issue by Zainab-Saad** [apache/age#729]
There are certain list functions such as `head()` and `last()` that return the first and last element of the list but these functions fail on the path variable that is a list too. For example, I have the following query where p is _list of vertices and edges_
`SELECT * FROM cypher('graph', $$
MATCH p = (u {name : "A"})-[e: DISTANCE*]->(v {name : "C"})
RETURN head(p)
$$) AS (result agtype);
`
The following error is shown

> ERROR:  head() argument must resolve to a list or null

What is the reason for this?

**Comment by mohayu22** [comment]
Path may look like a list but it is not the same thing as a list in cypher. Therefore, the head() function cannot be used directly on a path object. Instead, you can extract the vertices and edges from the path using the nodes() and relationships() functions respectively, and then apply the head() function to the resulting lists. For example, to get the first vertex and first edge of the path, you can modify your query like this:

```
SELECT * FROM cypher('graph', $$
    MATCH p = (u {name : "A"})-[e: DISTANCE*]->(v {name : "C"})
    RETURN head(nodes(p)), head(relationships(p)) 
$$) AS (res1 agtype, res2 agtype);
```

**Comment by Zainab-Saad** [comment]
Alright, thanks for clarifying.
