### ISSUE TITLE
How to apply arithmetic operations on a property of variable length edge 

### ISSUE THREAD

**Issue by Zainab-Saad** [apache/age#730]
If I have a scenario in which there are three vertices A, B and C. Going from A -> B takes cost 2 and then B -> C takes cost 3. If I have to go from A -> C, I can query on the variable length edge using `()-[e:label*]->()`. But this would return the path and if we get all the intermediate edges by `relationships(p)`, we get list of edges. How do we sum the cost 2 and 3 here from this list of edges?

**Comment by mohayu22** [comment]
You can use the [sum()](https://age.apache.org/age-manual/master/functions/aggregate_functions.html#sum) aggregate function to add up the cost property of each edge in the path. Here's an example query:
```
WITH relationships(path) as edges
RETURN sum(edges.cost) as total_cost
```

**Comment by Zainab-Saad** [comment]
Did you try the query? Because it gives me an error `ERROR:  array index must resolve to an integer value`.

**Comment by jrgemignani** [comment]
@Zainab-Saad @mohayu22 The sum() aggregate function only works against a column. So, it really will only sum a column of data. However, the data being returned and wanted summed is a row element that is an array of edges.

Baring an existing cypher of PG function, which, off the top of my head I can't think of any, you would need to write your own function to apply against that array to return the sum.

**Comment by M4rcxs** [comment]
I think there's a way to achieve this, which involves writing your own function. 
Maybe it can help you [Using Cypher](https://age.apache.org/age-manual/master/advanced/advanced.html).

**Comment by Zainab-Saad** [comment]
With PR # 736 being merged, the property of variable length edge can be summed as 
`MATCH p = (a)-[e:label*]->(b)
UNWIND (relationships(p)) AS x RETURN SUM(x.<edge_property_name>)
`
