### ISSUE TITLE
How to show all graphs in AGE? 

### ISSUE THREAD

**Issue by bigplaice** [apache/age#735]
Hi, 

One question about basic operation, that is, how to list all existing graphs in AGE. 
I failed to find  the answer in document. 

Thanks,
Steven

**Comment by im-aditya30** [comment]
You can get using the following command: `SELECT * FROM ag_catalog.ag_graph;`

**Comment by bigplaice** [comment]
Thank you,  Aditya, Tito! This is exactly what I need.
