### ISSUE TITLE
"Error: CALL not supported yet" on the CALL function on the regression tests

### ISSUE THREAD

**Issue by panosfol** [apache/age#737]
**Describe the bug**
Running the regression tests line by line I get an error
 ```sh
postgres=# SELECT * FROM cypher('cypher_call', $$CALL sqrt(64)$$) as (sqrt agtype);
2023-03-08 19:38:02.077 EET [6722] ERROR:  CALL not supported yet at character 39
2023-03-08 19:38:02.077 EET [6722] STATEMENT:  SELECT * FROM cypher('cypher_call', $$CALL sqrt(64)$$) as (sqrt agtype);
ERROR:  CALL not supported yet
```

**How are you accessing AGE (Command line, driver, etc.)?**
- Command line

**What data setup do we need to do?**
```pgsql
LOAD 'age';
SET search_path TO ag_catalog;



SELECT create_graph('cypher_call');

SELECT * FROM cypher('cypher_call', $$CREATE ({n: 'a'})$$) as (a agtype);
SELECT * FROM cypher('cypher_call', $$CREATE ({n: 'b'})$$) as (a agtype);

CREATE SCHEMA call_stmt_test;

CREATE FUNCTION call_stmt_test.add_agtype(agtype, agtype) RETURNS agtype
    AS 'select $1 + $2;'
    LANGUAGE SQL
    IMMUTABLE
    RETURNS NULL ON NULL INPUT;

/* 
 * CALL (solo) 
 */

SELECT * FROM cypher('cypher_call', $$CALL sqrt(64)$$) as (sqrt agtype);
```

**What is the command that caused the error?**
```pgsql
postgres=# SELECT * FROM cypher('cypher_call', $$CALL sqrt(64)$$) as (sqrt agtype);
```
```
ERROR:  CALL not supported yet
```

**Expected behavior**
According to the output of the regression tests, it should have returned :
```SELECT * FROM cypher('cypher_call', $$CALL sqrt(64) YIELD sqrt$$) as (sqrt agtype);
 sqrt 
------
 8.0
(1 row)
```

**Environment (please complete the following information):**
- PostgreSQL Version = 12_14
- apacheAGE version release/PG12/1.1.1

**Comment by dehowef** [comment]
Do the regression tests pass when you run them?

**Comment by dehowef** [comment]
Is this a recurring error that happens? More info would be helpful

**Comment by dehowef** [comment]
It would be great if you could describe what is going on in more detail

**Comment by panosfol** [comment]
Yeah it happens everytime i run the regression test manually. So basically I start with 
```pgsql
LOAD 'age';
SET search_path TO ag_catalog;



SELECT create_graph('cypher_call');

SELECT * FROM cypher('cypher_call', $$CREATE ({n: 'a'})$$) as (a agtype);
SELECT * FROM cypher('cypher_call', $$CREATE ({n: 'b'})$$) as (a agtype);

CREATE SCHEMA call_stmt_test;

CREATE FUNCTION call_stmt_test.add_agtype(agtype, agtype) RETURNS agtype
    AS 'select $1 + $2;'
    LANGUAGE SQL
    IMMUTABLE
    RETURNS NULL ON NULL INPUT;
```

which runs normally. After that when i reach the line 
```pgsql
SELECT * FROM cypher('cypher_call', $$CALL sqrt(64)$$) as (sqrt agtype);
```
I dont get the expected output , I get an error that reads : CALL not supported yet. I haven't done anything else to walk you through i think maybe it is the postgresql 12 that i have that makes it like that. Im planning on install postgresql11 and checking again to see if the error persists

**Comment by dehowef** [comment]
What about when  use CALL from the commandline in postgres? Same thing?

**Comment by panosfol** [comment]
just changed to version 11 and it works fine...let me check with version12 again and try to run CALL by itself

**Comment by panosfol** [comment]
after testing some things, the CALL statement seems to be working ok when use in other context. I created a procedure and used the CALL statement to execute it and i didnt have a problem with that

**Comment by dehowef** [comment]
Keep me updated if anything else comes up~

**Comment by panosfol** [comment]
I want to look into it a bit more. Do you know maybe where should i search in the source code to find more about this?

**Comment by dehowef** [comment]
I can't say because I'm not using your machine. If you document the issue more maybe I can help you

**Comment by panosfol** [comment]
what more info should i provide?

**Comment by dehowef** [comment]
You can troubleshoot and try to see what's wrong, from what it looks like to me it seems like this might be a user error on your part, or something that is an issue on your local machine. Thanks

**Comment by panosfol** [comment]
Thank you i will check it out!

**Comment by panosfol** [comment]
After some tests i've figure out it was a user error on my side so we should consider this issue resolved
