### ISSUE TITLE
Recent commits are not reflected to AGE local repository after pulling the commits from remote

### ISSUE THREAD

**Issue by Zainab-Saad** [apache/age#761]
I am trying to pull the recent changes in AGE repository to my local repository but am unable to do it.
The steps I follow are:
`git pull`
`git log` // this shows the recent commits to the repository
Then I rebuild AGE 
`sudo make PG_CONFIG=/path/to/bin/pg_config install`
`make PG_CONFIG=/path/to/bin/pg_config installcheck` // all regression tests are passed
Then I stop and start the server again followed by `DROP` and `CREATE` extension.

But the changes are not reflected to the repository. For example; in recent commits the edge type check for UNWIND was removed but I still get the error
> ERROR:  UNWIND clause does not support agtype edge

**Comment by mohayu22** [comment]
Could you provide the query that resulted in this error?

**Comment by Zainab-Saad** [comment]
Sure
`SELECT * FROM cypher('demo_graph', $$
MATCH p = (u:Vertex {name : "A"})-[:EDGE*]->(v:Vertex{name : "C"})
UNWIND(relationships(p)) AS x RETURN sum(x) 
$$) AS (result agtype);`
But the issue isnt with the query anymore.

**Comment by kenwoon** [comment]
I had the same issue, and I followed @jrgemignani 's method for rebuilding and installing AGE. The `UNWIND` error does not show up anymore using @Zainab-Saad 's query, but the resulting table is not as expected. Only 1 row has been outputted, but the row is empty when it should have returned the sum of the edge values.

**Comment by mohayu22** [comment]
It seems like @Zainab-Saad forgot to use the `make clean` command before running `make install`. This could cause some issues with the installation process.

**Comment by mohayu22** [comment]
@kenwoon Give these queries a try and let's check if you obtain the same outcome.

I created the Path like this:
```
SELECT * FROM cypher('github_issue_761', $$
  CREATE ({name: 'A'})-[:NEXT {val: 1}]->({name: 'B'})-[:NEXT {val: 2}]->({name: 'C'})
$$) AS (result agtype);
```
Then I added the edge values using this query:
```
SELECT * FROM cypher('github_issue_761', $$
  MATCH path = ({name: 'A'})-[:NEXT*]->({name: 'C'}) 
  UNWIND relationships(path) AS edge
  RETURN sum(edge.val)
$$) AS (result agtype);
```

And I obtained this outcome:
```
 result 
--------
 3
(1 row)
```

**Comment by kenwoon** [comment]
@mohayu22 Hmm it's weird, I'm getting the `UNWIND` error again after running both queries you provided even after making sure to follow each of @jrgemignani 's instructions for the AGE reinstallation.

**Comment by jrgemignani** [comment]
Make sure to look at the release notes for each PG version of AGE. Currently, development is in the master branch which is PG11. Only at the time of a release will all of the other branches be updated; until we solidify our branching and update strategy. Currently, UNWIND is only in the master and PG11 branches.

**Comment by Zainab-Saad** [comment]
@kenwoon I have updated the query in the comment. Try this one.

**Comment by jrgemignani** [comment]
**If** the original topic of this issue is resolved, please close it :)

**If** there is another issue that this issue uncovered, please create a new issue and link this one. This will allow us to track that specific issue.

**Comment by Zainab-Saad** [comment]
The issue is resolved, thanks for help :)
