### ISSUE TITLE
Research potential designs to implement IDs for vertices, edges, and labels. Designs that would generally work with existing code and that would permit multiple labels to be assigned to vertices and edges

### ISSUE THREAD

**Issue by eyab** [apache/age#772]

**Comment by Zainab-Saad** [comment]
Looking forward to working on this project.

**Comment by mohayu22** [comment]
Excited to contribute to this project!

**Comment by CapnSpek** [comment]
Excited to work on this project.

**Comment by jrgemignani** [comment]
Thank you all for selecting this project!

Per our meeting, the first tasks should be for everyone to get acquainted with PostgreSQL, Cypher, AGE's implementation of Cypher, and building and debugging the AGE extension. 

The next step will be for us to work out a way that we can **all work as a team**, i.e., work together as a cohesive group to understand the issue and design potential solutions. We will discuss this in the next gchat.

**Comment by WendelLana** [comment]
I'm looking forward to collaborating with the team and work on this project!

**Comment by CapnSpek** [comment]
Hey team,
So I came up with some ideas and since the shared document is still not available yet, I thought of putting them on dev to because of good readability, formatting and share-ability.
Would love to have your insights on it.

**Comment by jrgemignani** [comment]
@CapnSpek Have Udaya Ganesh link you the spreadsheet for this. You will be able to put it there as well.

**Comment by udaiganny67** [comment]
hello Guys. Here I have attached the sheet link. Kindly make use of it

https://docs.google.com/spreadsheets/d/1OICrYGikbbIT1qXX0N_08tUnt5NfQcg8SkscpIIEl6E/edit?usp=sharing

**Comment by nupis-DanielS** [comment]
+1

**Comment by rafsun42** [comment]
@nupis-DanielS Hello. Could you please let us know what are your use cases of multiple labels?
