### ISSUE TITLE
Research which components need CI Github Actions

### ISSUE THREAD

**Issue by eyab** [apache/age#774]

**Comment by arun-esh** [comment]
**Codebase:**
Running automatic code quality tests on a codebase Linting, code formatting, and static code analysis fall under this category. You can utilise programmes like ESLint, Prettier, or SonarCloud.

**Comment by arun-esh** [comment]
**Unit testing:** 
Running unit tests to check that the code is correct and to find any potential errors or regressions. You can use well-known testing frameworks like Jest, pytest, or NUnit.

**Comment by arun-esh** [comment]
@eya Are you still working on this issue?

**Comment by MuhammadTahaNaveed** [comment]
All the necessary and required CIs were added. Closing this issue.
