### ISSUE TITLE
Implement apoc.meta.types function: returns a map of keys to types

### ISSUE THREAD

**Issue by fatimafatimaprogrammer** [apache/age#785]
**Is your feature request related to a problem? Please describe.**
While this function is not supported in Apache-AGE, but they are implemented in Neo4j. I found it useful, particularly for answering this particular case scenerio.
https://stackoverflow.com/questions/75892961/how-do-i-find-the-data-type-of-a-cypher-query-result-in-apache-age.

Descriptions of this function is exactly similar to the one described here: https://neo4j.com/labs/apoc/4.3/overview/apoc.meta/apoc.meta.types/

**Describe the solution you'd like**
N/A

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by Zainab-Saad** [comment]
@jrgemignani Is this feature already in implementation phase? If no, do you consider working on this would be worthwhile?

**Comment by jrgemignani** [comment]
@Zainab-Saad I am not aware of it being scheduled or worked on by anyone. If Neo4j has it, it is worth considering.

**Comment by Zainab-Saad** [comment]
Since this function is not yet implemented in AGE, so I am working on a PR to implement this function

**Comment by Zainab-Saad** [comment]
Since this function is not yet implemented in AGE, so I am working on a PR to implement this function

**Comment by jrgemignani** [comment]
@Zainab-Saad It is worth noting that if this is part of a larger package of functions, by adding this function, it invites others to want the rest of the package. That would be my only caveat.

**Comment by Zainab-Saad** [comment]
This package has many useful functions, do you think we should consider implementing the larger package of functions that would have this type check function as well as other functions? Because we need to make AGE as close to Neo4j as possible.

**Comment by jrgemignani** [comment]
@Zainab-Saad Yeah, for now we could look into the functions that make sense and will add value.
