### ISSUE TITLE
Segmentation fault when SET n.value = rand() or SET n.value = pi()

### ISSUE THREAD

**Issue by mohayu22** [apache/age#791]
**Describe the bug:**
The server crashes with Segmentation Fault error whenever the _value_ property of a Node or Edge is set to `rand()` or `pi()`
```
Program received signal SIGSEGV, Segmentation fault.

0x00005650823d9abb in datumTransfer (value=4592508940796821504, 
    typByVal=typByVal@entry=false, typLen=-1) at datum.c:192
192		if (!typByVal && typLen == -1 &&
```

**How to produce the error?**
```
SELECT * from cypher('demo', $$
  MATCH (n)
  SET n.value = rand()
  RETURN n
$$) as (result agtype);
```
And
```
SELECT * from cypher('demo', $$
  MATCH (n)
  SET n.value = pi()
  RETURN n
$$) as (result agtype);
```
**Important:**
```
/*
* Check for openCypher functions that are directly mapped to PG
* functions. We may want to find a better way to do this, as there
* could be many.
*/

if (pg_strcasecmp(name, "rand") == 0)
    funcname = SystemFuncName("random");
else if (pg_strcasecmp(name, "pi") == 0)
    funcname = SystemFuncName("pi");
else if (pg_strcasecmp(name, "count") == 0)
    funcname = SystemFuncName("count");
```
**Additional context:**
Using `rand() + 0` or `pi() + 0` resolves the issue and allows the program to function properly.

**Environment:**
- PostgreSQL 11.18 
- Apache Age (master branch)

**Comment by jrgemignani** [comment]
@mohayu22 Thank you for finding this. I have a feeling this is a casting issue -

```
psql-11.5-5432-pgsql=# SELECT * from cypher('graph1', $$
  MATCH (n) SET n.value = rand()::integer RETURN n
$$) as (result agtype);
                                            result
----------------------------------------------------------------------------------------------
 {"id": 844424930131969, "label": "zero", "properties": {"name": "Zero", "value": 0}}::vertex
(1 row)

psql-11.5-5432-pgsql=# SELECT * from cypher('graph1', $$
  MATCH (n) SET n.value = rand()::float RETURN n
$$) as (result agtype);
                                                    result
--------------------------------------------------------------------------------------------------------------
 {"id": 844424930131969, "label": "zero", "properties": {"name": "Zero", "value": 0.880863124504685}}::vertex
(1 row)

psql-11.5-5432-pgsql=# SELECT * from cypher('graph1', $$
  MATCH (n) SET n.value = pi()::integer RETURN n
$$) as (result agtype);
                                            result
----------------------------------------------------------------------------------------------
 {"id": 844424930131969, "label": "zero", "properties": {"name": "Zero", "value": 3}}::vertex
(1 row)

psql-11.5-5432-pgsql=#
```
It might be that, in SET, it is assuming it to be AGTYPE but it isn't.

**Comment by jrgemignani** [comment]
@mohayu22 The solution looks to be either making sure it is coerced (casted) correctly **or** we just provide our own wrapped functions for rand() and pi() like we sort of do for e().

**Comment by mohayu22** [comment]
Creating wrapper functions for `rand` and `pi` appears to be a straightforward solution.However, it is still worthwhile to investigate the issue further to see if a simpler solution can be found.

**Comment by jrgemignani** [comment]
@mohayu22 Go ahead and investigate further, if you like. I'm thinking that a wrapper is probably the best way to do this atm. But, it certainly isn't the ideal way.

**Comment by hammadsaleemm** [comment]
It looks like you have encountered a bug in Apache Age when using certain OpenCypher functions (rand() and pi()) to set the value of a Node or Edge property. Specifically, setting the property to rand() or pi() without adding + 0 at the end can cause a segmentation fault error.

The error seems to be related to how Apache Age transfers the value of the property to the underlying PostgreSQL database. The datumTransfer function in the datum.c file is called, and it appears that the function is not handling the rand() and pi() values correctly.

One potential workaround is to add + 0 to the end of the rand() or pi() value, as you mentioned. This may allow the program to function properly without causing a segmentation fault error.

It may also be worth reporting this bug to the Apache Age development team, so that they can investigate and address the issue in a future release.

**Comment by jrgemignani** [comment]
@mohayu22 Will you be following up with a solution or PR?

**Comment by mohayu22** [comment]
Yes, I will do a pull request that adds two new functions called `age_rand` and `age_pi`. These functions will return a pointer to an _agtype_ (which is the required data type). 

To implement these functions, I will _DirectFunctionCall_ the `drandom` and `dpi` functions provided by PostgreSQL.
