### ISSUE TITLE
Is the source code for Docker Image used in Docker hub  available to public ?

### ISSUE THREAD

**Issue by Munmud** [apache/age#816]
Is the source code for [Docker image (apache/age)](https://hub.docker.com/r/apache/age/tags) available to public ? If its publicly available, where can I get the source code for docker Image ?

**Comment by jrgemignani** [comment]
@Munmud I'm not exactly sure what you are asking. The docker images for AGE are built off of their respective branches. So, if it is AGE source code that you are looking for, then just look at the respective branches.

**Comment by Munmud** [comment]
@jrgemignani I am looking for all the details of Image layers used to build [PG13_latest](https://hub.docker.com/layers/apache/age/PG13_latest/images/sha256-7be14d4743f482bcae47476e60025906210b1edb63872ede927ccc01499d0a60?context=explore) in docker hub

**Comment by Mghrabi** [comment]
Yes, it's public and available, you can find it here https://hub.docker.com/r/apache/age, I hope I got your question right and that this is what you are looking for.

**Comment by Mghrabi** [comment]
You can pull it directly by the following command **docker pull apache/age:PG13_latest**, which you will find here (https://hub.docker.com/r/apache/age/tags), to see the layers in that image you can simply write the following command **docker image history apache/age:PG13_latest**  , I hope again that's what you are asking for.

**Comment by Munmud** [comment]
> docker image history apache/age:PG13_latest

@Mghrabi 
Its still not showing full details of each layer..

**Comment by jrgemignani** [comment]
@Munmud There are 4 automated docker image builds. They use Docker's automated processes to watch their respective branches and then build a docker image on any push their branch. Docker does all the rest.
