### ISSUE TITLE
Are multiple cypher calls possible within the same FROM clause?

### ISSUE THREAD

**Issue by moeed-k** [apache/age#820]
If I write a query like so:
```
SELECT * 
FROM cypher('query1'), cypher('query2');
```

I get the following error:
`ERROR:  table name "cypher" specified more than once`

Is this working as intended? Or will it be possible to have multiple cypher calls in the same FROM clause in the future?

**Comment by aru-d-at** [comment]
Based on my trials, seems its only a combination of table, cypher() in whichever order you call them.

But, I am quite curious to know what would be the intention behind wanting such functionality? Could perhaps elaborate some use cases to justify the need?

At the moment, if your aim is to access more than one graph, you can just utilise the JOIN clause.

Like so:


```opencypher
SELECT * FROM cypher('graph1', $$
CREATE (c: Customer { user: 'gomeZ', tags: 'dev' })
$$) as (v agtype);

SELECT * FROM cypher('graph2', $$
CREATE (s: Queries { user: 'gomeZ', keywords: ['java', 'c', 'python'] })
$$) as (v agtype);
```

```opencypher
SELECT graph1.u, graph1.t, graph2.k         
FROM cypher('graph1', $$
MATCH (c:Customer)
RETURN c.user, c.tags
$$) as graph1(u agtype, t agtype)
JOIN cypher('graph2', $$
MATCH (s:Queries)
RETURN s.user, s.keywords
$$) as graph2(u agtype, k agtype)
ON graph1.u = graph2.u;
```

**Comment by jrgemignani** [comment]
@moeed-k You need to specify the output type **and** you need to specify the name, like in @aru-d-at example above, and as illustrated below -

```
psql-11.5-5432-pgsql=# SELECT * from cypher('graph1', $$ match (u) return u $$);
ERROR:  a column definition list is required for functions returning "record"
LINE 1: SELECT * from cypher('graph1', $$ match (u) return u $$);
                      ^
psql-11.5-5432-pgsql=# SELECT * from cypher('graph2', $$ match (u) return u $$);
ERROR:  a column definition list is required for functions returning "record"
LINE 1: SELECT * from cypher('graph2', $$ match (u) return u $$);
                      ^
psql-11.5-5432-pgsql=# SELECT * from cypher('graph1', $$ match (u) return u $$) as (result agtype);                                                                                    result
-------------------------------------------------------------------------------------------------------------
 {"id": 281474976710657, "label": "", "properties": {}}::vertex
 {"id": 281474976710658, "label": "", "properties": {}}::vertex
 {"id": 844424930131969, "label": "zero", "properties": {"name": "Zero", "value": 2.71828182845905}}::vertex
(3 rows)

psql-11.5-5432-pgsql=# SELECT * from cypher('graph2', $$ match (u) return u $$) as (result agtype);
                               result
---------------------------------------------------------------------
 {"id": 1407374883553281, "label": "loop", "properties": {}}::vertex
 {"id": 1407374883553282, "label": "loop", "properties": {}}::vertex
(2 rows)

psql-11.5-5432-pgsql=# SELECT * from cypher('graph1', $$ match (u) return u $$) as g1(result agtype), cypher('graph2', $$ match (u) return u $$) as g2(result agtype);
                                                   result                                                    |
         result
-------------------------------------------------------------------------------------------------------------+----------------------
-----------------------------------------------
 {"id": 281474976710657, "label": "", "properties": {}}::vertex                                              | {"id": 14073748835532
81, "label": "loop", "properties": {}}::vertex
 {"id": 281474976710657, "label": "", "properties": {}}::vertex                                              | {"id": 14073748835532
82, "label": "loop", "properties": {}}::vertex
 {"id": 281474976710658, "label": "", "properties": {}}::vertex                                              | {"id": 14073748835532
81, "label": "loop", "properties": {}}::vertex
 {"id": 281474976710658, "label": "", "properties": {}}::vertex                                              | {"id": 14073748835532
82, "label": "loop", "properties": {}}::vertex
 {"id": 844424930131969, "label": "zero", "properties": {"name": "Zero", "value": 2.71828182845905}}::vertex | {"id": 14073748835532
81, "label": "loop", "properties": {}}::vertex
 {"id": 844424930131969, "label": "zero", "properties": {"name": "Zero", "value": 2.71828182845905}}::vertex | {"id": 14073748835532
82, "label": "loop", "properties": {}}::vertex
(6 rows)

psql-11.5-5432-pgsql=#
```

**Comment by aru-d-at** [comment]
@jrgemignani I see, the reason cypher(), cypher() queries was failing for me was cause of not adding the `graphN(v agtype)` at the end.

Seems like I can actually go ahead and overload with multiple cypher queries if need be:

```opencypher
SELECT * FROM
cypher('graph1', $$
    CREATE (c: Customer { user: 'jameS', tags: 'dev' })
$$) as graph1(v agtype),
cypher('graph2', $$
    CREATE (s: Queries { user: 'jameS', keywords: ['ocaml','c++'] })
$$) as graph2(v agtype),
cypher('metro', $$
    CREATE (n: Metro { user: 'jameS', keywords: ['ocaml','c++'] })
$$) as metro(v agtype);
```

**Comment by mahinash26** [comment]
It looks like the error message you received is due to the fact that you specified the table name "cypher" more than once in your FROM clause. To fix the issue, you could try aliasing the table names, like so:


SELECT * 
FROM cypher('query1') AS result1, cypher('query2') AS result2;

This should allow you to specify multiple cypher calls in the same FROM clause without encountering the "table name specified more than once" error.

**Comment by AbdulSamad4068** [comment]
If you need to execute multiple Cypher queries and combine their results, you can execute them separately and then combine the results using other SQL operations, such as JOIN, UNION, or subqueries. For example:
```
SELECT *
FROM (
  SELECT *
  FROM cypher('query1')
) AS result1
JOIN (
  SELECT *
  FROM cypher('query2')
) AS result2 ON <join_condition>
```
Replace `<join_condition>` with the appropriate conditions based on your data model
for example you can write `result1.column_name = result2.column_name`

**Comment by Hamza-Mushtaque** [comment]
This is working as intended because you are not allowed to use same table name ("cypher") more than once in the same `FROM` clause and it is not possible use multiple cypher calls in same `from` clause.
But it is possible to run separate multiple Cypher queries and then combine their results using Joins.
Checkout below query for reference.

```
SELECT *
FROM (
  SELECT * FROM cypher('query1')  -- Subquery 1
) AS result1
CROSS JOIN (
  SELECT * FROM cypher('query2')  -- Subquery 2
) AS result2;

```

**Comment by abdulmanann** [comment]
> @jrgemignani I see, the reason cypher(), cypher() queries was failing for me was cause of not adding the `graphN(v agtype)` at the end.
> 
> Seems like I can actually go ahead and overload with multiple cypher queries if need be:
> 
> ```
> SELECT * FROM
> cypher('graph1', $$
>     CREATE (c: Customer { user: 'jameS', tags: 'dev' })
> $$) as graph1(v agtype),
> cypher('graph2', $$
>     CREATE (s: Queries { user: 'jameS', keywords: ['ocaml','c++'] })
> $$) as graph2(v agtype),
> cypher('metro', $$
>     CREATE (n: Metro { user: 'jameS', keywords: ['ocaml','c++'] })
> $$) as metro(v agtype);
> ```

I tried this for the query below
```
SELECT * FROM cypher('usergraph', $$CREATE(u:User {name: 'user1', email: 'user1@email.com', phone: '1234-5678'}) RETURN u$$) as usergraph(u agtype), 
cypher('usergraph', $$CREATE(u:User{name:'user2', email:'user
2@email.com'}) RETURN u$$) as usergraph(u agtype);
```
 but am getting the following error:
![image](https://github.com/apache/age/assets/57444524/8fb1d9f5-4e39-465c-bfc8-7b05ff1572ec)

Is there any way to work around it without using JOIN?

**Comment by jrgemignani** [comment]
@abdulmanann Because you are specifying `usergraph ` in the `AS ` clause more than once. Look at the example you quoted above. Additionally, you can specify more than one item to create in the `CREATE ` clause. How you are doing it is unnecessary.

**Comment by abdulmanann** [comment]
> @abdulmanann Because you are specifying `usergraph ` in the `AS ` clause more than once. Look at the example you quoted above. Additionally, you can specify more than one item to create in the `CREATE ` clause. How you are doing it is unnecessary.

Thank you for your response It worked when I specified the second query from another graph.
