### ISSUE TITLE
Typecast bool to integer and vice versa

### ISSUE THREAD

**Issue by Zainab-Saad** [apache/age#824]
**Is your feature request related to a problem? Please describe.**
The typecasting from bool data type to integer and vice versa is not supported
The query:
`agedb=# SELECT * FROM cypher('graph', $$
RETURN 1::bool
$$) AS (result agtype);`
outputs: 
`ERROR:  typecast 'bool' not supported
LINE 1: SELECT * FROM cypher('graph', $$`

and 
`agedb=# SELECT * FROM cypher('graph', $$
RETURN true::integer
$$) AS (result agtype);`
output:
`ERROR:  typecast expression must be a number or a string`

**Describe the solution you'd like**
To the point I have debugged, issue lies with transform_cypher_typecast function in backend/parser/cypher_expr.c and thus some modifications need to be made there

**Describe alternatives you've considered**
N/A

**Additional context**
This feature of typecasting bool to integer and vice versa is supported in postgres, thus it would be worth adding this feature to AGE as well.

**Comment by jrgemignani** [comment]
@Zainab-Saad This looks like something that could be useful to add. I'm not sure about which  of the these **::bool** or **::boolean** would be best to use, though. Also, you may want to consider adding this to the "other" casts to PG types (like ::pg_bigint and ::pg_float8)

**Comment by Zainab-Saad** [comment]
This PR works with `agtype_to_bool` which is not what I meant in this issue.
@jrgemignani As already brought to your notice, I am already working on a PR regarding the typecasting using the operator ::
Moreover, I am working on adding this to other casts like ::pg_bigint and ::pg_float8

**Comment by jrgemignani** [comment]
@Zainab-Saad Will you be creating a PR for this?

**Comment by Zainab-Saad** [comment]
@jrgemignani  Yes. I am working on it
