### ISSUE TITLE
Python Driver: Version mismatch between ANTLR runtime required by pip install age and cloned repository

### ISSUE THREAD

**Issue by safi50** [apache/age#848]
### Describe the bug

When installing the `apache-age-python` package using `pip install`, it requires **ANTLR runtime version 4.9.2** as its dependency. 
However, when cloning the repository and importing age, it requires **ANTLR runtime version 4.11.1** as written in the **requirements.txt** file. This causes a version mismatch and leads to a `Could not deserialize ATN with version` error if the versions do not match. 

We can solve this error by running the following: 
```
pip install antlr4-python3-runtime==4.9.2      # When using the apache-age-python package
pip install antlr4-python3-runtime==4.11.1      # When importing age from the cloned repository 
```

Why is there a difference between ANTLR runtime versions required when using the `apache-age-python` package and when directly importing `age` from the repository. 
Maybe the published package on PyPI missed an update?

**Comment by Munmud** [comment]
Apache AGE doesn't support external links that have no control over. We are removing references to PYPI until it is under our control. This was previously issued here #784

**Comment by safi50** [comment]
> Apache AGE doesn't support external links that have no control over. We are removing references to PYPI until it is under our control. This was previously issued here #784

I see! I will close this issue in that case
