### ISSUE TITLE
[ageviewer_go] isn't there a README file giving instructions on how to setup the frontend and backend server of ageviewer_go + how to use?

### ISSUE THREAD

**Issue by Mghrabi** [apache/age#849]

**Comment by AhmarZaidi** [comment]
Currently there isn't. It would be added soon.  
To test the application:
- Clone the repo and switch to `ageviewer_go` branch.
- Remove the `agensgraph.c` file. 
- Run `wails dev` command. 

It's still in development though.

**Comment by KamleshKumar427** [comment]
Also, the backend is not connected to the front end for now.
To run the backend:
1. Got to the backend folder.
2. Run `go run .`, this will start the backend server.
3. and then run `node APIfunctions.js`, this will provide you cmd menu to interact with the backend server.

**Comment by M4rcxs** [comment]
Unfortunately, the readme is not currently available. However, it is slated to be added in the near future. In the meantime, you can test the application by following these steps:

- Clone the repository and go to the ageviewer_go branch.
- Remove 'agensgraph.c' file.
- Run the command "wails dev".

It's important to note that the tool is still under development, so it may not be completely stable.
Additionally, it's worth noting that the backend is currently not connected to the frontend. To start the backend server, navigate to the backend folder and run the command "go run .". Then, in another terminal, run the command "node APIfunctions.js" to access a command menu for interacting with the backend server.

**Comment by kenwoon** [comment]
> Also, the backend is not connected to the front end for now. To run the backend:
> 
> 1. Got to the backend folder.
> 2. Run `go run .`, this will start the backend server.
> 3. and then run `node APIfunctions.js` in another terminal, this will provide you cmd menu to interact with the backend server.

I've tried running `node APIfunctions.js` in a new terminal but I did not get a command menu, instead it just returned nothing. Also running `wails dev` brings up the application but nothing happens when I click on the start button. Is this expected?

**Comment by KamleshKumar427** [comment]
> > Also, the backend is not connected to the front end for now. To run the backend:
> > 
> > 1. Got to the backend folder.
> > 2. Run `go run .`, this will start the backend server.
> > 3. and then run `node APIfunctions.js` in another terminal, this will provide you cmd menu to interact with the backend server.
> 
> I've tried running `node APIfunctions.js` in a new terminal but I did not get a command menu, instead, it just returned nothing. Also running `wails dev` brings up the application but nothing happens when I click on the start button. Is this expected?

For the backend, you first need to uncomment code for the menu at the end of the file and also uncomment some require() lines at the start of the APIfunctions.js file. 

For the front end, you need to run Wails dev inside the age-viewer folder, since the front end is implemented there as of now.

**Comment by farooquememon385** [comment]
> > Also, the backend is not connected to the front end for now. To run the backend:
> > 
> > 1. Got to the backend folder.
> > 2. Run `go run .`, this will start the backend server.
> > 3. and then run `node APIfunctions.js` in another terminal, this will provide you cmd menu to interact with the backend server.
> 
> I've tried running `node APIfunctions.js` in a new terminal but I did not get a command menu, instead it just returned nothing. Also running `wails dev` brings up the application but nothing happens when I click on the start button. Is this expected?

@kenwoon make necessary changes in APIfunctions.js as directed in this pull request https://github.com/apache/age/pull/869 if you get an error while running APIfunctions,js after uncommenting the code

**Comment by sarthak-19** [comment]
I've created a new [PR](https://github.com/apache/age/pull/873) with detailed instructions. Further improvement, suggestions  and contributions are welcomed.
