### ISSUE TITLE
Which Tech/Algorithm is used to generate id automatically when creating new nodes and edges ?

### ISSUE THREAD

**Issue by Munmud** [apache/age#852]
We are developing python support for Networkx. While building the project, we need to know the process of generating id no for that are assigned automatically when creating new nodes and edges.

**Comment by Zainab-Saad** [comment]
The 16 digit ID of nodes and edges is generated by applying certain masking algorithm on the ID of label associated with that node/edge. Since the labels are actually tables that store the nodes/edges associated to them in that table and the ID of these tables are generated by a sequence (you can find the ID of a label table using `SELECT * FROM ag_label` --> This outputs a column named id that is basically the label ID I am talking about.) 
In order to actually see how the IDs are given to nodes/edges, debug a simple CREATE statement with breakpoints on 

1. create_vertex
2. ExecEvalExpr

This will give you a more clear picture
Hope it helps!

**Comment by aru-d-at** [comment]
Stepping through the code, it seems the Id is calculated through Postgres using the `stdlib-bsearch` library and calling function `bsearch()`.

With the `ExecEvalStepOp` from _postgres/src/backend/executor/execExprInterp.c_ calling the function in multiple iterations to go through the existing Id's and evaluate the new Id's viability.

The operation occurs similarly with the label_id's. Besides calling the previously mentioned function, it also calls the following (to name a few):
* `_hash_any_` at _postgres/src/backend/utils/hashfn.c_
* `_calc_bucket_` at _postgres/src/backend/utils/dynahash.c_

**Comment by humzakt** [comment]
Apache AGE is an extension of PostgreSQL, and it uses the underlying PostgreSQL database management system to store and manage graph data. When creating new nodes and edges, Apache AGE relies on PostgreSQL's internal mechanisms for generating unique IDs.

In PostgreSQL, the most common method for generating unique IDs is to use a SERIAL column or a sequence. A SERIAL column is essentially an auto-incrementing integer value backed by a sequence. When a new row is inserted, the SERIAL column will automatically be assigned a new value from the sequence.

For Apache AGE, the details of the unique ID generation for nodes and edges are internal to the extension, but it is likely that it uses a similar mechanism, such as a sequence or a custom ID generation algorithm built on top of PostgreSQL's features. The exact implementation details might not be publicly documented.

In any case, the ID generation mechanism ensures that each node and edge receives a unique identifier when they are created, which can be accessed and used in Cypher queries or other operations.

**Comment by kenwoon** [comment]
I have found information from the official [master documentation](https://age.apache.org/age-manual/master/intro/types.html#graphid) as follows:

> An entity is assigned a set of properties, each of which are uniquely identified in the set by the irrespective property keys. Simple entities are assigned a unique `graphid`. A `graphid` is a unique composition of the entity’s label id and a unique sequence assigned to each label.

From what I can find,  `graphid`s are mainly referenced from the 'graphid.c' file, which is likely responsible for the creation of GRAPHID Oids. The function `make_graphid()` takes in the `label_id` and `entry_id` generated by the `PG_GETARG_INT32()` and `PG_GETARG_INT64()` functions, defined in the `graphid.h` header file.
