### ISSUE TITLE
How to create a node with with specific id I provide? 

### ISSUE THREAD

**Issue by Munmud** [apache/age#855]
Suppose I want to create a node with following information
- id `1910677111`.
- label `People` 
- properties `{'name' : 'Moontasir'}`
- Graph_name : `students`

How can I do that ?

**Comment by TalhaMunir-JD** [comment]
You can create the node with the information using create command.

`CREATE (p:Person {id: 1910677111, name: 'Moontasir'})
SET p.Graph_name = 'students'
RETURN p
`

**Comment by Munmud** [comment]
> You can create the node with the information using create command.
> 
> `CREATE (p:Person {id: 1910677111, name: 'Moontasir'}) SET p.Graph_name = 'students' RETURN p `

IT will only create a new property. Not this way I want.. Because still it generates an id for new nodes.
![Screenshot from 2023-04-26 13-15-29](https://user-images.githubusercontent.com/53787290/234499090-d9ac7c6d-9eb5-43cd-aeb5-a3be3cf74c7b.png)

**Comment by Zainab-Saad** [comment]
The IDs for nodes and edges are generated automatically. I have explained how they are generated [here](https://github.com/apache/age/issues/852#issuecomment-1522934924). Because the ID of vertex, edge is strongly associated with the label that it has, hence we can not change the ID of node/edge or create a new one with the ID of our choice.

**Comment by dukeofhazardz** [comment]
You could try this assuming you've already created the graph 'students';

SELECT * FROM cypher('students', $$ CREATE ( :People { id: 1910677111, name : 'Moontasir'}) $$) AS (a agtype);

This will create a node, with the id you assigned as an attribute which can only be accessed through the :People Label.

However, like Zainab said, the actual IDs are automatically generated, but you can do the above to meet your specific need.

**Comment by jrgemignani** [comment]
@Munmud 

As @Zainab-Saad correctly stated, the IDs are system generated and are not user configurable. While there are "ways" to change these system generated IDs, doing so would break the graph. 

As @TalhaMunir-JD stated, you can create an ID of your own as a property. This is the correct way to do it.

**Comment by shady-cj** [comment]
You can do that using 

`SELECT * FROM cypher(‘students’,  $$
    CREATE (:People {_id: 1910677111, name: ‘Moontasir’}) 
$$) 
AS (p agtype);
`

As said earlier…. I’d’s would be automatically generated if you can create a custom field such as ‘_id’ if you need to use a custom unique identifier for each vertex.

**Comment by Hamza-Mushtaque** [comment]
Try this;
CREATE (:People {id: 1910677111, name: 'Moontasir'})-[:IN]->(:students);

It will create a node labeled 'People' with the properties 'id' and 'name' and will create a relationship labeled 'IN' to a node labeled 'students'. The colon in front of 'People' and 'students' indicate their labels, and the curly braces indicate the node properties.

I hope this helps.

**Comment by waleedahmed0001** [comment]
> > You can create the node with the information using create command.
> > `CREATE (p:Person {id: 1910677111, name: 'Moontasir'}) SET p.Graph_name = 'students' RETURN p `
> 
> IT will only create a new property. Not this way I want.. Because still it generates an id for new nodes. ![Screenshot from 2023-04-26 13-15-29](https://user-images.githubusercontent.com/53787290/234499090-d9ac7c6d-9eb5-43cd-aeb5-a3be3cf74c7b.png)

You are just giving the id as the property of the Person label. You want to see it in the gid but its not directly possible as it is based on some algorithm and it cannot be directly accessed.

**Comment by Omar-Saad** [comment]
You can't change the ID as they are auto generated but alternatively you can add a new property for the `People` entity like `person_id` and put the `id` you want in it.
You can do so by running the following query : 

```
SELECT * FROM cypher(‘students’,  $$
 MERGE(p:People { person_id: 1910677111, name: ‘Moontasir’})  
RETURN p
$$)  AS (res agtype); 
```

The `MERGE` command will either create a new person or update it if it is already exists.
