### ISSUE TITLE
Using CALL with a function and a RETURN with an undefined variable does not output correct error

### ISSUE THREAD

**Issue by aru-d-at** [apache/age#871]
**Description**
CALL function with a RETURN does not output correct error message

**Mode:**
- Command line

**Data Setup:**
- None

**Configuration:**
- Default AGE 1.3.0 installation with PostgreSQL 12

**Command**
```pgsql
SELECT * FROM cypher('test', $$
    CALL toInteger('1')
    RETURN v
$$) as (v agtype);
```
```
ERROR:  Procedure call inside a query does not support naming results implicitly
LINE 1: SELECT * FROM cypher('test', $$
                                      ^
HINT:  Name explicitly using `YIELD` instead
```

**Expected behavior**
Should throw syntax error at `RETURN v` instead of crashing

Similar to
```
ERROR:  could not find rte for v
LINE 3: RETURN v
               ^
```

**Environment:**
- Version: Tested using 1.3.0

**Comment by dehowef** [comment]
Hi, thanks for catching this~ can you go ahead and modify the code to throw the appropiate error? thx!

**Comment by aru-d-at** [comment]
@dehowef Sure, working on it.

**Comment by aru-d-at** [comment]
@dehowef Hi, could you please check the PR. Thanks.

**Comment by jrgemignani** [comment]
@aru-d-at I agree that the crash is not an acceptable result. But, neither is `ERROR:  could not find rte for v`. That is an error stating that something is wrong with the code; that something was transformed or built incorrectly. Errors like that need to be fixed as well. So, while you may be able to stop it from crashing, you still haven't resolved the core issue.

> Expected behavior
> Should throw syntax error at RETURN v instead of crashing
> 
> Similar to
> 
> ```
> ERROR:  could not find rte for v
> LINE 3: RETURN v
>                ^
> ```

**Comment by aru-d-at** [comment]
@jrgemignani So, after further investigating the issue, I have found that the crash by itself is unrelated to the `CALL` clause. Rather, it seems using AGE 1.3.0 on a Database that had previously used AGE 1.1.0 results in crashing the database. Most queries seem to cause a crash.

When I opened the issue, my database was in a a similar state (AGE 1.1.0 -> 1.3.0) and it just so happens the query used at the time had the `CALL` clause. For this issue, the title as well as the error output needs to be edited. So I will do that first.

In regards to the crash, it can be either be that, 1.3.0 is incompatible with 1.1.0 based Databases or that it is indeed a bug. I may need to open a separate issue for this.

For the PR, I was working on the master branch and therefore switched to PG11 with a fresh database. It utilised the master branch installation all through the database initialisation as well as testing. As such, the crash did not occur there, instead I did get the error message as it is currently implemented.
`ERROR:  Procedure call inside a query does not support naming results implicitly`

Referring to a similar clause used in Neo4j it does not match the error message.

**Comment by jrgemignani** [comment]
@aru-d-at 

> @jrgemignani So, after further investigating the issue, I have found that the crash by itself is unrelated to the CALL clause. Rather, it seems using AGE 1.3.0 on a Database that had previously used AGE 1.1.0 results in crashing the database. Most queries seem to cause a crash.

If I recall correctly, you cannot upgrade from 1.1.0 to 1.3.0 due to changes made to some tables. So, you need to remove the old AGE installation.

**Comment by jrgemignani** [comment]
@aru-d-at 

> `ERROR:  could not find rte for v`

and 

> `ERROR:  Procedure call inside a query does not support naming results implicitly`

Which do you feel is more descriptive? To me, one tells you that something isn't supported and the other tells you it can't find something.

**Comment by aru-d-at** [comment]
@jrgemignani 

> `ERROR:  Procedure call inside a query does not support naming results implicitly`
This error is far more descriptive to me as it underlines that `YIELD` is required after a `CALL` clause when I require the results to be named.

Seems like, in the case the user is making a solo `CALL` and wants to return the vertex they would need to use the `CALL ... YIELD` syntax. I have now found that queries like
```pgsql
SELECT * FROM cypher('test', $$
    MATCH (v) WHERE v.name='J' CALL toInteger(v.customer_id) RETURN a
$$) as (v agtype);
```
and

```pgsql
SELECT * FROM cypher('test', $$
    MATCH (v) WHERE v.name='J' CALL toInteger(v.customer_id) RETURN v
$$) as (v agtype);
```

Both return the same error.

**Comment by dehowef** [comment]
https://neo4j.com/docs/cypher-manual/current/clauses/call/

https://neo4j.com/docs/cypher-manual/current/clauses/call/

Please read the documentation for both Call subquery and Call Yield specifically. Thanks

@aru-d-at

**Comment by jrgemignani** [comment]
@aru-d-at My issue is that your PR wants to change the error message to something that isn't useful

![image](https://user-images.githubusercontent.com/1505136/235811665-c01e78c5-41aa-4bfd-a3da-c7d1428bedb9.png)

**Comment by aru-d-at** [comment]
@dehowef 
> If the called procedure declares at least one result field, YIELD may generally not be omitted. However YIELD may always be omitted in a standalone procedure call. In this case, all result fields are yielded as newly-bound variables from the procedure call to the user.

Ok, I see, thank you for pointing that out.

@jrgemignani I have closed the PR. Thank you for clarification. In this case, I feel I should close this issue as well.
