### ISSUE TITLE
Unexpected Error: column reference "_age_default_alias_0" is ambiguous

### ISSUE THREAD

**Issue by DominicWuest** [apache/age#876]
When running the following query:
```cypher
MATCH ({n0:0}) MATCH ()-->() MATCH ({n1:0})--() RETURN 0 AS n2
```

I encountered the following error:
```
column reference "_age_default_alias_0" is ambiguous
```

I believe the query mentioned above is semantically and syntactically correct and thus no error should be thrown here.

I encountered this issue when testing queries against the **apache/age:PG13_latest** docker image.

### Steps to reproduce
Run the following query and observe it throws an error:
```cypher
MATCH ({n0:0}) MATCH ()-->() MATCH ({n1:0})--() RETURN 0 AS n2
```

### Expected behavior
The query should run successfully

### Actual behavior
The query fails with the error message `column reference "_age_default_alias_0" is ambiguous`.

**Comment by AbdulSamad4068** [comment]
The error message "column reference '_age_default_alias_0' is ambiguous" indicates that the column reference used in the query is not unique and could refer to more than one column.

In this particular case, it seems that the issue may be related to the use of the alias "n0" and "n1" for nodes in the MATCH clause. The alias could be conflicting with a default alias generated by the system, causing the ambiguity error.

To solve this issue, you could try using a different alias for the nodes in the MATCH clause, or using a different alias for the "0" value in the RETURN clause. For example, you could rewrite the query as follows:

`MATCH (n:Node)-[]->() MATCH (n1:Node)-[]->() RETURN 0 AS result
`

Where "Node" is the label of the nodes you want to match. By using different aliases and specifying the label of the nodes, you can avoid conflicts with the default aliases generated by the system and resolve the ambiguity error.

If this does not solve the issue, you could try checking the database schema and ensuring that there are no naming conflicts or other issues that could cause ambiguity errors.

**Comment by DominicWuest** [comment]
Thanks for looking into this @AbdulSamad4068!
But this doesn't seem to fix the error. After spinning up a brand new docker container and running just the following query:
```psql
SELECT * FROM cypher('graph', $$
    MATCH ({very_weird_name:0}) MATCH ()-->() MATCH ({another_weird_name:0})--() RETURN 0 AS the_weirdest_of_all_names
$$) AS (v agtype);
```
The same error occurs.
