### ISSUE TITLE
Unexpected Error: operator does not exist: @> agtype

### ISSUE THREAD

**Issue by DominicWuest** [apache/age#883]
When running the following query:
```cypher
MATCH () MATCH (_{n0:0}) RETURN 0
```

I encountered the following error:
```
pq: operator does not exist: @> agtype
```

I believe the query mentioned above is semantically and syntactically correct and thus no error should be thrown here.
Additionally, the query runs successfully in neo4j.

I encountered this issue when testing queries against the **apache/age:PG13_latest** docker image.

### Steps to reproduce
Run the following query and observe it throws an error:
```cypher
MATCH () MATCH (_{n0:0}) RETURN 0
```

### Expected behavior
The query should run successfully

### Actual behavior
The query fails with the error message `operator does not exist: @> agtype`.

**Comment by humzakt** [comment]
Can you share the complete query you are writing along with a screenshot of your terminal for better diagnosis?
Also make sure you have imported AGE correctly and you are able to run other queries

**Comment by safi50** [comment]
This problem seems to be related to the use of multiple `MATCH` clauses used within a single cypher query without corresponding `Where` clauses.
The following query runs as expected: 
```
MATCH () , (_{n0:0}) RETURN 0
```
