### ISSUE TITLE
Unexpected Error: graphid cde does not exist

### ISSUE THREAD

**Issue by DominicWuest** [apache/age#884]
When running the following query against an empty database:
```cypher
MERGE ()-[x:A]->() SET x = { n0:endNode(x).n1 }
```

I encountered the following error:
```
pq: graphid cde 281474976710658 does not exist
```

I believe the query mentioned above is semantically and syntactically correct and thus no error should be thrown here.
Additionally, the query runs successfully in neo4j.

I encountered this issue when testing queries against the **apache/age:PG13_latest** docker image.

### Steps to reproduce
Run the following query and observe it throws an error:
```cypher
MERGE ()-[x:A]->() SET x = { n0:endNode(x).n1 }
```

### Expected behavior
The query should run successfully

### Actual behavior
The query fails with the error message `graphid cde 281474976710658 does not exist`.

**Comment by DominicWuest** [comment]
Thanks for looking into this issue @jrgemignani!
I ran this query against an empty dataset, I have updated the issue to hold this information.
Since I am using a cypher fuzzer to find these bugs, I am not attempting to do anything in particular besides find previously unknown bugs.

**Comment by jrgemignani** [comment]
@DominicWuest Any particular reason why you are doing this? 

> Since I am using a cypher fuzzer to find these bugs, I am not attempting to do anything in particular besides find previously unknown bugs.

Also, what tool are you using?

**Comment by jrgemignani** [comment]
@DominicWuest Please do, it could be useful :)

The one thing that I will add about doing this sort of testing, in general, is that it can be a bit problematic if you don't know the specific applications involved. For example, there are differences between AGE and Neo4j types, among other things. Because you aren't aware of them, your tests can flag them as issues, when they aren't.

I mention this because our team does try to look into every issue, bug, question, or enhancement and extraneous ones do create extra work for our team. Just try to keep that in mind.

**Comment by dehowef** [comment]
> @jrgemignani As part of my bachelor thesis I am writing a cypher fuzzer. Your project is pretty popular and makes use of cypher. Because of this, I saw it as an optimal target for evaluating my tool by helping improve your product through fuzz testing.
> 
> My work is not yet done so I can't share a lot of details just yet, but it will be open source once I'm done and under the GPLv3 license, so you could then start using it as part of your testing strategy. If you want to, I could inform you directly once my work is done.

Wow that's pretty cool~ Good luck on your thesis

**Comment by dehowef** [comment]
@MuhammadTahaNaveed Your patch seemed to fix this issue as well! Good job.

**Comment by DominicWuest** [comment]
Alright, I will inform you once I'm done @jrgemignani!

I'm sorry for any inconvenience some of my reports might have caused. In the future, I will abstain from submitting reports related to features that aren't fully documented or used in other systems.

**Comment by DominicWuest** [comment]
Thank you @dehowef!
