### ISSUE TITLE
Unexpected Error: UNION types agtype and bigint cannot be matched

### ISSUE THREAD

**Issue by DominicWuest** [apache/age#885]
When running the following query:
```cypher
RETURN 0 AS x UNION RETURN COUNT(0) AS x
```

I encountered the following error:
```
pq: UNION types agtype and bigint cannot be matched
```

I believe the query mentioned above is semantically and syntactically correct and thus no error should be thrown here.
Additionally, the query runs successfully in neo4j.

I encountered this issue when testing queries against the **apache/age:PG13_latest** docker image.

### Steps to reproduce
Run the following query and observe it throws an error:
```cypher
RETURN 0 AS x UNION RETURN COUNT(0) AS x
```

### Expected behavior
The query should run successfully

### Actual behavior
The query fails with the error message `UNION types agtype and bigint cannot be matched`.

**Comment by jrgemignani** [comment]
@DominicWuest Neo4j doesn't use nor have AGTYPE. Because of that, it won't complain. 

The problem here is that you are trying to UNION a container type (or composite type) without specifying what it contains. AGTYPE can be many things, you need to specify what it is in this case.

```
 psql-11.5-5432-pgsql=# SELECT * from cypher('graph1', $$ RETURN 0::pg_bigint AS x UNION RETURN COUNT(0) AS x $$) as g1(result agtype);
 result
--------
 0
 1
(2 rows)

psql-11.5-5432-pgsql=#
```

**Comment by DominicWuest** [comment]
Hi @jrgemignani, thanks for looking into my issue!
I'm sorry, I was unaware of this discrepancy between AGE's implementation and the openCypher specs, I will close this issue as "Won't fix" since it seems like it's intended behavior.

**Comment by DominicWuest** [comment]
I see, thanks for clearing that up @jrgemignani. Do you have any tips about how I could differentiate between fixable and unfixable cases?
By the way, how would you want me to report crashes? Should I also just create issues for those or do you want me to follow the apache reporting procedure?

**Comment by jrgemignani** [comment]
@DominicWuest For crashes, they need to be as detailed as possible and reproducible. Basically, show us how to reproduce the crash.

**Comment by DominicWuest** [comment]
Alright, noted @jrgemignani!
I'll put extra care into these reports and submit them soon.
