### ISSUE TITLE
Import statement gives error

### ISSUE THREAD

**Issue by Zainab-Saad** [apache/age#886]
While testing the samples for python driver in apache-age-note.ipynb here,
```
import age
from age.gen.ageParser import *
GRAPH_NAME = "test_graph"
DSN = "host=172.17.0.2 port=5432 dbname=postgres user=postgres password=agens"
ag = age.connect(graph=GRAPH_NAME, dsn=DSN)
```
The statement `from age.gen.agePareser import *` gives error 'ModuleNotFoundError: No module named 'age.gen.ageParser''.

I have tested the sample cells without this statement and everything works fine. Is there a reason this statement is here or is it by mistake?

**Comment by titoausten** [comment]
Yes, Instead of that use `import AgtypeParser`. I guess it hasn't been updated in the notebook.

**Comment by FahadZaheerfzr** [comment]
I just looked into the code and in this directory, I couldn't find any such file or module. It's also possible that the module was only necessary for earlier versions.

**Comment by titoausten** [comment]
It was renamed. Instead of that use ` AgtypeParser`. I guess it hasn't been updated in the notebook.

**Comment by M4rcxs** [comment]
The module `age.gen.ageParser` has been named to `age.gen.AgtypeParser`, the `age.gen.ageParser` is an old version of it.

**Comment by humzakt** [comment]
You should replace `from age.gen.ageParser import *` with `age.gen.AgtypeParser`. I believe this will fix your errors.

**Comment by FahadZaheerfzr** [comment]
This issue is resolved in Pull Request # 900
Here is the link to Pull Request: https://github.com/apache/age/pull/900

**Comment by hammadsaleemm** [comment]
The issue reason is basically simple, it seems that the module 'age.gen.ageParser' is not installed or cannot be found in your environment. This module is used to parse the AgeQL language, which is the query language used by Apache AGE. As mentioned by others, this has been changed so use now `age.gen.AgtypeParser`. Also check the PR#900 As fahad mentioned.
