### ISSUE TITLE
ImportError in age.models

### ISSUE THREAD

**Issue by hammadsaleemm** [apache/age#890]
I encountered an ImportError when trying to import 'Model' from 'age.models' in the age Python driver for Apache AGE. The error message reads:

    ImportError: cannot import name 'Model' from 'age.models' (c:\Users\lenovo\age\drivers\python\age\models.py)

I am running Python 3.9 on Windows 10. Here are the steps I took to encounter the error:

1. Installed the age Python driver using pip.
2. Attempted to import 'Model' from 'age.models'.
3. Encountered the ImportError.

Please let me know if there is any additional information I can provide to help diagnose and fix this issue.

**Comment by humzakt** [comment]
Models isn't defined in `models.py`. You can check https://github.com/rhizome-ai/apache-age-python/blob/main/age/models.py for all available classes which you can import

**Comment by aru-d-at** [comment]
@hammadsaleemm 
> Attempted to import 'Model' from 'age.models'.

You should be importing one or more of the classes defined.

[Refer to the test file](https://github.com/apache/age/blob/master/drivers/python/test_age_py.py) for usage of the models.

**Comment by safi50** [comment]
If you open the `models.py` file in the python driver, you'll find that there is no `Model` class or `Function`. 
If you are simply trying to import the file `age.models`, use the import statements as : 
` import age.models as model`

**Comment by M4rcxs** [comment]
It looks like the 'Model' class is not defined in the `age.models` module. This could be the reason why you are getting the ImportError when trying to import it. Alternatively, you can try reviewing your import statement to make sure that you are using the correct class name or function name. 
reach it on: [Age Models](https://github.com/rhizome-ai/apache-age-python/blob/main/age/models.py)

**Comment by AhmedMo0** [comment]
if you checked [models.py](https://github.com/rhizome-ai/apache-age-python/blob/main/age/models.py) file you will not find Model 
class So, check import statement is written correctly

**Comment by Nimra-1234** [comment]
The 'Model' class does not appear to be declared in the `age.models `module. This could be the cause of the ImportError while attempting to import it. Alternatively, check your import statement to ensure that you are using the correct class or function name.

Import using:
`from age.models import *`

**Comment by abdulmanann** [comment]
It appears that the ImportError is caused by trying to import a 'Model' class that doesn't exist in the `age.models` module. 

If you check the content of `age.models` on the [Apache AGE Python driver GitHub page](https://github.com/rhizome-ai/apache-age-python/blob/main/age/models.py), you will see that 'Model' is not a declared class in that module, which is why you're encountering this error.

Please make sure you are importing a class or function that actually exists in the `age.models` module. You can import all classes from `age.models` with the following statement:

```python
from age.models import *
```

**Comment by AadilBashir489** [comment]
In `age.models`, there exist no class named 'Model', which is why you are facing this error. The solution is to correct your import statement like this below:
`from age.models import *`

**Comment by mahinash26** [comment]
The ImportError is occurring because you are attempting to import a 'Model' class that is not present in the age.models module. Double-check that you are importing a valid class or function from the age.models module.
I hope this helps.

**Comment by Omar-Saad** [comment]
There is no `Model` class present in the `models.py` file, which is why you are encountering this error. To import all the classes from this file, you can utilize the following code:

```python
from age.models import *
```

**Comment by waleedahmed0001** [comment]
These are the classes defined in the models file.

Graph: Represents a graph object with rows and vertices.
AGObj: Base class for AGE objects.
Path: Represents a path object composed of multiple entities.
Vertex: Represents a vertex in the graph with an ID, label, and properties.
Edge: Represents an edge in the graph with an ID, label, start ID, end ID, and properties.

The model class is not defined and that's why you are getting this error.

**Comment by vkt-1271** [comment]
You're importing a class that doesn't exist in `models.py` that's why you facing this error.
Try using: `from age.models import *`

**Comment by pawankukreja01** [comment]
**Check for circular imports**: Circular imports can cause issues with importing modules in Python. Ensure that there are no circular imports between your modules.
**Check for version compatibility issues**: Ensure that you are using a compatible version of Apache AGE with your version of Python.
**Check that the module exists**: Verify that the ‘age.models’ module exists in the correct location and contains the ‘Model’ class. You can do this by opening a Python shell and running `import age.models` followed by `dir(age.models)` to see a list of all objects in the module.
