### ISSUE TITLE
Function parameter not accessible inside Cypher query

### ISSUE THREAD

**Issue by WendelLana** [apache/age#894]
**Describe the bug**
I'm creating a function in PostgreSQL, but I believe that the parameter `search_name` of the `text` type is not accessible within the Cypher query.

**How are you accessing AGE (Command line, driver, etc.)?**
- Command line

**What data setup do we need to do?**
```pgsql
SELECT * from cypher('graph_name', $$
  CREATE (a:Person {name: 'A'}), 
         (b:Person {name: 'B'}), 
         (c:Person {name: 'C'}), 
         (d:Person {name: 'D'})
$$) as (a agtype);
SELECT * FROM cypher('graph_name', $$
    MATCH (a:Person), (b:Person)
    WHERE a.name = 'A' AND b.name <> 'A'
    CREATE (a)-[e:friends_with]->(b)
    RETURN e
$$) AS (e agtype);
```

**What is the necessary configuration info needed?**
- none

**What is the command that caused the error?**
```plpgsql
CREATE OR REPLACE FUNCTION count_friends(search_name text)
    RETURNS integer AS $function$
    BEGIN
        RETURN (
            SELECT COUNT(*) FROM cypher('graph_name', $$
                MATCH (v:Person)-[]-(w)
                WHERE v.name = search_name
                RETURN w AS friend
            $$) AS (friends agtype)
        );
    END;
$function$ LANGUAGE plpgsql;
```
To test the function, I ran this simple query:
```
SELECT count_friends('A');
```
And I got this error:
```
ERROR:  could not find rte for name
```

**Expected behavior**
The function should return the number of friends that a specified person, identified by their name, has.

**Environment (please complete the following information):**
- Version: Apache AGE release 1.3.0 in PostgreSQL 13.10

**EDIT**
This is actually a dynamic cypher and you can see more about it [here](https://age.apache.org/age-manual/master/advanced/plpgsql.html#dynamic-cypher)

**Comment by WendelLana** [comment]
This is actually a dynamic cypher and you can see more about it [here](https://age.apache.org/age-manual/master/advanced/plpgsql.html#dynamic-cypher)

**Comment by jrgemignani** [comment]
@WendelLana But, did it resolve the issue?

**Comment by WendelLana** [comment]
@jrgemignani In this particular function, I couldn't access the parameter variable inside the Cypher query at all. However, I was able to write another function that worked by using the sample from the docs

**Comment by jrgemignani** [comment]
@WendelLana It "should" work. However, from the linked example, it looks like you need to add more to your function.
