### ISSUE TITLE
Indexing function for existing drivers

### ISSUE THREAD

**Issue by aru-d-at** [apache/age#902]
Add functions to create indexing functions for existing Drivers

**Proposition:**
Adding indexing functions for the drivers like those described in the regression test `index.sql`

**Current situation:**
Currently only alternative is to use Psycopg to directly create the required indices. Or through psql by DBA.

**Context:**
Would be more user friendly to have indexing functions implemented within drivers.

**Comment by aru-d-at** [comment]
I am already working on a PR for this

**Comment by dehowef** [comment]
This would be a great addition for the drivers!!! Good taking initiative @aru-d-at
