### ISSUE TITLE
NULLIF() function

### ISSUE THREAD

**Issue by WendelLana** [apache/age#908]
**Is your feature request related to a problem? Please describe.**
I was trying to create a conditional statement using the `NULLIF()` function inside a Cypher query, but I received an error message stating that the function does not exist.

**Describe the solution you'd like**
A similar function to the PG `NULLIF()` function

**Describe alternatives you've considered**
Using `CASE` would be an alternative to `NULLIF`

**Additional context**
I'm working on a PR for this, if there's no problem

**Comment by farakh-shahid** [comment]
Yes i have checked this We have alternative CASE .
We can achieve similar functionality  using the 'CASE' expression in cypher.

Try this :
```
MATCH  (n:node)
RETURN CASE
WHEN n.property = 'value' THEN NULL
ELSE n.property
END AS result;
```

This will is  n.property has a value of 'value' then it will return null for this  else it will return n.property.
