### ISSUE TITLE
Python Driver : Reference to author name and author email may not be correct

### ISSUE THREAD

**Issue by Munmud** [apache/age#921]
In [Setup.py](https://github.com/apache/age/blob/a43002ae39132781c535031d426d04bc5464851e/drivers/python/setup.py#L28) `author` and `author_email` is referencing to specific person. So it might not be correct.

**Comment by hammadsaleemm** [comment]
Hey @Munmud , ig youre right the author and author_email fields in the setup.py file are currently set to specific values ('rhizome' and 'rhizome.ai@gmail.com', respectively). It is possible that these values may not be correct or up-to-date.

**Comment by Munmud** [comment]
Resolved the issue with pr
