### ISSUE TITLE
Updating properties for multiple nodes in a graph database using a single query without specifying each node individually

### ISSUE THREAD

**Issue by hammadsaleemm** [apache/age#934]
I am aware of how to update properties for a single node using a query like:

```
MATCH (n:label4 {id: 123})
SET n.newProperty = 'new value'
```
However, I want to update properties for multiple nodes without having to specify each node individually in the query. Is there a way to achieve this with a single query? If so, what would be the recommended approach?

**Comment by TalhaMunir-JD** [comment]
Yes you can update property of multiple nodes without specifying every node individually. 

If you want to update nodes based on some condition. You can do this in 2 ways :
Updating nodes based on a condition:
1. You can use match clause with come condition that selects the node that you want to update 
2. Then use set clause to update the desired properties.
SQL:
`MATCH (n:labelt)
WHERE n.Property = 'random value'
SET n.nProperty = 'new value'`
In above case all nodes with labelt and with property 'Property' that equals to a new balue random value will be selected and their new property will be updated to new value.

Another method can be to update nodes of a specific label:
1. In above scenario by just eliminating the condition in match clause you can update all the nodes.
SQL:
  `MATCH (n:labelt)
  SET n.newProperty = 'new value'`
In above case all nodes with labelt will have new property updated to a new value 


Using above 2 ways you can update properties of multiple nodes in graph database using a single query without specifying each node individually.

**Comment by dukeofhazardz** [comment]
In order to modify nodes that have a particular label, you can use the `MATCH` clause to locate all nodes with that specific label. Following that, you can utilize the `SET` clause to update the properties you desire. Here's an example of your modified:
```MATCH (n:label4)
SET n.property = 'value'
```
In this example, all the nodes with the label `label4` will have their new "property" set to the new 'value'.

But if you want to update the nodes based on a specific property value, you can use the `MATCH` clause to specify the condition for the property value and then use the `SET` clause to update the desired properties. The updated query will be;
```
MATCH (n:label4)
WHERE n.property = 'value'
SET n.property = 'value'
```
So only the nodes with label "label4" which meets the `WHERE` condition will have their "property" set to 'value'.

**Comment by Hamza-Mushtaque** [comment]
Yes, you can update properties for multiple nodes without specifying each node individually by using the `MATCH` clause with a condition to select the desired nodes and the `SET` clause to update their properties. Here's an example of how you can achieve this:

```cypher
MATCH (n:label4)
WHERE n.property = "write the value you wanna target" 
SET n.newProperty = ' write new value you want'
```

In the above query, the `MATCH` clause selects all nodes with the label `label4`. The `WHERE` clause filters the nodes based on their  property. The `SET` clause then updates the `newProperty` for the selected nodes to the specified value ('new value' in this example).

I hope this helps you.

**Comment by RahimullahShaheen** [comment]
Not only you can update the properties for multiple nodes but also you can specify the number of nodes to be changed based on a condition. To achieve this we can use the `MATCH` clause to select nodes with with specific label and to limit the number of nodes that we want the changes to, we will use `LIMIT` clause.
Here is how the query will look like

```
MATCH (n:label4)
WHERE n.property = 'val'
SET n.nproperty = 'new val'
LIMIT 5

```
the above query will change the property of the first 5 nodes to new val which has the label4 and property val.

**Comment by AhmedMo0** [comment]
Using MATCH clause without a specific id for the nodes and after that using SET clause you can modify the properties.
e.g. 
```sql
MATCH (n:label4)
WHERE n.property = 'value'
SET n.property = 'new value'
```

**Comment by shady-cj** [comment]
To update properties for multiple nodes there has to be something common with those nodes…
* one is the label… so you can do
`MATCH (n:label)`
* Second is the properties (Probably there is a property that is common among the nodes)
E.g

```
MATCH (movies)
WHERE movies.rating = 5
```
Then you can update the property..
 * You can also do the combination of the two I.e matching labels and properties that have something in common.. 
 
 
Depending on your scenario all method works and you’ll be able to update or set new properties for multiple nodes that match your query.

**Comment by Omar-Saad** [comment]
To update and add a new property to all nodes labeled `label4`, you can use the following query:

```
MATCH (n:label4)
SET n.newProperty = 'new value', n.anotherProperty = 'another value'
RETURN n
```
Please note that this query will not create a new node if there are no nodes in the graph with the label `label4`.

If you want to create a new node or update existing ones, you can use the `MERGE` clause:

```
MERGE (n:label4)
SET n.newProperty = 'new value', n.anotherProperty = 'another value'
RETURN n
```
The `MERGE` clause is useful when you want to ensure that a node exists before performing any updates or inserts. In this case, the `MERGE` clause will create a new node if it doesn't exist with the label `label4`, or update the existing nodes if they do.

**Comment by abdulmanann** [comment]
Absolutely, you can update properties of multiple nodes in a single query without specifying each node individually. The answers provided have illustrated this well.

1. **Update nodes based on a condition**:
    ```cypher
    MATCH (n:label) WHERE n.Property = 'existing value' 
    SET n.newProperty = 'new value'
    ```
In this case, all nodes with the specified label and the property that matches the given existing value will have their newProperty updated to 'new value'.

2. **Update all nodes of a specific label**:
    ```cypher
    MATCH (n:label)   
    SET n.newProperty = 'new value'
    ```
Here, all nodes with the given label will have their newProperty updated to 'new value', irrespective of their current properties.

You can choose between these methods based on whether you want to update properties of all nodes of a specific label or only those nodes that meet certain conditions.

**Comment by humzakt** [comment]
Yes, you can indeed update properties for multiple nodes without specifying each node individually. The exact query will depend on your specific criteria for which nodes to update, but here is an example:
```
MATCH (n:label4)
WHERE n.someProperty = 'some value'
SET n.newProperty = 'new value'
```

In this query, MATCH (n:label4) matches all nodes with the label "label4". The WHERE clause filters these nodes to only those where someProperty has the value 'some value'. Then, SET n.newProperty = 'new value' updates the newProperty attribute of these nodes to 'new value'.

**Comment by Zeesh-an** [comment]
You can update multiple nodes with single query. This can be done in two ways:
1) Based on Condition
```
MATCH (n:label)
WHERE n.Property = 'previousValue'
SET n.newProperty = 'updatedValue'
```
2) All nodes of a specific label
```
MATCH (n:label)
SET n.newProperty = 'updatedValue'

```

**Comment by waleedahmed0001** [comment]
Yes, you can update properties for multiple nodes using a single query. The recommended approach is to use the MATCH clause with a condition to match the desired nodes, and then use the SET clause to update the properties. Here's an example:

```
MATCH (n:label4)
WHERE n.id IN [123, 456, 789]
SET n.newProperty = 'new value'
```

In this example, the MATCH clause matches all nodes with the label "label4". The WHERE clause filters the nodes based on their "id" property, using the IN operator to specify a list of IDs you want to update. Finally, the SET clause updates the "newProperty" of the matched nodes to the desired value ('new value' in this case).

You can adjust the WHERE clause condition to match the specific criteria for your nodes. For example, you can use a range of IDs or other property conditions to select the nodes you want to update.

Note that it's important to be careful when updating properties for multiple nodes, as a poorly constructed query can result in unintended updates. Always double-check your query and consider running a sample query with a RETURN clause before executing the SET operation to ensure you are targeting the correct nodes.

**Comment by mahinash26** [comment]
```
MATCH (n:label4)
WHERE n.property = "old value" 
SET n.newProperty = "new value"
```


1. Select all nodes with the label label4: MATCH (n:label4)
2. Filter the nodes based on a specific property value: WHERE n.property = "old value"
3. Update the newProperty for the selected nodes to a new value: SET n.newProperty = "new value"


I hope this helps.

**Comment by AadilBashir489** [comment]
Yes, you can update multiple nodes with single query. You can use either of the two methods below:
1. Conditional base:
    `MATCH (n:label)
WHERE n.Property = 'oldValue'
SET n.newProperty = 'newValue'`

2. Updating all nodes of a specific label:
   `MATCH (n:label)
SET n.newProperty = 'updatedValue'`

I hope this helps you.

**Comment by moiz697** [comment]
MATCH (n:Label)
WHERE n.property = value
SET n.property = newValue

You can use this to add multiple nodes at once
