### ISSUE TITLE
Dockerfile as a development environment

### ISSUE THREAD

**Issue by panosfol** [apache/age#936]
**Is your feature request related to a problem? Please describe.**

Contributors should also have an option to develop using docker containers. As of today, this is partially possible, except in some cases.

Using docker containers as my development environment, solves two problems for me:
* Having different Postgres & Age(e.g. PG11 & PG12) tags
* Leave host Postgres installation intact, such that it won't disturb other databases running, which may or may not be irrelevant to AGE

The current Dockerfile instructions cannot do that. I have locally developed an additional Dockerfile that I'm using as a developer.

**Describe the solution you'd like**

An additional Dockerfile called Dockerfile.dev that also provide the necessary infrastructure, such that regression tests can run during the building phase of the container, allowing us to catch regression failed tests early.

**Describe alternatives you've considered**

Manually attaching to the container and do what's necessary for tests to run. This is a very time consuming alternative.

**Comment by Munmud** [comment]
Hey I made a pr #422 for adding the instruction. It took me lots of time to manually find how to go through docker cli as there is `username` and `password` dependency to access it
