### ISSUE TITLE
Installing AGE to be used with PostgresQL v13 on Windows

### ISSUE THREAD

**Issue by asltjoey** [apache/age#94]
Hello AGE team,

I am a data analyst trying to install AGE extension for my PostgreSQL v13 and lack of database admin expertise. Here is what I have gone through so far.

- Had PostgreSQL v13 installed on my windows laptop and have been using it for quite a while
- Recently downloaded the apache-age-0.4.0-incubating-src.tar file
- Updated the path environment variable by adding this D:\Program Files\PostgreSQL\13\bin\pg_config
- Have also downloaded the Apache AGE Guide pdf but it doesn't mention how to install on windows. Therefore, I got stuck there and have no idea how to proceed.

Looking forward to your guidance.

Thank you very much.

**Comment by emotionbug** [comment]
not supporting PG 13, yet. First, they will focus on page 11 and then be work for newer PG versions.

**Comment by joefagan** [comment]
Hi Prakasit

Is your priority to look at AGE on windows or on PG 13.

If windows is your priority we can get AGE to work in Docker. Is this of interest?

Thanks
Joe

**Comment by asltjoey** [comment]
Hi Joe,

The data I'm playing with is in the enterprise server, also a PG 13, and I am using my laptop with PG 13 installed to do some testing. Based on this understanding, I think the priority is much on PG 13.

Thanks,
Prakasit

**Comment by muhammadshoaib** [comment]
A stable version of PG13 is out. Therefore we are closing this issue. Therefore issue is being closed.

**Comment by ShanGor** [comment]
There is a binary ship with PG17 (Not for PG13), if you want to compile it by yourself, you can ref to it too.
https://github.com/ShanGor/apache-age-windows
