### ISSUE TITLE
Typo in exists() predicate function documentation

### ISSUE THREAD

**Issue by shady-cj** [apache/age#950]
Using the exists(expression) one can check for a property or path… according to the example given in the documentation [here](https://age.apache.org/age-manual/master/functions/predicate_functions.html) the following examples raised errors.

```
SELECT * FROM cypher('graph_name', $$
 MATCH (n)
 WHERE exists(n)-[]-(name: 'Willem Defoe')
 RETURN n.full_name
$$) as (full_name agtype);
```

**The following error was raised**

```

ERROR:  syntax error at or near ")"
LINE 3:  WHERE exists(n)-[]-(name: 'Willem Defoe')
                       ^

```

**Expected behavior**
The expected behavior is to return either `null` or `surname` of agtype that matches the `WHERE` clause 

**The expected query**

The expected query that worked is the following 

```

SELECT * FROM cypher('graph_name', $$
 MATCH (n)
 WHERE exists((n)-[]-({name: 'Willem Defoe'})) 
 RETURN n.full_name 
$$) as (full_name agtype);

```

**Comment by titoausten** [comment]
Yes, `exists()` takes only `n` a vertice as an argument whereas it is supposed to take a path.

**Comment by KamleshKumar427** [comment]
Yes, You noticed right, there is a typo in the documentation.
Apache-age documentation is maintained under another GitHub repo at:
https://github.com/apache/age-website

You can correct that typo and create a PR, or open an issue at that GitHub repo.

**Comment by abdullahzia-6464** [comment]
Your issue has been noted. I have opened a [pull request](https://github.com/apache/age-website/pull/160) in the relevant repository to update the documentation.

**Comment by AhmedMo0** [comment]
You are right. EXISTS clause take argument property which is a vertex or a path so, in this example it should be like this 
`WHERE exists((n)-[]-(name: 'Willem Defoe'))`

**Comment by Omar-Saad** [comment]
The documentation contains a syntax error, and the query should be modified as you mentioned.

```

SELECT * FROM cypher('graph_name', $$
 MATCH (n)
 WHERE exists((n)-[]-({name: 'Willem Defoe'})) 
 RETURN n.full_name 
$$) as (full_name agtype);
```

You can create a PR to correct this error.
