### ISSUE TITLE
How to edit node label name ?

### ISSUE THREAD

**Issue by Munmud** [apache/age#969]
```sql
SELECT * from cypher('munmud', $$
CREATE 
(:Movie {id: 'movie1', name: 'The Shawshank Redemption', imdbRank : 25}),
(:Movie {id: 'movie2', name: 'The Godfather', imdbRank : 60}),
(:Movie {id: 'movie3', name: 'The Dark Knight', imdbRank : 100})
$$) as (V agtype);
```
how to change all label name from `Movie` to `OldMovie`

**Comment by Zainab-Saad** [comment]
At present, the label names can not be changed. Take a look at this [issue](https://github.com/apache/age/issues/464)

**Comment by jrgemignani** [comment]
The only way to do it would be to recreate the node with the new label and then delete the old node.

**Comment by Omar-Saad** [comment]
Currently you can't change label name in Apache AGE. 

So, you have to recreate them with the new label then delete the old ones and you can do this with only one query.

```
MATCH (m:Movie)
CREATE (om:OldMovie)
SET om = m
REMOVE m:Movie
RETURN om
```

This query first matches all nodes with `Movie` label and then creates a copy of it with a new label `OldMovie`.

**Comment by shady-cj** [comment]
It’s not possible at the moment.  The work around is to create a new node using the properties of the old node to create the new node..
