### ISSUE TITLE
Analyse MATCH clause performance (shortest path)

### ISSUE THREAD

**Issue by rafsun42** [apache/age#984]

**Comment by Omar-Saad** [comment]
You can analyze any query performance using `EXPLAIN` keyword.

```
EXPLAIN MATCH(n) RETURN n
```
This query will return the execution plan, cost, time of your query.

Also you can take a look on this tutorial: [Mastering Query Performance Analysis and Query Plan Understanding in Apache AGE](https://dev.to/omarsaad/mastering-query-performance-analysis-and-query-plan-understanding-in-apache-age-56d)
