### ISSUE TITLE
Write Useful Print message for test_agtypes

### ISSUE THREAD

**Issue by Munmud** [apache/age#991]
When I am testing `test_agtypes.py` file its not showing what we are testing. Instead its showing some garbage print. Writing some good print message might be a good idea

###  Test Result
--------------------------
![Screenshot from 2023-06-15 06-25-15](https://github.com/apache/age/assets/53787290/b306b230-b802-43df-8ef4-e6b83cf236cc)

**Comment by titoausten** [comment]
Using `pynose` might be useful here for formatting.
