### ISSUE TITLE
how we start develop compatibility with distributed database function of Citus

### ISSUE THREAD

**Issue by iitaejeong** [apache/age#996]
I recently saw the Citus Paper (https://dl.acm.org/doi/10.1145/3448016.3457551). They suggest the multi-tenant system for distributed database system through engineering skills. among them, i think the high-performance CRUD by reference table and index is good synergy with AGE. because of 'indexing' function.

I think the AGE can index function unlike Neo4j graph database (native vs. non-native). AGE is non-native but can use indexing of graph by assignment. so whoever wants to develop this project? not intervene low-level code(C++) only high-level code(SQL).

**Comment by M4rcxs** [comment]
I was researching about Citus and other alternatives for the problem, I have found this article at `db-engines`. 



Name | Citus  X | Memgraph  X | Postgres-XL  X
-- | -- | -- | --
Description | Scalable hybrid operational and analytics RDBMS for big data use cases based on PostgreSQL | An open source graph database built for real-time streaming and compatible with Neo4j | Based on PostgreSQL enhanced with MPP and write-scale-out cluster features



- Link for the complete descriptions and features: [Citus comparative article](https://db-engines.com/en/system/Citus%3BMemgraph%3BPostgres-XL)

**Comment by iitaejeong** [comment]
@M4rcxs thanks your information. wow Memgraph can sharding but they can't multi-modal model(not compatible with SQL).

**Comment by Hannan2910** [comment]
We have started this project and have tried to use citus exposed symbols and querries to shard tables created for the graphs vetices and edges. The use of reference tables ad colocation is rather favorable for AGE. We are still debating on how to approach automatic sharding of tables on creation and how to dynamically link Citus exposed symbols within  AGE's code.

**Comment by MuhammadZeeshan03** [comment]
Citus introduces two types of tables to PostgreSQL: `Distributed tables` and `Reference tables`, These tables are initially created as regular PostgreSQL tables, and then they are converted by calling Citus-specific functions. So, to make AGE compatible we have to work on calling these functions in our AGE's source code. If these are enough we are good to go.
