### ISSUE TITLE
Isn't there a good documentation for understanding how python/node.js drivers work

### ISSUE THREAD

**Issue by Mghrabi** [apache/age#999]

**Comment by waleedahmed0001** [comment]
It's is mentioned in the readme of the Apache age official GitHub link.
Python Driver:

[Github ReadMe link](https://github.com/apache/age/blob/master/drivers/python/README.md)

Node Driver:

[Github ReadMe link](https://github.com/apache/age/blob/master/drivers/nodejs/README.md)

**Comment by Chidera6** [comment]
Just as @waleedahmed0001 said, it is mentioned in the README of the official Github link, if you have more questions I think you should ask those working on AGE drivers [here](https://discord.com/channels/1022177873127280680/1022184647460917360) on discord.

**Comment by AhmedMo0** [comment]
You can find examples for using NodeJs driver and Apache AGE documentation [here](https://github.com/apache/age/tree/master/drivers/nodejs). As @Chidera6 said you can know more about drivers on discord

**Comment by RahimullahShaheen** [comment]
Though we do not have a detailed documentation about python or node js driver but on the official age github repository in the built-in section there is a read me file for each driver which contains enough information to get you started.
